#!/bin/bash
#
# /usr/lib/magos/scripts/cfg_mnger
#
# Description: Configs Manager 
# Author : Anton Goroshkin <http://magos-linux.ru>

export PATH=/usr/lib/magos/scripts:$PATH

cXdialog --msgbox "Утилита управления конфигурационными файлами находится в разработке. \n Вы можете использовать текстовый редактор для настройки MagOS.ini."
CFGFILE=/mnt/livedata/MagOS-Data/MagOS.ini
[ -f $CFGFILE ] || CFGFILE=/mnt/livemedia/MagOS-Data/MagOS.ini
[ -f $CFGFILE ] || CFGFILE=/mnt/livemedia/MagOS/MagOS.ini
editor_root $CFGFILE
