#!/bin/bash
#
# /usr/lib/magos/scripts/cfg_mnger
#
# Description: Configs Manager 
# Author : Anton Goroshkin <http://magos-linux.ru>

export PATH=/usr/lib/magos/scripts:$PATH
MSG="You can use a text editor to change settings in MagOS.ini."
echo $LANG | grep -qi ^ru_ && MSG="Вы можете использовать текстовый редактор для настройки MagOS.ini."
cXdialog --msgbox "$MSG"
CFGFILE=/mnt/livedata/MagOS-Data/MagOS.ini
[ -f $CFGFILE ] || CFGFILE=/mnt/livemedia/MagOS-Data/MagOS.ini
[ -f $CFGFILE ] || CFGFILE=/mnt/livemedia/MagOS/MagOS.ini
if [ -w $CFGFILE -a -w $(dirname $CFGFILE) ] ;then
  editor $CFGFILE
else
  editor_root $CFGFILE
fi
