#!/bin/bash
#
# /usr/lib/magos/scripts/createloop
#
# Description: Create loop
# Author : Anton Goroshkin <http://magos-linux.ru>
# Last edited : Mikhail Zaripov <http://magos-linux.ru>

# $1=filename
# $2=size

if [ "$1" == "" -o "$1" == "--help" ] ;then
  echo Create encrypted loopback file
  echo Usage: $0 filename size[GgMmKk] [options for cryptsetup]
  exit 0
fi

FNAME="$1" ; shift
SIZE=$(echo $1 | tr -d [a-z][A-Z])
METR=$(echo $1 | tr -d [0-9])
METR=$(echo $METR | tr [a-z] [A-Z])
shift

echo Creating encrypted filesystem $FNAME with size $SIZE x 1${METR}bytes.

dd if=/dev/zero of="$FNAME" bs="$SIZE" count=1$METR >/dev/null

cryptsetup close magosnewencloop0 2>/dev/null

read -pPassword: ; echo $REPLY | cryptsetup open --type loopaes ""$FNAME"" magosnewencloop0 --key-file - $@

mkfs.ext3 /dev/mapper/magosnewencloop0 

cryptsetup close magosnewencloop0
