#!/bin/bash
# convert directory tree into .xzm noncompressed file
# which can be used as a LiveCD module
#
# Author: Tomas M. <http://www.linux-live.org>
#
# Author: Anton Goroshkin <http://magos-linux.ru>

. /usr/lib/magos/functions || exit 1

echo "This script is obsolete and possibly will be removed in future. Please use dir2xzm -b "

if [ ! -d "$1" -o "$2" = "" ]; then
   echo
   echo "Convert directory tree into .xzm noncompressed module."
   echo "usage: $0 source_directory output_file.xzm"
   exit 1
fi

addparam=

create_module "$1" "$2" -noI -noD -noF $addparam
#create_module "$1" "$2"
if [ $? != 0 ]; then echo "error building compressed image"; exit 1; fi
