#!/bin/bash
if [ "$(id -un)" != "root" ] ;then
   gksu -g "/bin/bash $0 $@"
   exit 0
fi

export PATH=/usr/lib/magos/scripts:$PATH

. /usr/lib/magos/functions
. /usr/lib/magos/os-config

MODULEFORMAT=xzm

case $1 in
   --nocompress )
      shift
      create_module "$1" "$1.noxz.$MODULEFORMAT" -noI -noD -noF
      ;;
   --oldpc )
      shift
      create_module "$1" "$1.oldpc.$MODULEFORMAT" $MKSQFS_FASTALG 
      ;;
   * )
      create_module "$1" "$1.$MODULEFORMAT"  
      ;;
esac
if [ $? -eq 0 ] ; then
   mdialog --msgbox "Модуль готов"
else
   mdialog --error "Ошибка при создании модуля"
fi
