#!/bin/bash

# /usr/lib/magos/scripts/dir2mod
#
# Description: Convert DIRs to Modules 
# Author : Anton Goroshkin <http://magos-linux.ru>

MODULEFORMAT=xzm

#convert DIRs to XZMs
# $1 = directory images
# $2 = directory of XZMs
# $3 = mask of dirname (ex. - "??-" )
convert_dir2xzm()
{
  echo "Converting DIRs to module:"
  for a in `ls -d $1/$3*`; do
    mn=$(basename $a)
    fd="$2/$MODULEFORMAT/$mn"
    echo "$fd" | grep -q [.]$MODULEFORMAT$ || fd="$fd".$MODULEFORMAT
    echo -ne \\n"   converting $mn --> $fd "\\n
    mkdir -p "$2/$MODULEFORMAT"
    dir2xzm "$a" "$fd"
  done
}

#convert DIRs to XZMs with usian a fast algorithm for slow pc
# $1 = directory images
# $2 = directory of XZMs
# $3 = mask of dirname (ex. - "??-" )
convert_dir2fastxzm()
{
  echo "Converting DIRs to module (fast algotithm):"
  for a in `ls -d $1/$3*`; do
    mn=$(basename $a)
    fd="$2/fast_$MODULEFORMAT/$mn"
    echo "$fd" | grep -q [.]$MODULEFORMAT$ || fd="$fd".$MODULEFORMAT
    echo -ne \\n"   converting $mn --> $fd (fast algorithm)"\\n
    mkdir -p "$2/fast_$MODULEFORMAT"
    dir2xzm -f "$a" "$fd"
  done
}

#convert DIRs to XZMs noxzm
# $1 = directory images
# $2 = directory of XZMs
# $3 = mask of dirname (ex. - "??-" )
convert_dir2noxzm()
{
  echo "Converting DIRs to module (no compression):"
  for a in `ls -d $1/$3*`; do
    mn=$(basename $a)
    fd="$2/nocomp_$MODULEFORMAT/$mn"
    echo "$fd" | grep -q [.]$MODULEFORMAT$ || fd="$fd".$MODULEFORMAT
    echo -ne \\n"   converting $mn --> $fd (no compression)"\\n
    mkdir -p "$2/nocomp_$MODULEFORMAT"
    dir2xzm -b "$a" "$fd"
  done
}

#convert DIRs to ROMs 
# $1 = directory images
# $2 = directory of ROMs
# $3 = mask of dirname (ex. - "??-" )
convert_dir2rom()
{
  echo "Converting DIRs to ROMs:"
  for a in `ls -d $1/$3*`; do
    mn=$(basename $a)
    echo "	converting $mn --> $mn.rom"
    st=`du -s -m $a ` 
    size_mod=${st%%$a}
    size_mod=$[$size_mod+100]
    mkdir -p "$2/roms" "$2/roms/$mn"
    dd if=/dev/zero of="$2/roms/$mn.rom" bs=1M count=0 seek=$size_mod 2>/dev/null
    echo y | mkfs.ext3 -q "$2/roms/$mn.rom" >/dev/null
    echo "virtual size: [$size_mod"."M]"
    mount -o loop "$2/roms/$mn.rom" "$2/roms/$mn"
    cp -a "$a/*" "$2/roms/$mn" 2>/dev/null
    umount "$2/roms/$mn"
    rm -rf "$2/roms/$mn"

  done
}

HELP()
{
   echo
   echo "#####################################"
   echo "Convert directory tree into modules" 
   echo
   echo -ne "Usage:\\n	$0 xzm|noxzm|fastxzm|rom source_directory destination_directory mask \\n"
   echo -ne "Example:\\n	./dir2mod noxzm /mnt/live/memory/images /mnt/livemedia/MagOS/modules/ ??- \\n"
   echo
   echo "#####################################"   
   echo
}

. /usr/lib/magos/functions

case $1 in
  -h | --help )
  HELP ;;

  --test )
  TEST ;;

  * )
  cmd=$1
  [ "$cmd" != "xzm" -a "$cmd" != "noxzm" -a "$cmd" != "rom" -a "$cmd" != "fastxzm" ] && cmd=
  shift

  if [ ! -d "$1" -o "$2" = "" -o "$cmd" = "" ]; then
    HELP
    exit 1
  fi
  convert_dir2$cmd "$@"
  if [ $? != 0 ]; then echo "error building modules "; exit 1; fi
  ;;
esac

#convert_dir2rom "$1" "$2" "$3"
#convert_dir2sqm "$1" "$2" "$3"
