#!/bin/sh
EDITORS="/usr/bin/kwrite /usr/bin/gedit /usr/bin/leafpad"
PREF=/usr/bin/leafpad

. /usr/lib/magos/functions

DE=$(detectDE)

case "$DE" in
    kde|plasma)
    PREF=/usr/bin/kwrite
    ;;

    gnome|gnome-shell)
    PREF=/usr/bin/gedit
    ;;
esac

for a in $PREF $EDITORS ;do
    [ -x $a ] || continue
    [ -z "$1" ] && $a || $a "$1"
    break
done
