#!/bin/sh
#Find file in mounted or installed .pfs packages
#VERSION 3.6
. $(which pfs)

case "$1" in 
  "") echo "Usage: $(basename "$0") FILE"; exit 1;;
  "-"*[A-Za-z]*) echo "$(basename "$0"): invalid option -- '$(echo $1 | tr -d '-')'" >&2; exit 1;;
  *) findname="$1";;
esac

find "${PFSDIR}" -mindepth 3 -maxdepth 3 -type f -name 'pfs.files' | while read listfiles; do 
    cat "${listfiles}" | cut -f2- -d'/' \
	| sed -e 's:^[^/]*::' -e 's:[\]:\\\\:g' -e "s/^/`echo "${listfiles}" | cut -f5 -d'/'`/"
done | grep -F "${findname}" | cut -f1 -d'/' | sort -uf

###sfs (
p=/mnt/live/memory/images/
[ -d $p ] || exit 0
f="`basename "$1"`"
echo "
--------------- in meta.pfs : ------------------\
"
find "$p" \( -type f -o -type l \) -name "$f" |sed 's#^'$p'## ; s/'$f'$//' 
exit 0
