#!/bin/sh
FMANAGERS="/usr/bin/dolphin /usr/bin/nautilus /usr/bin/pcmanfm /usr/bin/pcmanfm-qt"
PREF=/usr/bin/dolphin

. /usr/lib/magos/functions

DE=$(detectDE)

case "$DE" in
    gnome|gnome-shell)
    PREF=/usr/bin/nautilus
    ;;

    lxde)
    PREF=/usr/bin/pcmanfm
    ;;

    lxqt)
    PREF=/usr/bin/pcmanfm-qt
    ;;
esac

for a in $PREF $FMANAGERS ;do
    [ -x $a ] || continue
    [ -z "$1" ] && $a || $a "$1"
    break
done
