#!/bin/sh
PVIEWERS="/usr/bin/gwenview /usr/bin/gqview /usr/bin/gpicview"
PREF=/usr/bin/gpicview

. /usr/lib/magos/functions

DE=$(detectDE)

case "$DE" in
    kde|plasma)
    PREF=/usr/bin/gwenview
    ;;

    gnome|gnome-shell)
    PREF=/usr/bin/gqview
    ;;
esac

for a in $PREF $PVIEWERS ;do
    [ -x $a ] || continue
    [ -z "$1" ] && $a || $a "$1"
    break
done
