#!/bin/bash
# /usr/lib/magos/scripts/mdialog
#
# Helper Library for scripts
#
# Author: Alexandr Betkher <http://magos-linux.ru>
# Author: Anton Goroshkin <http://magos-linux.ru>
#

export PATH=/usr/lib/magos/scripts:/usr/lib/qt4/bin:$PATH

. /usr/lib/magos/functions

PREFIX=none
DE=$(detectDE)

[ -f /usr/bin/zenity ] && PREFIX=ZENITY

if [ "$DE" == "plasma" -o "$DE" == "kde" ] ; then
    [ -f /usr/bin/kdialog ] && PREFIX=KDIALOG
else
    # if session is not KDE, but zenity is not exist - use kdialog
    [ $PREFIX == none ] &&  [ -f /usr/bin/kdialog ] && PREFIX=KDIALOG
fi

[ $PREFIX == none ] && echo "no zenity and kdialog in system" && exit -1

if [ "$1" == "RESTARTED" ] ; then
    RESTARTED='yes'
    shift
fi 
# restart mdialog with xuserrun  
if [ "$(id -un)" = "root" -a ! "$RESTARTED" ] ;then
    xuserrun  $0 RESTARTED "$@" ; exit
fi

XAUTH=$(ps -p $(pgrep Xorg) -o cmd |tail -n1 |sed 's#\(.*-auth \)\(/\S*\)\( -.*$\)#\2#')
[ -f "$XAUTH" ] && export XAUTHORITY="$XAUTH"

ZENITY--radiolist() {
	text="$2"
	shift ; shift
	for val in "$@" ; do
	echo \""$val"\" |sed -e 's/on/TRUE/' -e 's/off/FALSE/'
	done |tac | xargs \
	zenity --list --text="$text" --column= --column= --column=return  --hide-column=3 --print-column=3 --radiolist  
}
KDIALOG--radiolist() {
	shift
	kdialog --radiolist "$@"
}

ZENITY--checklist() {
	text="$2"
	shift ; shift
	for val in "$@" ; do
	echo \""$val"\" |sed -e 's/on/TRUE/' -e 's/off/FALSE/'
	done |tac | xargs \
	zenity --list --text="$text" --column= --column= --column=return  --hide-column=3 --print-column=3 --checklist | \
	sed -e 's/^/"/' -e 's/$/"/' -e 's/|/" "/g'   
}
KDIALOG--checklist() {
	shift
	kdialog --checklist "$@"
}

KDIALOG--password () {
	kdialog --password "$2"
}

ZENITY--password() {
	zenity --password --title="$2"
}


KDIALOG--msgbox () {
    kdialog --msgbox "$2"
} 

ZENITY--msgbox () {
    zenity --info --text="$2"
} 

KDIALOG--sorry () {
    kdialog --sorry "$2"
} 
ZENITY--sorry () {
    zenity --warning --text="$2"
} 

KDIALOG--error () {
    kdialog --error "$2"
} 

ZENITY--error () {
    zenity --error --text="$2"
} 

KDIALOG--yesno ()  {
    kdialog --yesno "$2"
} 
ZENITY--yesno () {
    zenity --question --text="$2"
} 

KDIALOG--inputbox () {
    kdialog --inputbox "$2" "$3"
} 
ZENITY--inputbox () {
    zenity --entry --text="$2" --entry-text="$3"
} 

KDIALOG--textbox () {
    kdialog --textbox "$2"
} 

ZENITY--textbox () {
    zenity --text-info --filename="$2"
} 

# параметр работает как в zenity читает из файла
KDIALOG--textinputbox () {
    kdialog --textinputbox  "Просмотр текста" "$(cat $2)"
} 

ZENITY--textinputbox () {
    zenity --text-info --editable --filename="$2"
} 

KDIALOG--passivepopup () {
    kdialog --passivepopup "$2" 5
} 
ZENITY--passivepopup () 
{
    notify-send "$2" || zenity --notification --text="$2"
} 

KDIALOG--getopenfilename () {
    kdialog --getopenfilename `pwd`  
} 

ZENITY--getopenfilename () {
    zenity --file-selection 
} 

KDIALOG--getsavefilename () {
    shift
    filter=$1
    shift
    kdialog --getsavefilename `pwd` $filter $@
} 

ZENITY--getsavefilename () {
    shift
    filter=$1
    shift
    zenity --file-selection --save --file-filter=$filter $@
} 

KDIALOG--getexistingdirectory  () {
    shift
    dir_name=`pwd`
    if [ ! "$1" = "" ]; then 
        dir_name=$1 
    fi
    kdialog --getexistingdirectory $dir_name
}

ZENITY--getexistingdirectory  () {
    shift
    dir_name=$(pwd)
    if [ ! "$1" = "" ]; then 
        dir_name=$1 
    fi
    cd $dir_name
    zenity --file-selection --directory
} 

KDIALOG--calendar () {
    kdialog --calendar "$2"  
} 

ZENITY--calendar () {
    zenity --calendar  --date-format=%a" "%B" "%d" "%Y --text="$2" 
} 


KDIALOG--menu () {
    shift
    kdialog --menu "$@"  
} 

ZENITY--menu () {
    text=$2
    shift 2
    zenity --list --text="$text" --column=1  --column=2 --hide-header --print-column=1 --hide-column=1 "$@"
    exit 
} 


KDIALOG--progressbar () {
    stdifs=$IFS
    dbusRef=`kdialog --progressbar "Подождите пожалуйста...." $#`
    inc=1
    shift
    for arg in "$@"; do  
	qdbus $dbusRef Set "" value $inc
	IFS=: 
	$arg
	IFS=$stdifs
	inc=`expr $inc + 1`
    done
    qdbus $dbusRef Set "" value $inc
    sleep 1
    qdbus $dbusRef close 
    exit 0
} 

ZENITY--progressbar () {
    IFS=:
    shift
    per=$(expr 100 / $#)
    [ $per -eq 0 ] && per=1
    inc=$per
    > /tmp/progress.tmp
    for arg in "$@" ; do
	echo "$inc"
	sleep 0.1
	$arg  >> /tmp/progress.tmp
	inc=$(expr $per + $inc) > /dev/null
    done | zenity --progress  --auto-close  --percentage=0 --text="Подождите пожалуйста..." 
    cat /tmp/progress.tmp
    rm -f /tmp/progress.tmp
}
 

HELP () 
{
    echo  "Скрипт $0, автоматически использует для создания графического интерфеса"
    echo  "zenity либо kdialog, в зависимости от их наличия и среды KDIALOG. GNOME, etc"
    echo  "Синтаксис максимально повторяет kdialog, но есть и расхождения."

    echo  "--yesno <text>            Вопросительный диалог с кнопками да/нет"
    echo  "--sorry <text>            Диалог с сообщением об ошибке"
    echo  "--error <text>            Диалог "Ошибка""
    echo  "--msgbox <text>           Информационный диалог"
    echo  "--inputbox <text> <init>  Диалог ввода"
    echo  "--textbox <file>  Диалог с текстом"
    echo  "--textinputbox <text> <file> Диалог ввода текста (отличается от kdialog)"
    echo  "--menu <text> [tag item] [tag item] ... Диалог с меню"
    echo  "--passivepopup <text>  Пассивное всплывающее окно"
    echo  "--getopenfilename   Диалог открытия существующего файла (начальный каталог - текущий)"
    echo  "--getsavefilename [filter]  Диалог сохранения файла (начальный каталог - текущий)"
    echo  "--getexistingdirectory [dir] Диалог выбора существующего каталога (начальный каталог - текущий или [dir])"
    echo  "--progressbar Отличается от zenity/kdialog. mdialog --progressbar команда1:параметр1:параметр2 команда2:параметр1 и т.д."
    echo  "              Избегайте пробелов в именах файлов. Варинт не идеален, предложите лучше изменим :-)"
    echo  "--calendar      Диалог с календарём, возвращает выбранную дату."
    exit
}

TEST () 
{
    echo "команда mdialog --msgbox \"error и sorry использовать аналогично\""
    $0  --msgbox "error и sorry использовать аналогично"
    echo "команда mdialog --yesno \"возвращает 0 либо 1 зависимо от нажатой кнопки\""
    $0 --yesno "возвращает 0 либо 1 зависимо от нажатой кнопки"
    echo $?
    echo "команда mdialog --inputbox \"заголовок\" \"строка\""
    $0 --inputbox "заголовок" "строка"
    echo "команда mdialog --textbox mdialog" 
    $0 --textbox /etc/os-release
    echo "команда mdialog --textinputbox mdialog"
    $0 --textinputbox /ect/machine-id
    echo "команда mdialog --progressbar sleep:1 sleep:1 ls:-R ls:/etc" 
    $0 --progressbar sleep:1 sleep:1 ls:-R ls:/etc
    echo "команда mdialog --passivepopup \"тест окончен\"" 
    $0 --passivepopup "тест завершен"
    exit
}

cmd=$1
if [ "$cmd" = "" ]; then
    cmd="-h" 
fi

case $cmd in
    -h | --help )
    HELP ;;

    --test )
    TEST ;;

    * )
    XAUTHORITY="$XAUTH" $PREFIX$cmd "$@" ;;
esac
