#!/bin/sh
export TERM=linux

PORT=/dev/modem
[ $1  ] && PORT=$1

AT=AT
[ $2 ] && AT=$2

#максимальное время ожидания инициализации модема
COUNTER=10

#время отведенное на ответ модема после инициализации
TIMEOUT=1
[ $3 ] && TIMEOUT=$3

SCR=/tmp/m_script
OST=/tmp/lastcheck
tmp_file=/tmp/modem_out
: >  $tmp_file

echo -n "$AT" > $OST
echo "send $(cat $OST)" > $SCR

cat $PORT  > $tmp_file 2>/dev/null &
cat_pid=$(echo $!)

minicom -D $PORT -S $SCR >/dev/null 2>&1 &
minicom_pid=$(echo $!)

while [ ! -s $tmp_file -a $COUNTER -ne 0 ] ; do
sleep 1
COUNTER=$(($COUNTER - 1))
done

sleep $TIMEOUT

kill -s 9 $cat_pid > /dev/nul 2>&1
kill -s 9 $minicom_pid > /dev/null 2>&1

cat $tmp_file | while read line ;do 
echo $line | grep -v AT #здесь грепать  вывод OK,AT и т.д.
done 

[ ! -s $tmp_file ] && exit -1
exit 0
