#!/bin/bash
#
# /usr/lib/magos/scripts/mountloop
#
# Description: Mount loop 
# Author : Anton Goroshkin <http://magos-linux.ru>

dl=$(losetup -f)
/usr/lib/magos/scripts/losetupenc -e "$1" $dl "$2"
mount $dl "$3"
