#!/bin/sh
PDFVIEWERS="/usr/bin/okular /usr/bin/evince /usr/bin/zathura /usr/bin/qpdfview"
PDEF=/usr/bin/qpdfview

. /usr/lib/magos/functions

DE=$(detectDE)

case "$DE" in
    kde|plasma)
    PREF=/usr/bin/okular
    ;;

    gnome|gnome-shell|mate)
    PREF=/usr/bin/evince
    ;;
esac

for a in $PREF $PDFVIEWERS ;do
    [ -x $a ] || continue
    [ -z "$1" ] && $a || $a "$1"
    break
done
