#!/bin/bash
usage()
{
   echo "Warning ! This script returns rpm base to initial state!"
   echo
   echo "Usage: $0 --copy|--erase"
   echo "--copy  Will copy DB from module to rootfs. It is usefull for clean mode."
   echo "        It works immediately."
   echo "--erase Will clear changes in rootfs (/mnt/live/memory/changes/var/lib/rpm)."
   echo "        It is usefull for save change mode. It works after reboot."
   exit 1
}

if [ "$1" = "" ] ;then
   usage
fi

# uird/initrd vars
IMGPATH=/mnt/live/memory/images
CHPATH=/mnt/live/memory/changes
if [ -d /memory/changes ];then
   IMGPATH=/memory/bundles
   CHPATH=/memory/changes
fi

case "$1" in
   --copy)
     echo remove rpm DB ...
     rm -fr /var/lib/rpm/*
     echo copy initial rpm DB ...
     find "$IMGPATH" -maxdepth 4 -path "*/var/lib/rpm" | sort | while read a ;do
       echo  "$a -> /var/lib/rpm"
       cp -prf "$a"/* /var/lib/rpm
     done
     echo Done.
     ;;
   --erase)
     echo remove rpm DB changes ...
     rm -fr "$CHPATH/var/lib/rpm"
     echo Done. Please reboot.
     ;;
   *)
     usage
     ;;
esac
