#!/bin/bash
#
# /usr/lib/magos/scripts/rpmdrake2xzm
#
# Description: create XZM using rpmdrake (& dependences)
# Author : Anton Goroshkin <http://magos-linux.ru>
# Edited by Mikhail Zaripov <http://magos-linux.ru>

if [ "$(id -un)" != "root" ] ;then
   beesu -l "/bin/bash '$0' $@"
   exit 0
fi

export PATH=/usr/lib/magos/scripts:$PATH
MODULEFORMAT=xzm
URPMITMP=/tmp/rpmdrake2xzm
mod_path=/mnt/live/memory/images
. /usr/lib/magos/functions

root_br="$URPMITMP/root"
mod_br="$URPMITMP/changes"
mod_file="$URPMITMP/rpmdrake2xzm.img"
err=0
mount_mode="rr"
[ $(cmdline_parameter unionfs) ] && mount_mode="ro"

rm -rf "$mod_br" "$root_br" 2>/dev/null
mkdir -p "$mod_br" "$root_br"
SPACE=$(LC_ALL=C df -BM "$URPMITMP" --output=avail | tail -1 | tr -d M) # free space in folder
[ ! -z "$SPACE" ] && SPACE=$(echo "$SPACE""*80/100" | bc)        # 80% of free space in folder
[ ! -z "$SPACE" -a -z "$URPMISPACE" ] && URPMISPACE="$SPACE"M
[ -z "$URPMISPACE" ] && URPMISPACE=1024M
dd if=/dev/zero of="$mod_file" bs=1 count=0 seek="$URPMISPACE" && mkfs.ext2 "$mod_file"
mount -o loop "$mod_file" "$mod_br" || exit 1

mount_br="$mod_br=rw"
for a in `ls -d $mod_path/??-*`; do
    mount_br="$mount_br:$(readlink -f $a)=$mount_mode"
done

if [ $(cmdline_parameter unionfs) ];then
    mount -t unionfs -o dirs="$mount_br" unionfs "$root_br"
else
    mount -t aufs -o br:"$mount_br" aufs "$root_br"
fi

mkdir -p "$root_br"/{dev,proc,sys,tmp}
for tm in {dev,proc,sys}; do
    mount -o bind /$tm "$root_br"/$tm
done

/usr/sbin/rpmdrake --rpm-root="$root_br" --urpmi-root="$root_br"  $@
if [ $? != 0 ] ;then
    echo "Error rpmdrake RPMs install";
    err=1
fi
[ ! -f "$mod_br/var/lib/rpm/Packages" ] && err=1 # nothing was installed

echo "Unmounting filesystems..."
grep "$root_br"/ /proc/mounts | awk '{ print $2}' | sort -r | while read tm ;do
      umount "$tm"
done
umount "$root_br"

rm -rf "$mod_br/tmp" "$mod_br/var/tmp" "$mod_br/var/cache/urpmi" "$mod_br/etc/urpmi" "$mod_br"/var/lib/{rpm,menu,urpmi} "$mod_br/usr/share/applications/mimeinfo.cache" "$mod_br"/.wh* 2>/dev/null
find "$mod_br/usr/share/icons" -type f -name icon-theme.cache 2>/dev/null | xargs rm -f 
rmdir "$mod_br"/{dev,proc,sys,lost+found} "$mod_br/var/cache" "$mod_br/var/lib" "$mod_br/var" "$mod_br/etc" 2>/dev/null

cd /mnt/livedata/MagOS-Data/optional || cd /mnt/livemedia/MagOS-Data/optional || cd /mnt/livemedia/MagOS/optional

if [ "x$err" != "x1" ]; then
  while [ -z "$mod_name" -o -f "$mod_name.$MODULEFORMAT" -o -d "$mod_name.$MODULEFORMAT" -o -d "$mod_name" ]; do # checks for name. do not overwrite files
    mod_name=$(mdialog --getsavefilename *.$MODULEFORMAT) || mod_name=-1 # if Cancel
    mod_name=$(echo $mod_name | sed s/[.]$MODULEFORMAT$//) 
  done
  [ "$mod_name" = "-1" ] && err=1
  mod_name="$mod_name".$MODULEFORMAT
fi

if [ "x$err" != "x1" ]; then
    cd "$mod_br"
    xterm -e "echo 'Creating $MODULEFORMAT module, please waiting... ' && dir2xzm ./ '$mod_name'"
    chmod 664 "$mod_name"
    cXdialog --yesno "Создание модуля завершено :)\\n Подключить модуль для текущего сеанса?"
    [ $? = 0 ] && gactivate "$mod_name"
    cd /tmp
fi

umount "$mod_br"
rm -f "$mod_file"
rmdir "$mod_br" "$root_br" 
[ -h "$URPMITMP" ] || rmdir "$URPMITMP"
