#!/bin/bash

NETWORKIP=192.168.137.1

function help()
{
   cat <<EOF
$0 - share internet for android device through USB cable with using a default network 192.168.137.1/24
Usage: $0 [-a 1.2.3.4 / -a 3 ] on/off [device]

Examples:
    $0 on enp0s29u1u8
	share internet to device enp0s29u1u8
    $0 on
	find device and share internet
    $0 off
	find device and stop sharing internet
    $0 -a 192.168.111.1 on
	find device and share internet only for network 192.168.111.1/24
    $0 -a 0 on
	find device and share internet only for network 192.168.0.1/24

Defailt networks: 192.168.0.1/24(Windows XP/Vista) 192.168.137.1/24(Windows 7/8)

Note:
    You have to switch on "USB Internet" option in your Android device before sharing internet
EOF
exit $1
}

function finddev()
{
DEVICE=$(ls /sys/class/net/e*u*/address | awk -F/ '{print $5}' | head -1)
[ -z "$DEVICE" ] && DEVICE=$(grep "^e.*u.*:[[:space:]]*[1-9]" /proc/net/dev | awk -F: '{print $1}' | head -1)
echo "$DEVICE"
}

function ineton()
{
DEVICE=$1
echo "Setting up network $NETWORKIP/24 for device $DEVICE"
NET=$(echo $NETWORKIP | sed s/[.][0-9]*$/.0/)
ifconfig $DEVICE 2>/dev/null | grep -q $NETWORKIP || ifconfig $DEVICE $NETWORKIP netmask 255.255.255.0 up
ip route show dev $DEVICE  2>/dev/null | grep -q $NET || ip route add $NET/24 $DEVICE
nmcli device set $DEVICE  managed no
echo "Setting up ip forwarding"
sysctl net.ipv4.ip_forward=1
echo "Setting up masquerading"
systemctl restart iptables
iptables -t nat -F
iptables -t nat -A POSTROUTING -j MASQUERADE
}

function inetoff()
{
DEVICE=$1
echo "Switching down ip forwarding"
sysctl net.ipv4.ip_forward=0
echo "Resetting iptables"
iptables -t nat -F
systemctl restart iptables
#echo "Resetting routes"
#NET=$(echo $NETWORKIP | sed s/[.][0-9]*$/.0/)
#ip route show dev $DEVICE  2>/dev/null | grep -q $NET || ip route del $NET/24
echo "Shutting down interface $DEVICE"
ifconfig $DEVICE down
echo "Switch off \"USB Internet\" option in your Android device"
}

[ -z "$1" -o "$1" = "--help" ] && help 0

if [ "$1" = "-a" ] ;then
   shift
   NETWORKIP=$1
   shift
   [ "$NETWORKIP" -gt "-1" -a "$NETWORKIP" -lt "256" ] 2>/dev/null && NETWORKIP=192.168.$NETWORKIP.1
fi

case "$1" in
   on)
     DEVICE=$2
     [ -z "$DEVICE" ] && DEVICE=$(finddev)
     [ -z "$DEVICE" ] && help 1
     ineton $DEVICE
     ;;
   off)
     DEVICE=$2
     [ -z "$DEVICE" ] && DEVICE=$(finddev)
     [ -z "$DEVICE" ] && help 1
     inetoff $DEVICE
     ;;
   *)
     help 1
     ;;
esac
