#!/bin/sh

PRIMUSLMOD=81-libs4primus.xzm
PRIMUSLPATH=http://magos.sibsau.ru/repository/modules/2014.64
PRIMUS32LIB=/usr/lib/libGL.so.1
PRDNL="wget -O "
USERMODSPATH=/mnt/livedata/MagOS-Data/modules
. /usr/lib/magos/os-config
. /etc/sound/profiles/current/profile.conf
. /etc/sysconfig/MagOS

# checking for standalone steam mode
if ! wmctrl -m | grep -qi name ;then

   # Clean up after GDM (GDM sets the number of desktops to one)
   xprop -root -remove _NET_NUMBER_OF_DESKTOPS -remove _NET_DESKTOP_NAMES -remove _NET_CURRENT_DESKTOP 2> /dev/null

   # Creating user directories
   if [ -z "$XDG_CONFIG_HOME" ]; then
	export XDG_CONFIG_HOME="$HOME/.config"
   fi
   if [ -e "$XDG_CONFIG_HOME/user-dirs.dirs" ]; then
	. "$XDG_CONFIG_HOME/user-dirs.dirs"
   else
   	XDG_DESKTOP_DIR="$HOME/Desktop"
   fi
   mkdir -p "$XDG_DESKTOP_DIR"

   #starting windows manager
   if [ -x /usr/bin/openbox-session ] ;then
      # Ensure the existance of openbox config file
      OPENBOX_CONF_DIR="$XDG_CONFIG_HOME/openbox"
      if [ ! -f "$OPENBOX_CONF_DIR/lxde-rc.xml" ]; then
	mkdir -p "$OPENBOX_CONF_DIR"
	cp /usr/share/lxde/openbox/rc.xml "$OPENBOX_CONF_DIR/lxde-rc.xml"
      fi
      # starting openbox
      /usr/bin/openbox-session &
   elif [ -x /usr/bin/kwin ] ;then
      # starting kwin
      /usr/bin/kwin &
   fi

   #Disabling dpms monitor function
   xset -dpms

   #Starting pulseaudio
   [ "$SOUNDPROFILE" = "pulse" ] && start-pulseaudio-x11 &

fi

# Checking for bumblebee
if systemctl status bumblebeed.service | grep -q "Loaded:[[:space:]]*loaded" ;then
   [ -x /usr/bin/primusrun ] && PRRUN=primusrun
   #Primus needs 32bit libs to work. Check for x64
   if [ "$(uname -i)" = "x86_64" ];then
      #Are 32bit libs installed?
      if ! [ -f "$PRIMUS32LIB" ] ;then
         #Downloading xzm module
         xterm -e "$PRDNL /tmp/$PRIMUSLMOD $PRIMUSLPATH/$PRIMUSLMOD || rm -f /tmp/$PRIMUSLMOD"
         if [ -f /tmp/$PRIMUSLMOD ] ;then
            #Installing xzm module
            MODCMD1="mv -f /tmp/$PRIMUSLMOD $USERMODSPATH/$PRIMUSLMOD ;"
            if [ -w $USERMODSPATH ] ;then
               "$MODCMD1"
               ROOTCMD=
            else
               ROOTCMD="$MODCMD1"
            fi
            #Activating module
            ROOTCMD="$ROOTCMD activate $USERMODSPATH/$PRIMUSLMOD"
            beesu -l "$ROOTCMD"
         fi
      fi
   fi
else
   PRRUN=
fi

# Start steam
exec $PRRUN /usr/bin/steam $@
