#!/bin/sh
# Unmount file for PuppyRus ("Ext2", "Ext3", "Ext4", "SquashFS", "ISO")
#VERSION 4.2
#help
HLP(){
echo "Usage: $0 <file>"
exit 1
}
case "$1" in
    "" | -h | --help)  HLP ;;
    *) if ! [ -f $1 ] ; then 
    echo "$1 - file not found "
    HLP  ; fi ;;
esac

[ -f "$1" ] && mntfile="$(realpath "$1")" || mntfile="$1"
mntpoint=/mnt/$(echo "${mntfile}" | tr ' ' '_' | sed "s#^\.##g" | sed "s#/#+#g")
status=0

if [ -d "${mntpoint}" ]; then
  sync
  busybox umount -d "${mntpoint}"
  status=$?
  rmdir "${mntpoint}" 2>/dev/null
  [ ${status} -gt 0 ] && echo "Unmount \"${mntfile}\" failed!"
  sync
else
  echo "$(basename "$0"): File \"${mntfile}\" is not mounted!"; status=1
fi

exit ${status}
