#!/bin/bash
#
# /usr/lib/magos/scripts/umountloop
#
# Description: Umount loop
# Author : Anton Goroshkin <http://magos-linux.ru>
# Last edited : Mikhail Zaripov <http://magos-linux.ru>

if [ "$1" == "" -o  "$2" != "" -o  "$1" == "--help" -o ! -d "$1" ] ;then
  echo Umount encrypted loopback file from directory
  echo Usage: $0 mounted_directory
  exit 0
fi

DNAME=$(readlink -f "$1")
MNAME=$(grep -m1 " $DNAME " /proc/mounts | cut -d " " -f 1)

umount "$DNAME"
cryptsetup close "$MNAME"
