#!/bin/bash
#
# /usr/lib/magos/scripts/urpm2xzm
#
# Description: create LZM/XZM from RPM (& dependences)
# Author : Anton Goroshkin <http://magos-linux.ru>
#
# $1=RPM file or name program

[ $(id -un) != "root" ] && exit

cat /proc/config.gz | gunzip | grep -q SQUASHFS_XZ && MODULEFORMAT=xzm || MODULEFORMAT=lzm

[ "$1" = "" ] && exit -1
# 
###########################################
urpme $@ > /dev/null 2>&1                 #
rpmdbreset --copy                         #
urpmi --test $@ || exit 2                 #
###########################################

export PATH=/usr/lib/magos/scripts:$PATH
. /usr/lib/magos/scripts/liblinuxlive

#############################
uird=yes                    #
. /etc/initvars || uird=no  #
#############################

###########################################################
mod_br=/mnt/live/memory/tmp/wiz_fly_mods                  #
[ "$uird" != "no" ] &&  mod_br=$SYSMNT/tmp/wiz_fly_mods   #
root_br=/mnt/live/memory/tmp/wiz_fly_rootfs               #
[ "$uird" != "no" ] && root_br=$SYSMNT/tmp/wiz_fly_rootfs #
mod_path=/mnt/live/memory/images                          #
[ "$uird" != "no" ] && mod_path=$SYSMNT/bundles           #
###########################################################

mount_br=$mod_br

rm -rf $mount_br $root_br
mkdir -p $mount_br $root_br

for a in `ls -d $mod_path/??-*`; do
    if [ $(cmdline_parameter unionfs) ];then
      mount_br="$mount_br:$a=ro"
    else
      mount_br="$mount_br:$a=rr"
    fi                                                                                                                                                                      
done                                                                                                                                                                        
                                                                                                                                                                            
if [ $(cmdline_parameter unionfs) ];then                                                                                                                                    
    mount -t unionfs -o dirs=$mount_br wiz_fly $root_br                                                                                                                     
else                                                                                                                                                                        
    mount -t aufs -o br:$mount_br wiz_fly $root_br                                                                                                                          
fi                                                                                                                                                                          
                                                                                                                                                                            
mkdir -p $root_br/{dev,proc,sys}                                                                                                                                            

for tm in {dev,proc,sys,var/lib/rpm}; do
    mount -o bind /$tm $root_br/$tm
done

mkdir -p $root_br/tmp
/usr/sbin/urpmi --root=$root_br $@

for tm in {var/lib/rpm,sys,proc,dev}; do
    while (grep -q $root_br/$tm /proc/mounts ) ; do
        umount $root_br/$tm
    done
done

while (grep -q wiz_fly /proc/mounts ) ; do
    umount wiz_fly
done

rm -rf $mod_br/var/lib/rpm
rm -rf $mod_br/tmp
rm -rf $mod_br/{dev,proc,sys}

###########################################################################################
ls -a $mod_br |grep  -q ^[[:alnum:]]*$  && dir2xzm $mod_br "$(basename $1).$MODULEFORMAT" #
###########################################################################################

rm -rf $mod_br
rm -rf $root_br

###########
urpme $@  #
###########
