#!/bin/bash
#
# /usr/lib/magos/scripts/urpm2xzm
#
# Description: create LZM/XZM from RPM (& dependences)
# Author : Anton Goroshkin <http://magos-linux.ru>
# Edited by Mikhail Zaripov <http://magos-linux.ru>

if [ "$1" == "" -o "$1" == "--help" -o $(id -un) != "root" ] ;then
  echo "urpm2xzm creates xzm module for rpm package and dependencies by using urpmi. This scripts needs root account."
  echo "Usage: $0 <rpm_package_name> [urpmi parameters]"
  echo "Module <rpm_package_name.xzm> will be created in current folder."
  exit 0
fi

export PATH=/usr/lib/magos/scripts:$PATH
MODULEFORMAT=xzm
URPMITMP=/tmp/urpm2xzm
mod_path=/mnt/live/memory/images
. /usr/lib/magos/functions

root_br="$URPMITMP/root"
mod_br="$URPMITMP/changes"
mod_file="$URPMITMP/urpm2xzm.img"
err=0
mount_mode="rr"
[ $(cmdline_parameter unionfs) ] && mount_mode="ro"

rm -rf "$mod_br" "$root_br" 2>/dev/null
mkdir -p "$mod_br" "$root_br"
SPACE=$(LC_ALL=C df -BM "$URPMITMP" --output=avail | tail -1 | tr -d M) # free space in folder
[ ! -z "$SPACE" ] && SPACE=$(echo "$SPACE""*80/100" | bc)        # 80% of free space in folder
[ ! -z "$SPACE" -a -z "$URPMISPACE" ] && URPMISPACE="$SPACE"M
[ -z "$URPMISPACE" ] && URPMISPACE=1024M
dd if=/dev/zero of="$mod_file" bs=1 count=0 seek="$URPMISPACE" && mkfs.ext2 "$mod_file"
mount -o loop "$mod_file" "$mod_br" || exit 1

mount_br="$mod_br=rw"
for a in `ls -d $mod_path/??-*`; do
    mount_br="$mount_br:$(readlink -f $a)=$mount_mode"
done

if [ $(cmdline_parameter unionfs) ];then
    mount -t unionfs -o dirs="$mount_br" unionfs "$root_br"
else
    mount -t aufs -o br:"$mount_br" aufs "$root_br"
fi

mkdir -p "$root_br"/{dev,proc,sys,tmp}
for tm in {dev,proc,sys}; do
    mount -o bind /$tm "$root_br"/$tm
done

/usr/sbin/urpmi.update -a --urpmi-root=$root_br
/usr/sbin/urpmi --root="$root_br" $@
[ $? != 0 ] && err=1 && echo "urpmi error !"
[ ! -f "$mod_br/var/lib/rpm/Packages" ] && err=1 # nothing was installed

echo "Unmounting filesystems..."
grep "$root_br"/ /proc/mounts | awk '{ print $2}' | sort -r | while read tm ;do
      umount "$tm"
done
umount "$root_br"

rm -rf "$mod_br/tmp" "$mod_br/var/tmp" "$mod_br"/var/cache/{urpmi,ldconfig} "$mod_br"/etc/{urpmi,ld.so.cache} "$mod_br"/var/lib/{rpm,menu,urpmi} "$mod_br/usr/share/applications/mimeinfo.cache" "$mod_br"/.wh* 2>/dev/null
find "$mod_br/usr/share/icons" -type f -name icon-theme.cache 2>/dev/null | xargs rm -f 
rmdir "$mod_br"/{dev,proc,sys,lost+found} "$mod_br/var/cache" "$mod_br/var/lib" "$mod_br/var" "$mod_br/etc" 2>/dev/null

if [ "x$err" != "x1" ]; then
   echo Creating module "$(basename $1).$MODULEFORMAT"
   dir2xzm "$mod_br" "$(basename $1).$MODULEFORMAT"
fi

umount "$mod_br"
rm -f "$mod_file"
rmdir "$mod_br" "$root_br" 
[ -h "$URPMITMP" ] || rmdir "$URPMITMP"

