#!/bin/sh
#
# UIRD Init script
# Author: Anton Goroshkin <http://magos-linux.ru>
#

. /livekitlib
#. /lib/magos-lib.sh

#transfer_initramfs

UNION=$NEWROOT

MEMORY=/memory
CHANGES=$MEMORY/changes
CACHE=$MEMORY/cache
DATAMNT=$MEMORY/data
BUNDLES=$MEMORY/bundles
COPY2RAM=$MEMORY/copy2ram
COPY2REP=$MEMORY/copy2rep

LIVEKITNAME="MagOS"
BEXT=xzm

echo "0" >/proc/sys/kernel/printk

header "Starting UIRD init <http://magos-linux.ru/>"

mkdir -p $MEMORY
mount -t tmpfs -o size="100%" tmpfs $MEMORY

debug_start
                                                                                                                                                      debug_shell
init_aufs

# find data dir with filesystem bundles
DATA="$(find_data 60 "$DATAMNT")"
                                                                                                                                                      debug_shell
# setup persistent changes, if possible
persistent_changes "$DATA" "$CHANGES"
                                                                                                                                                      debug_shell
# copy to LOCAL_REPOSITORY if needed
DATA_REP="$(copy_to_rep "$DATA" "$COPY2REP")"
                                                                                                                                                      debug_shell
# copy to RAM if needed
DATA_RAM="$(copy_to_ram "$DATA" "$COPY2RAM")"
                                                                                                                                                      debug_shell
# init aufs union
init_union "$CHANGES" "$UNION"
                                                                                                                                                      debug_shell
# add data to union
for d_dirs in "/$DATA_RAM" "/$DATA_REP" "/$DATA" ;do
    union_append_bundles $d_dirs "$BUNDLES" "$UNION"
done
                                                                                                                                                      debug_shell

# rootcopy
#copy_rootcopy_content "$DATA" "$UNION"

# create empty fstab
#fstab_create "$UNION"
                                                                                                                                                      debug_shell
#header "Live Kit done, starting $LIVEKITNAME"
#change_root "$UNION"

#header "!!ERROR occured, you shouldn't be here.!!"
#/bin/sh

#need for usable_root of dracut
mkdir -p $UNION/proc $UNION/sys $UNION/dev $UNION/$MEMORY

#need TODO
mount -o bind $MEMORY $UNION/$MEMORY

header "UIRD init done, starting $LIVEKITNAME"

