.TH pfs-utils 8  "март, 2017" "версия 3.*" "PFS-UTILS"
.SH НАЗВАНИЕ
pfs-utils \- комплект скриптов для управления squashfs модулями для linux live дистрибутивов 
.SH ОБЗОР
Коллекция скиптов для создания, слияния, разборки, подключения и отключения модулей PFS
.TP
\- mkpfs \- создание и слияние модулей
.TP
\- pfsextraxt \- распаковка модулей, разборка составных модулей, распаковка в систему (установка) 
.TP
\- pfsload \- подключение модулей (каталогов, образов) в корневую aufs
.TP
\- pfsunload \- отключение от корневой aufs модулей, подключенных pfsload 
.TP
\- pfsuninstall \- пофайловое удаление из системы установленного с pfsextract -i
.TP
\- pfsrebuild \- пересборка установленных и подключенных пакетов
.TP
\- sync2layer \- утилита создает новый слой и перемещает в него файлы из changes, освобождая tmpfs
.TP
\- pfsinfo \- список пакетов в составном модуле PFS
.TP
\- pfs \- библиотека функций для pfs-utils скриптов  
.SH КОД ЗАВЕРШЕНИЯ
все утилиты возвращают "0" при удачном завершении.
.SH АВТОР
команда forum.puppyrus.org  (sfs, zay, DdShuruck)
.SH ЕЩЕ
mksquashfs(1)
