#!/bin/sh
#---------------------------------------------------------------
# Project         : Mandrake
# Module          : numlock
# File            : numlock.xinit
# Version         : $Id: numlock.xinit 241829 2008-04-03 04:15:25Z blino $
# Author          : Frederic Lepied
# Created On      : Wed Apr 12 08:39:24 2000
#---------------------------------------------------------------

#
#  The following code used to execute enable_numlock if numlock was enabled
#  on this host.  This screwed hosts which did not use numlock (laptops)
#  but which tried to create XDMCP sessions to this host, as numlock would
#  be turned on unconditionally.
#
#  The following code detects a $DISPLAY host other than what would be
#  expected for a local X session on this host, and exempts it from the
#  automatic execution of numlock.
#

[ -f /etc/sysconfig/MagOS ] && . /etc/sysconfig/MagOS

DISPHOST=${DISPLAY%%:*}
if  [ "$DISPHOST" = "" -o "$DISPHOST" = "localhost" -o "$DISPHOST" = "$HOSTNAME" ]; then
  /usr/bin/enable_X11_numlock off
  if [ -f /var/lock/subsys/numlock -a  -x /usr/bin/enable_X11_numlock -a "$NUMLOCK" != "no" ]; then
      /usr/bin/enable_X11_numlock
  fi
fi

# numlock ends here
