#!/bin/sh
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

FUSIONICONTIMEOUT=5
FUSIONICONDEDIS=gnome-shell,gnome,i3term
. /etc/sysconfig/compositing-wm
. /usr/lib/magos/functions
. /usr/lib/magos/os-config
. /etc/MagOS/config

DE=$(detectDE)

if [ "$COMPOSITING_WM_START" = "yes" -a "$COMPOSITING_WM" = "compiz-fusion" ] ;then
   if ! echo " $FUSIONICONDEDIS " | tr ',;' " " | grep -q " $DE " ;then
     sleep $FUSIONICONTIMEOUT
     fusion-icon -f &
   fi
fi
