#!/bin/bash
#
# magosctl      Helper script for MagOS Linux Live.
#
# Authors:	Mikhail Zaripov <m3for@mail.ru>
#
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

[ -f /etc/MagOS/config ] && . /etc/MagOS/config
[ "$RUNLDCONFIG" != "yes" -a "$RUNLDCONFIG" != "no"  ] && bash -c "sleep 30 && sudo /sbin/ldconfig" &
