#!/bin/bash
# Description: This script ask user for update system
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0


function dialogreboot()
{
 MSG01=$(gettext -s "MagOS update is over")
 MSG02=$(gettext -s "MagOS updated. Please reboot computer.")
 MSG03=$(gettext -s "Reboot now")
 MSG04=$(gettext -s "No, i will reboot later")
 CHOICE=$(Xdialog --title "$MSG01" --radiolist "$MSG02" 0 0 3 "1" "$MSG03" on "2" "$MSG04" off 2>&1 | tail -1)
 [ "$CHOICE" = "1" ] || exit 0
 systemctl reboot
 reboot
}

function dialogerror()
{
 MSG01=$(gettext -s "Update was unsuccessful.")
 cat $LOGFILEROOT >> $LOGFILE 2>/dev/null
 Xdialog --title "$MSG01" --no-cancel --textbox $LOGFILE 0 0
}

# $1 text string
function dialogupdate()
{
 MSG01=$(gettext -s "Please select")
 MSG02=$(gettext -s "$1")
 MSG03=$(gettext -s "Do you want to update it now?")
 MSG04=$(gettext -s "Yes, right now")
 MSG05=$(gettext -s "No, later")
 MSG06=$(gettext -s "Never, don't ask me again")
 CHOICE=$(Xdialog --title "$MSG01" --radiolist "$MSG02\n$MSG03" 0 0 4 "1" "$MSG04" on "2" "$MSG05" off "3" "$MSG06" off 2>&1 | tail -1)
 if [ "$CHOICE" = "3" ] ;then
    touch $MAGOSPATH/.dontupdatemagos 2>/dev/null || touch $HOME/.config/.dontupdatemagos
 fi
 [ "$CHOICE" = "1" ] && return 0
 return 1
}

export TEXTDOMAINDIR=/usr/share/locale
export TEXTDOMAIN=magos_functions
echo $PATH | grep -q /usr/lib/magos/scripts || PATH=/usr/lib/magos/scripts:$PATH
. /usr/lib/magos/functions
. /usr/lib/magos/os-config
. /etc/MagOS/config
DEBUGMODE=no
debug_mode "$0" "$@"
LOGFILE=/tmp/magosupdate-$UID.log
LOGFILEROOT=/tmp/magosupdate-0.log
MAGOSPATH=/mnt/livemedia/MagOS
[ -f /mnt/live/etc/modules ] && . /mnt/live/etc/modules
[ ! -z "$MAGOSMODS" -a -d "$MAGOSMODS/base" ] && MAGOSPATH="$MAGOSMODS"
[ -f "$MAGOSPATH/vmlinuz" -a -d "$MAGOSPATH/base" ] || exit 1

#check for readonly filesystem
magosupdate --checkdir || exit 1

#check if update is disabled or auto
echo $MAGOSUPDATE | grep -qi ^ask$ || exit 0
[ -f $MAGOSPATH/.dontupdatemagos -o -f $HOME/.config/.dontupdatemagos ] && exit 0

#check for server connection
magosupdate --checkserver || exit 1

#check for updates
if   magosupdate --checknewversion ;then
    if dialogupdate "New version of MagOS Linux is detected on server."  ;then
	magosupdate --updateversion || dialogerror
	grep -qi "please reboot" $LOGFILE $LOGFILEROOT 2>/dev/null && dialogreboot
    fi
elif magosupdate --checkupdates    ;then
    if dialogupdate "New updates for MagOS Linux are detected on server." ;then
	magosupdate --updatebase || dialogerror
	grep -qi "please reboot" $LOGFILE $LOGFILEROOT 2>/dev/null && dialogreboot
    fi
fi
