#!/bin/bash
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

SNLIBS=/opt/secretnet/lib
[ -d "$SNLIBS" ] || exit 0
getent group snlogger || addgroup snlogger
getent group snadmin  || addgroup snadmin
ldconfig $SNLIBS
systemctl is-active sn >/dev/null || systemctl restart sn
export PATH=/usr/lib/magos/scripts:/opt/secretnet/sbin:/opt/secretnet/bin:/sbin:/usr/sbin:/bin:/usr/bin:/usr/X11R6/bin:/usr/local/bin:/usr/local/sbin:/usr/lib/qt4/bin
/opt/secretnet/bin/snaidectl -i
/opt/secretnet/sbin/snunblock
