#!/bin/bash
#
# ifup-post-local       Helper script for MagOS Linux Live.
#
# Authors:	        Mikhail Zaripov <m3for@mail.ru>

[ -f /etc/sysconfig/MagOS ] && . /etc/sysconfig/MagOS

# mount MagOS-Server
if [ "$AUTOMOUNTSERVER" = "yes" ];then
    for a in $(showmount --exports --no-headers MagOS-Server | awk '{ print $1}' | grep /media) ;do
        MOUNTDEST=$(echo $a | sed s-/media-/mnt/server-)
        mkdir -p $MOUNTDEST 2>/dev/null
        [ -d "$MOUNTDEST" ] || continue
        grep -q " $MOUNTDEST " /etc/fstab || echo "MagOS-Server:$a $MOUNTDEST nfs nolock,users,auto 0 0 #AUTOMOUNTSERVER=yes" >> /etc/fstab
        grep -q " $MOUNTDEST " /proc/mounts ||  mount $MOUNTDEST 2>/dev/null &
    done
fi

exit 0
