#!/bin/sh
[ -f /var/lock/subsys/pdnsd ] || exit 0
cat /var/run/resolvconf/interface/* 2>/dev/null | grep nameserver > /var/cache/pdnsd/pdnsd.servers.down
if grep -q nameserver /var/cache/pdnsd/pdnsd.servers.down ;then
   mv -f /var/cache/pdnsd/pdnsd.servers.down /var/cache/pdnsd/pdnsd.servers
   /etc/rc.d/init.d/pdnsd reload >/dev/null 2>&1
else
   rm -f /var/cache/pdnsd/pdnsd.servers.down
fi
true