#!/bin/sh
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

. /usr/lib/magos/functions
. /etc/sysconfig/MagOS

DE=$(detectDE)
cd $HOME

echo "$AUTOEXEC" | tr ',;' \\n | while read a ;do
     NEEDDE=$(echo $a | grep : | awk -F: '{print $1}' | tr A-Z a-z)
     PROGRAM=${a/*:/}
     [ "$NEEDDE" -a "$NEEDDE" != "$DE" ] && continue
     [ -z "$PROGRAM" ] || "$PROGRAM" &
done

