# Mozilla User Preferences
user_pref("app.update.auto", false);
user_pref("browser.migration.version", 1);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.preferences.advanced.selectedTabIndex", 2);
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.search.order.1", "Ask.com");
user_pref("browser.search.order.2", "Exalead");
user_pref("browser.search.order.3", "Google");
user_pref("browser.search.order.4", "Yahoo");
user_pref("browser.search.selectedEngine", "Google");
user_pref("browser.search.update", false);
user_pref("browser.sessionstore.resume_session_once", true);
user_pref("browser.startup.homepage", "http://www.magos-linux.ru");
user_pref("browser.safebrowsing.enable", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("intl.charsetmenu.browser.cache", "KOI8-R, windows-1251, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("privacy.clearOnShutdown.offlineApps", true);
user_pref("privacy.clearOnShutdown.passwords", true);
user_pref("privacy.clearOnShutdown.siteSettings", true);
user_pref("privacy.item.cookies", true);
user_pref("privacy.item.offlineApps", true);
user_pref("privacy.sanitize.didShutdownSanitize", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.sanitizeOnShutdown", true);
user_pref("spellchecker.dictionary", "ru");
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.autoDisableScopes",0);
user_pref("startup.homepage_welcome_url","");
user_pref("datareporting.healthreport.uploadEnabled", false);
