#!/bin/bash
#
# Helper script for MagOS Linux Live.
#
# Authors:	Mikhail Zaripov <m3for@mail.ru>
#

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

SYSTEMCTL_NO_BLOCK=1 /usr/share/harddrake/service_harddrake 2>/dev/null
