#!/bin/sh
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

if [ ! -f $HOME/.config/Trolltech.conf ] ;then
   [ -f /usr/share/lxqt/themes/Default/Trolltech.conf ] && cp /usr/share/lxqt/themes/Default/Trolltech.conf $HOME/.config/Trolltech.conf
fi
