#!/bin/bash
#
# magosctl      Helper script for MagOS Linux Live.
#
# Authors:	Mikhail Zaripov <m3for@mail.ru>
#

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0
DEBUGMODE=no
. /usr/lib/magos/scripts/liblinuxlive
[ "$DEBUGMODE" = "yes" ] && debug_mode "$0" "$@"

[ -d /mnt/livemedia/MagOS-Data -a ! -d /mnt/livedata ] && ln -sf livemedia /mnt/livedata
