#!/bin/bash
#
# ifup-pre-local        Helper script for MagOS Linux Live.
#                       Used for autodetecting Wifi network
# Authors:	        Mikhail Zaripov <m3for@mail.ru>

[ -f /etc/MagOS/config ] && . /etc/MagOS/config

# Wifi detection
[ -f /etc/sysconfig/network-scripts/$1 ] || exit 0
. /etc/sysconfig/network-scripts/$1
if [ "$1" = "ifcfg-wlan0" -a "$WIRELESS_ESSID" = "" ] ;then
    ifconfig wlan0 up
    WIRELESS_ESSID=$(iwlist wlan0 scan 2>/dev/null | grep -m 1 ESSID: |  awk -F "\"" '{ print $2 }')
    ifconfig wlan0 down
    [ "$WIRELESS_ESSID" = "" ] || sed -i s/'^WIRELESS_ESSID=.*$'/WIRELESS_ESSID=$WIRELESS_ESSID/ /etc/sysconfig/network-scripts/$1
fi

if ! [ -z "$MACCHANGE" ] ;then
   IF=$(echo $1 | sed s/ifcfg-// )
   [ -z "$MACCHANGEROPTIONS" ] && MACCHANGEROPTIONS="-e"
   echo " $MACCHANGE " | tr ",;" " " | grep -q " $IF " && macchanger $MACCHANGEROPTIONS $IF
fi

exit 0
