#!/bin/bash
echo 3_makekernel
./3_makekernel >3.log 2>&1
echo 4_addkernel
./4_addkernel >4.log 2>&1
echo 5_checkdeps
./5_checkdeps >5.log 2>&1
echo 6_makedistro
./6_makedistro >6.log 2>&1
echo 7_split_rootfs
./7_split_rootfs >7.log 2>&1
echo 8_makeflash
./8_makeflash >8.log 2>&1
