#!/bin/bash
# скрипт запущенный в loaded/MagOS-2011 создаёт папку test куда складирует все rpm по папкам-модулям
# удобно для определения больших пакетов
rm -fr test
for a in ../../files/rpm_names/MagOS-2011/??-* ;do
   NM=$(echo ${a##.*/})
   echo $NM
   mkdir -p test/$NM
   for b in `cat $a` ;do
       cp -H rpms/$b[0-9][-0-9._a-zA-Z]*.rpm test/$NM
   done
done
