#!/bin/bash
# скрипт создаёт папку tmp/packages4mod куда складирует все папкам по папкам-модулям
# удобно для определения больших пакетов
TMPF=/tmp/packages4mod
. .config || exit 1
CACHE=cache/$FLASHNAME-$VERREL

rm -fr "$TMPF"
for a in $CACHE/modules/packages/??-* ;do
   echo $(basename $a)
   mkdir -p $TMPF/$(basename $a)
   cat $a | while read b ;do
       cp -H $CACHE/store/$b $TMPF/$(basename $a) || exit 1
   done
done
