#!/bin/bash
# преоброазует список файлов с полного имени dkms-lzma-4.43-27mdv2009.1.i586.rpm до названия пакета dkms-lzma-
ls -1 | awk -F- '{ for (i=1 ; i < ( NF - 1 ) ; i++) {  printf $i "-" }  print "" }' 
