#!/bin/bash
# MagOS project
# Authors: Alexandr Betсher
# Authors: Mikhail Zaripov
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0
DEBUGMODE=no
. /usr/lib/magos/scripts/liblinuxlive
. /usr/lib/magos/os-config
debug_mode "$0" "$@"

WALLPAPERSRES=1920x1080
WPDEFDIR=/mnt/livedata/MagOS-Data/backgrounds/wallpapers/Default
SSDEFDIR=/mnt/livedata/MagOS-Data/backgrounds/screensaver/Default
WPSYSDIR=/usr/share/magos/wallpapers/Default
SSSYSDIR=/usr/share/magos/screensaver/Default
WPDEFFILE=/usr/share/magos/wallpapers/default.jpg
[ -f /etc/sysconfig/theme ] && . /etc/sysconfig/theme
[ -f /etc/sysconfig/MagOS ] && . /etc/sysconfig/MagOS

# setting screensaver theme
[ -z "$SSAVERTHEME" ] && SSAVERTHEME="$SSDEFDIR"
[ ! -d "$SSAVERTHEME" -a -d "$BACKGROUND" ] && SSAVERTHEME="$BACKGROUND"
[ ! -d "$SSAVERTHEME" -a -d "$WPDEFDIR" ] && SSAVERTHEME="$WPDEFDIR"
[ ! -d "$SSAVERTHEME" ] && SSAVERTHEME="$WPSYSDIR"
rm -f "$SSSYSDIR"
ln -sf "$SSAVERTHEME" "$SSSYSDIR"

# selecting file for default wallpaper
[ -z "$BACKGROUND" ] && BACKGROUND="$WPDEFDIR"
[ -r "$BACKGROUND" ] || BACKGROUND="$WPSYSDIR"
[ -d "$BACKGROUND" ] && BACKGROUND=$(find -L "$BACKGROUND" | egrep -i "[.]jpeg$|[.]jpg$" | sort -R | head -1)
[ -f "$BACKGROUND" ] || exit 0
rm -f "$WPDEFFILE"
cp -Lp "$BACKGROUND" "$WPDEFFILE"

[ -x /usr/bin/convert ] || exit 0

# detecting monitor resolution
[ "$(cmdline_value xres)" ] && XORG_RES=$(cmdline_value xres)
[ -z "$XORG_RES" -o "$XORG_RES" = "auto" ] && XORG_RES=$(monitor-edid | awk '/ModeLine/ { print $2 }' | sed -e 's/"//g' -e '2,$d')
[ -z "$XORG_RES" ] && XORG_RES=$(find -L /sys/class/drm/card0 -maxdepth 2 -name modes 2>/dev/null -exec cat '{}' \; | sort -t x -n -k 2 | tail -1)
echo "$XORG_RES" | grep -q ^[0-9]*x[0-9]*$ || XORG_RES=$WALLPAPERSRES

# resizing wallpaper for monitor resolution (default is proportional on black bacground)
RESIZEOPT="-resize $XORG_RES -background black -gravity center -extent $XORG_RES"
[ "$BACKGROUNDMODE" = "1" ] && RESIZEOPT="-resize $XORG_RES!"
[ "$BACKGROUNDMODE" = "2" ] && RESIZEOPT="-resize $XORG_RES^ -gravity center -extent $XORG_RES"
convert $RESIZEOPT "$WPDEFFILE" /tmp/background.jpg

# Graffiti effects
if [ "$GRAFFITI" = "yes" ] ;then
   [ "$(cmdline_value changes)$(cmdline_value uird.changes)" ] && LABEL=magos.png || LABEL=clean.png
   convert -resize x$(expr $(echo $XORG_RES | awk -Fx '{ print $2 }') / 10) /usr/share/magos/graffiti/$LABEL /tmp/logo.png
   composite -gravity SouthWest  /tmp/logo.png /tmp/background.jpg /tmp/background2.jpg
   mv -f /tmp/background2.jpg /tmp/background.jpg
   rm -f /tmp/logo.png
fi

# placing warning about default passwords
if [ "$GRAFFITI" != "no" -a -x /usr/bin/composite ] ;then
   A=0
   grep -q "^root:$DEFAULTROOTPASSWD:" /etc/shadow && A=1
   grep -q "^user:$DEFAULTPASSWD:" /etc/shadow && A=1
   [ "$A" = "1" ] && composite -gravity NorthWest /usr/share/magos/graffiti/warning.png /tmp/background.jpg /tmp/background2.jpg
   [ -f /tmp/background2.jpg  ] && mv -f /tmp/background2.jpg /tmp/background.jpg
#   disabled slow method
#   convert $DEFAULTDIR/default.jpg  -gravity NorthWest -stroke '#000C' -strokewidth 1 -annotate 0 ' Warning: passwords are default - user:magos, root:toor ' -stroke  none  -fill red  -annotate 0 ' Warning: passwords are default - user:magos, root:toor ' $DEFAULTDIR/default.jpg
fi

# replacing default wallpaper
[ -f /tmp/background.jpg  ] && mv -f /tmp/background.jpg "$WPDEFFILE"

# making ksplash background
if [ -d usr/share/apps/ksplash ] ;then
   mkdir -p "/usr/share/apps/ksplash/Themes/Default/$XORG_RES"
   convert "$WPDEFFILE" "/usr/share/apps/ksplash/Themes/Default/$XORG_RES/background.png"
fi
