#!/bin/bash
# MagOS project
# Authors: Alexandr Betсher
# Authors: Mikhail Zaripov
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0
DEBUGMODE=no
. /usr/lib/magos/functions
. /usr/lib/magos/os-config
debug_mode "$0" "$@"
[ -f /etc/MagOS/theme ] && . /etc/MagOS/theme
[ -f /etc/MagOS/config ] && . /etc/MagOS/config

# setting screensaver theme
[ -z "$SSAVERTHEME" ] && SSAVERTHEME="$SSDEFDIR"
[ ! -d "$SSAVERTHEME" -a -d "$BACKGROUND" ] && SSAVERTHEME="$BACKGROUND"
[ ! -d "$SSAVERTHEME" -a -d "$WPDEFDIR" ] && SSAVERTHEME="$WPDEFDIR"
[ ! -d "$SSAVERTHEME" ] && SSAVERTHEME="$WPSYSDIR"
rm -f "$SSSYSDIR"
ln -sf "$SSAVERTHEME" "$SSSYSDIR"

# selecting file for default wallpaper
[ -z "$BACKGROUND" ] && BACKGROUND="$WPDEFDIR"
[ -r "$BACKGROUND" ] || BACKGROUND="$WPSYSDIR"
[ -d "$BACKGROUND" ] && BACKGROUND=$(find -L "$BACKGROUND" | grep -iE "[.]jpeg$|[.]jpg$" | sort -R | head -1)
[ -f "$BACKGROUND" ] || exit 0
rm -f "$WPDEFFILE"
cp -Lpf "$BACKGROUND" "$WPDEFFILE"
cp -pf "$WPDEFFILE" $(dirname "$WPDEFFILE")/default.orig.jpg
