#!/bin/bash
#
# magosctl      Helper script for MagOS Linux Live.
#
# Authors:	Mikhail Zaripov <m3for@mail.ru>
#
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0
DEBUGMODE=no
. /usr/lib/magos/scripts/liblinuxlive
debug_mode "$0" "$@"

[ -f /etc/sysconfig/MagOS ] && . /etc/sysconfig/MagOS
[ "$RUNLDCONFIG" = "yes" ] && /sbin/ldconfig
