#!/bin/bash
#
# magosctl      Helper script for MagOS Linux Live.
#
# Authors:	Mikhail Zaripov <m3for@mail.ru>
#
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0
DEBUGMODE=no
. /usr/lib/magos/functions
debug_mode "$0" "$@"

[ -f /etc/MagOS/config ] && . /etc/MagOS/config
[ "$RUNLDCONFIG" != "no" ] && /sbin/ldconfig &
