#!/bin/bash
#
# magosctl      Helper script for MagOS Linux Live.
#
# Authors:	Mikhail Zaripov <m3for@mail.ru>
#
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0
DEBUGMODE=no
. /usr/lib/magos/functions
. /usr/lib/magos/os-config
debug_mode "$0" "$@"
. /etc/MagOS/config

if readlink -f /etc/systemd/system/default.target 2>/dev/null | grep -q multi-user.target ;then
   kill -RTMIN+21 1 || busybox kill -RTMIN+21 1
   grep -q plymouth.enable=1 /proc/cmdline && /bin/plymouth --wait quit
   sleep 2
   [ -x /lib/systemd/systemd-vconsole-setup ] && /lib/systemd/systemd-vconsole-setup
   kill -RTMIN+21 1 || busybox kill -RTMIN+21 1
   chvt 2
fi
