#!/bin/bash
# Description: This script will generate initial passwords for samba users
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

DEBUGMODE=no
. /usr/lib/magos/scripts/liblinuxlive
debug_mode "$0" "$@"

MAGOSPATH=/mnt/livemedia/MagOS
[ -f /mnt/live/etc/modules ] && . /mnt/live/etc/modules
[ ! -z "$MAGOSMODS" -a -d "$MAGOSMODS/base" ] && MAGOSPATH="$MAGOSMODS"
[ -f /etc/sysconfig/MagOS ] && . /etc/sysconfig/MagOS

echo $MAGOSUPDATE | grep -qi ^auto$ || exit 0

/usr/lib/magos/scripts/magosupdate >>$MAGOSPATH/update.log 2>&1

exit 0