#!/bin/bash
# Initial script for MagOS-Linux Live operating system
# This script are launching before starting init from linux-live script.
# Current dir allways must be set to root (/)
# All system path must be relative, except initrd dirs

[ -z "$PATHINI" ] && PATHINI=/tmp/MagOS.ini.gz
[ -f "$PATHINI" ] || exit 0

# MagOS.ini processing
FNAME=etc/sysconfig/MagOS
touch $FNAME
gunzip -c "$PATHINI" | egrep '^DEFAULTPASSWD|^DEFAULTROOTPASSWD|^NEEDEDUSERS' > /tmp/.credential
gunzip -c "$PATHINI" | egrep -v '^DEFAULTPASSWD|^DEFAULTROOTPASSWD|^NEEDEDUSERS'| while read a ;do
   echo $a | egrep -q '^[:space:]*#|^[:space:]*$' && continue
   if echo $a | grep -q "^\[.*\][:space:]*" ;then
      FNAME=`echo "$a" | tr -d '[ ]' | sed s-^/--`
   else
      nv=`echo $a | awk -F= '{print $1}'`
      [ "$nv" = "" ] && continue
      if ! grep -q "^[[:space:]]*$nv=" $FNAME 2>/dev/null ;then
         grep -q "^$a$" $FNAME 2>/dev/null || echo "$a" >>$FNAME
      else
         sed -i 's|'"^[[:space:]]*$nv=.*$"'|'"$a"'|' $FNAME
      fi
   fi
done

