#!/bin/bash
# Initial script for MagOS-Linux Live operating system
# This script are launching before starting init from linux-live script.
# Current dir allways must be set to root (/)
# All system path must be relative, except initrd dirs

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

. etc/sysconfig/MagOS
. usr/lib/magos/functions

echolog "setting up modules repository"
REPOSITORY=$(cmdline_value repository)

if [ "$REPOSITORY" ]; then
   if [ "$(echo $REPOSITORY | grep "://")" != ""  ]; then
      init_dhcp $(modprobe_network_modules)
       mkdir -p $LIVEREPOSITORY
      echo $REPOSITORY | grep -iq ^"http://" && mount_httpfs $REPOSITORY $LIVEREPOSITORY
      echo $REPOSITORY | grep -iq ^"ftp://" && mount_curlftpfs $REPOSITORY $LIVEREPOSITORY
      echo $REPOSITORY | grep -iq ^"ssh://" && mount_sshfs $REPOSITORY $LIVEREPOSITORY
      echo $REPOSITORY | grep -iq ^"nfs://" && mount_nfs $REPOSITORY $LIVEREPOSITORY
   else
   REPOSITORYMNT=$(find_in_computer $REPOSITORY $LIVEREPOSITORY)
   mount_device $REPOSITORYMNT $LIVEREPOSITORY
   echolog $REPOSITORYMNT
   fi
else
   REPOSITORYMNT=$DATAMNT
   LIVEREPOSITORY=$DATAMNT
fi

#debug_shell
