#!/bin/bash
MOUNTHOTPLUG=yes
HOTPLUGMOUNTOPTIONS="-u 0 --dmask 0 --fmask 0111 -s"
. /etc/sysconfig/MagOS
[ "$MOUNTHOTPLUG" != "yes" ] && exit 0
MOUNTUSER=`grep users: /etc/group | awk -F: '{print $4}' | awk -F, '{ print $1}'`
[ $MOUNTRUSER = "" ] && MOUNTUSER=root
DEVICE=$1
shift
if [ -b "$DEVICE" ] ;then
   su -l $MOUNTUSER -c "pmount-hal $DEVICE $HOTPLUGMOUNTOPTIONS $@"
else
   echo Usage: pmount-hal-user <device> [parameters]
fi
