#!/bin/bash
#
# /usr/lib/magos/sbin/conv4mod
#
# Description: Convert modules 
# Author : Anton Goroshkin <http://magos-linux.ru>


if [ "$(id -un)" != "root" ] ;then
   gksu -g "/bin/bash '$0' $@"
   exit 0
fi

PATH=.:$(dirname $0):/usr/lib/magos/sbin:$PATH

mod_dir=/mnt/live/memory/images

mdialog --msgbox "Выберите директорию для сохранения модулей"
dir_name=$(mdialog --getexistingdirectory /mnt/livemedia/ )
format=$(mdialog --menu Формат_модулей lzm LZM nolzm LZM_nocompression)
dir2mod $format $mod_dir $dir_name ??-

