#!/bin/bash
#
# /usr/sbin/mdialog
#
# Helper Library for scripts
#
# Author: Alexandr Betkher <http://magos-linux.ru>
# Author: Anton Goroshkin <http://magos-linux.ru>
#

if [ -z $DISPLAY ]
then
        DIALOG=dialog
    else
        DIALOG=Xdialog
fi

HELP () {
echo  "Скрипт $0, автоматически использует для создания графического интерфеса"

echo  "--yesno <text>            Вопросительный диалог с кнопками да/нет"
exit
}

cmd=$1
if [ "$cmd" = "" ]; then
    cmd="-h" 
fi

case $cmd in
-h | --help )
HELP ;;

* )
shift 
$DIALOG --stdout --title "" $cmd "$@" 0 0
;;

esac