#!/bin/bash

# /usr/lib/magos/sbin/dir2mod
#
# Description: Convert DIRs to Modules 
# Author : Anton Goroshkin <http://magos-linux.ru>



#convert DIRs to LZMs
# $1 = directory images
# $2 = directory of LZMs
# $3 = mask of dirname (ex. - "??-" )
convert_dir2lzm()
{
echo "Converting DIRs to LZMs:"
for a in `ls -d $1/$3*`; do
    mn=$(basename $a)
    echo -ne \\n"	converting $mn --> $mn.lzm "\\n
    mkdir -p $2/lzm
    fd=$2/lzm/$mn.lzm

    dir2lzm $a $fd
done
}


#convert DIRs to LZMs nolzma
# $1 = directory images
# $2 = directory of LZMs
# $3 = mask of dirname (ex. - "??-" )
convert_dir2nolzm()
{
echo "Converting DIRs to LZMs nocompression:"
for a in `ls -d $1/$3*`; do
    mn=$(basename $a)
    echo -ne \\n"	converting $mn --> $mn.lzm (no compression)"\\n
    mkdir -p $2/nolzm
    fd=$2/nolzm/$mn.lzm

    dir2nolzm $a $fd
done
}

#convert DIRs to ROMs 
# $1 = directory images
# $2 = directory of ROMs
# $3 = mask of dirname (ex. - "??-" )
convert_dir2rom()
{
echo "Converting DIRs to ROMs:"
for a in `ls -d $1/$3*`; do
    mn=$(basename $a)
    echo "	converting $mn --> $mn.rom"
    st=`du -s -m $a ` 
    size_mod=${st%%$a}
    size_mod=$[$size_mod+100]
    mkdir -p $2/roms $2/roms/$mn
    dd if=/dev/zero of=$2/roms/$mn.rom bs=1M count=0 seek=$size_mod 2>/dev/null
    echo y | mkfs.ext3 -q $2/roms/$mn.rom >/dev/null
    echo "virtual size: [$size_mod"."M]"
    mount -o loop $2/roms/$mn.rom $2/roms/$mn
    cp -a $a/* $2/roms/$mn 2>/dev/null
    umount $2/roms/$mn
    rm -rf $2/roms/$mn

done

}

HELP()
{
   echo
   echo "#####################################"
   echo "Convert directory tree into modules" 
   echo
   echo -ne "Usage:\\n	$0 lzm|nolzm|rom source_directory destination_directory mask \\n"
   echo -ne "Example:\\n	./dir2mod nolzm /mnt/live/memory/images /mnt/livemedia/MagOS/modules/ ??- \\n"
   echo
   echo "#####################################"   
   echo
}

PATH=.:$(dirname $0):/usr/lib:$PATH
. liblinuxlive || exit 1


case $1 in
-h | --help )
HELP ;;

--test )
TEST ;;

* )

cmd=$1
shift

if [ ! -d "$1" -o "$2" = "" -o ! "$cmd" = "lzm" -o ! "$cmd" = "nolzm" -o ! "$cmd" = "rom" ]; then
    HELP
    exit 1
fi

convert_dir2$cmd "$@"
if [ $? != 0 ]; then echo "error building modules "; exit 1; fi
;;
esac

#convert_dir2rom "$1" "$2" "$3"
#convert_dir2sqm "$1" "$2" "$3"

