#!/bin/bash
# MagOS project
# Authors: Alexandr Betсher
# Authors: Mikhail Zaripov
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

DEBUGMODE=no
. /liblinuxlive  2>/dev/null || . /mnt/live/liblinuxlive
debug_mode "$0" "$@"

WALLPAPERSRES=1920x1080
DEFWPDIR=/mnt/livedata/MagOS-Data/backgrounds/wallpapers/Default
DEFSSDIR=/mnt/livedata/MagOS-Data/backgrounds/screensaver/Default
SYSWPDIR=/usr/share/magos/wallpapers/Default
SYSSSDIR=/usr/share/magos/screensaver/Default
DEFWPFILE=/usr/share/magos/wallpapers/default.jpg
[ -f /etc/sysconfig/theme ] && . /etc/sysconfig/theme
[ -f /etc/sysconfig/MagOS ] && . /etc/sysconfig/MagOS

# setting screensaver theme
[ -z "$SSAVERTHEME" ] && SSAVERTHEME="$DEFSSDIR"
[ ! -d "$SSAVERTHEME" -a -d "$BACKGROUND" ] && SSAVERTHEME="$BACKGROUND"
[ ! -d "$SSAVERTHEME" -a -d "$DEFWPDIR" ] && SSAVERTHEME="$DEFWPDIR"
[ ! -d "$SSAVERTHEME" ] && SSAVERTHEME="$SYSWPDIR"
rm -f "$SYSSSDIR"
ln -sf "$SSAVERTHEME" "$SYSSSDIR"

# selecting file for default wallpaper
[ -z "$BACKGROUND" ] && BACKGROUND="$DEFWPDIR"
[ -r "$BACKGROUND" ] || BACKGROUND="$SYSWPDIR"
[ -d "$BACKGROUND" ] && BACKGROUND=$(find -L "$BACKGROUND" | egrep -i "[.]jpeg$|[.]jpg$" | sort -R | head -1)
[ -f "$BACKGROUND" ] || exit 0
rm -f "$DEFWPFILE"
cp -Lp "$BACKGROUND" "$DEFWPFILE"

[ -x /usr/bin/convert ] || exit 0

# detecting monitor resolution
[ "$(cmdline_value xres)" ] && XORG_RES=$(cmdline_value xres)
[ -z "$XORG_RES" -o "$XORG_RES" = "auto" ] && XORG_RES=$(monitor-edid | awk '/ModeLine/ { print $2 }' | sed -e 's/"//g' -e '2,$d')
[ -z "$XORG_RES" ] && XORG_RES=$(find -L /sys/class/drm/card0 -maxdepth 2 -name modes 2>/dev/null -exec cat '{}' \; | sort -t x -n -k 2 | tail -1)
echo "$XORG_RES" | grep -q ^[0-9]*x[0-9]*$ || XORG_RES=$WALLPAPERSRES

# resizing wallpaper for monitor resolution (default is proportional on black bacground)
RESIZEOPT="-resize $XORG_RES -background black -gravity center -extent $XORG_RES"
[ "$BACKGROUNDMODE" = "1" ] && RESIZEOPT="-resize $XORG_RES!"
[ "$BACKGROUNDMODE" = "2" ] && RESIZEOPT="-resize $XORG_RES^ -gravity center -extent $XORG_RES"
convert $RESIZEOPT "$DEFWPFILE" /tmp/background.jpg

# Graffiti effects
if [ "$GRAFFITI" = "yes" ] ;then
   [ "$(cmdline_value changes)$(cmdline_value uird.changes)" ] && LABEL=magos.png || LABEL=clean.png
   convert -resize x$(expr $(echo $XORG_RES | awk -Fx '{ print $2 }') / 10) /usr/share/magos/graffiti/$LABEL /tmp/logo.png
   composite -gravity SouthWest  /tmp/logo.png /tmp/background.jpg /tmp/background2.jpg
   mv -f /tmp/background2.jpg /tmp/background.jpg
   rm -f /tmp/logo.png
fi

# placing warning about default passwords
if [ "$GRAFFITI" != "no" -a -x /usr/bin/composite ] ;then
   egrep -q '^root\:\$2a\$08\$6Sd1ei3xkrWq21ypHSlgZOOlViPgyi4u.g7P0hZgpHx43cWwjO/Ji|^user\:\$2a\$08\$7zaCsmtvyXcGKVC3jRkUkeLnscv6s0mkXJ4GnJfrMzgmcMZzvF2a2' /etc/shadow && \
         composite -gravity NorthWest /usr/share/magos/graffiti/warning.png /tmp/background.jpg /tmp/background2.jpg
   [ -f /tmp/background2.jpg  ] && mv -f /tmp/background2.jpg /tmp/background.jpg
#   disabled slow method
#   convert $DEFAULTDIR/default.jpg  -gravity NorthWest -stroke '#000C' -strokewidth 1 -annotate 0 ' Warning: passwords are default - user:magos, root:toor ' -stroke  none  -fill red  -annotate 0 ' Warning: passwords are default - user:magos, root:toor ' $DEFAULTDIR/default.jpg
fi

# replacing default wallpaper
[ -f /tmp/background.jpg  ] && mv -f /tmp/background.jpg "$DEFWPFILE"

# making ksplash background
mkdir -p "/usr/share/apps/ksplash/Themes/Default/$XORG_RES"
convert "$DEFWPFILE" "/usr/share/apps/ksplash/Themes/Default/$XORG_RES/background.png"
