#!/bin/bash
#
# ifup-post-local       Helper script for MagOS Linux Live.
#
# Authors:	        Mikhail Zaripov <m3for@mail.ru>
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

NFSMOUNTTM=10
NFSMOUNTWAIT=6
NFSOPTS="vers=3,nolock,users,noauto"
[ -f /etc/sysconfig/MagOS ] && . /etc/sysconfig/MagOS

# mount MagOS-Server
sed -i /AUTOMOUNTSERVER=yes/d /etc/fstab
if [ "$AUTOMOUNTSERVER" = "yes" ] ;then
    while [ -z "$NFSMPLIST" -a "$NFSMOUNTTM" != "0" ] ;do
	sleep $NFSMOUNTWAIT
        NFSMPLIST=$(showmount --exports --no-headers MagOS-Server 2>/dev/null | awk '{print $1}' | grep ^/media/)
        NFSMOUNTTM=$(expr $NFSMOUNTTM - 1)
    done
    for a in $NFSMPLIST ;do
        MOUNTDEST=$(echo $a | sed s-/media-/mnt/server-)
        mkdir -p $MOUNTDEST 2>/dev/null
        [ -d "$MOUNTDEST" ] || continue
        grep -q " $MOUNTDEST " /etc/fstab || echo "MagOS-Server:$a $MOUNTDEST nfs $NFSOPTS 0 0 #AUTOMOUNTSERVER=yes" >> /etc/fstab
        grep -q " $MOUNTDEST " /proc/mounts ||  mount $MOUNTDEST 2>/dev/null
    done
fi
