#!/bin/bash
#
# magosctl      Helper script for MagOS Linux Live.
#
# Authors:	Anton Goroshkin <http://magos-linux.ru>
#
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0
DEBUGMODE=no
. /usr/lib/magos/scripts/liblinuxlive
. /usr/lib/magos/os-config
debug_mode "$0" "$@"

[ "$UPDATEGTKICONCACHE" = "yes" ] && gtk-update-icon-cache $UPDATEGTKICONOPTS >/dev/null 2>&1
