#!/bin/bash
#
# magosctl      Helper script for MagOS Linux Live.
#
# Authors:	Mikhail Zaripov <m3for@mail.ru>
#
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0
DEBUGMODE=no
. /usr/lib/magos/scripts/liblinuxlive
. /usr/lib/magos/os-config
debug_mode "$0" "$@"

. /etc/sysconfig/MagOS

# Registering mozilla extentions (firefox and thunderbird)
if [ "$REGISTERMOZEXT" = "yes" ] ;then
  for i in firefox thunderbird ; do
    if [ -d /usr/lib/mozilla/$i/extensions ] ;then
      for a in $(ls -d /usr/lib/mozilla/$i/extensions/* ) ; do
        for f in /usr/lib/$i-* ;do
           [ -d $f/extensions ] && ln -sf $a $f/extensions
           [ -d $f/browser/extensions ] && ln -sf $a $f/browser/extensions
        done
      done
    fi
    if [ -d /usr/lib64/mozilla/$i/extensions ] ;then
      for a in $(ls -d /usr/lib64/mozilla/$i/extensions/* ) ; do
        for f in /usr/lib64/$i-* ;do
           [ -d $f/extensions ] && ln -sf $a $f/extensions
           [ -d $f/browser/extensions ] && ln -sf $a $f/browser/extensions
        done
      done
    fi
  done
fi
