#!/bin/bash
#
# magosctl      Helper script for MagOS Linux Live.
#
# Authors:	Mikhail Zaripov <m3for@mail.ru>
#
[ -f /etc/sysconfig/MagOS ] && . /etc/sysconfig/MagOS

# Registering mozilla extentions (firefox and thunderbird)
for i in firefox thunderbird ; do
  if [ -d /usr/lib/mozilla/$i/extensions ] ;then
    for a in $(ls -d /usr/lib/mozilla/$i/extensions/* ) ; do
      for f in /usr/lib/$i-* ;do
         [ -d $f/extensions ] && ln -sf $a $f/extensions
      done
    done
  fi
done
