#!/bin/bash
#
# magosctl      Helper script for MagOS Linux Live.
#
# Authors:	Mikhail Zaripov <m3for@mail.ru>
#
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0
[ -f /etc/sysconfig/MagOS ] && . /etc/sysconfig/MagOS

[ "$NUMLOCK" = "yes" ] &&  for tty in /dev/tty[1-8]; do setleds -D +num < $tty ; done
[ "$NUMLOCK" = "yes" ] &&  chkconfig --add numlock
[ "$NUMLOCK" = "no" ] &&  for tty in /dev/tty[1-8]; do setleds -D -num < $tty ; done
[ "$NUMLOCK" = "no" ] &&  chkconfig --del numlock

