#!/bin/bash
# Description: This script will generate initial passwords for samba users
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0
DEBUGMODE=no
. /usr/lib/magos/scripts/liblinuxlive
. /usr/lib/magos/os-config
debug_mode "$0" "$@"

if [ "$MKSMBPWD" = "yes" ] ;then
  if ! grep -q nobody /etc/samba/passdb.tdb ;then
    echo -e \\n\\n | smbpasswd -Lsa nobody >/dev/null 2>&1
    for a in `grep users /etc/group | awk -F: '{print $4}' | tr ';,' ' '` ;do
       PASS=`echo $a | cat - /mnt/live/VERSION /proc/cmdline | md5sum | cut -c 1-5`
       echo -e $PASS\\n$PASS\\n | smbpasswd -Lsa $a >/dev/null 2>&1
    done
  fi
  if [ "$SHDSMBPWD" = "yes" ] ;then
    echo "Default samba passwords:"
    for a in `grep users /etc/group | awk -F: '{print $4}' | tr ';,' ' '` ;do
           PASS=`echo $a | cat - /mnt/live/VERSION /proc/cmdline | md5sum | cut -c 1-5`
           echo $a $PASS
    done
  fi
fi
