#!/bin/bash
# Description: This script will generate initial passwords for samba users
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

DEBUGMODE=no
. /usr/lib/magos/functions
debug_mode "$0" "$@"

[ -f /etc/sysconfig/MagOS ] && . /etc/sysconfig/MagOS
echo $MAGOSUPDATE | grep -qi ^auto$ || exit 0

/usr/lib/magos/scripts/magosupdate --auto >/dev/null  2>&1

exit 0
