#!/bin/bash
# Initial script for MagOS-Linux Live operating system
# This script are launching before starting init from linux-live script.
# Current dir allways must be set to root (/)
# All system path must be relative, except initrd dirs

export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

. /liblinuxlive

if [ $(cmdline_value savelist) ] ;then
   echo -ne .savelist
   for a in $(cmdline_value savelist | tr , " " ) ;do
       echo $a >>.savelist
   done
fi

