#!/bin/bash
# Initial script for MagOS-Linux Live operating system
# This script are launching before starting init from linux-live script.
# Current dir allways must be set to root (/)
# All system path must be relative, except initrd dirs

export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

. /liblinuxlive
. etc/sysconfig/MagOS

mkdir -p proc
mount -o rbind /proc proc
for a in $(echo $SERVICESSTART | tr , " ") ;do
    if [ -x bin/systemd ] ;then
       chroot . systemctl enable $a.service || chroot . chkconfig --add $a
    else
       chroot . chkconfig --add $a
    fi
done
for a in $(echo $SERVICESNOSTART | tr , " ") ;do
    if [ -x bin/systemd ] ;then
       chroot . systemctl disable $a.service || chroot . chkconfig --del $a
    else
       chroot . chkconfig --del $a 
    fi
done
umount proc

