#!/bin/bash
# Initial script for MagOS-Linux Live operating system
# This script are launching before starting init from linux-live script.
# Current dir allways must be set to root (/)
# All system path must be relative, except initrd dirs

export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

. /liblinuxlive


sed -i 's/id:.:initdefault:/id:5:initdefault:/' etc/inittab
ln -sf /lib/systemd/system/graphical.target etc/systemd/system/default.target
[ -x usr/bin/kdm ] || ln -sf /lib/systemd/system/gdm.service etc/systemd/system/display-manager.service
[ -x usr/bin/gdm -o -x usr/bin/kdm ] || ln -sf /lib/systemd/system/slim.service etc/systemd/system/display-manager.service

switch3don()
{
         echo "COMPOSITING_SERVER_START=no" >etc/sysconfig/compositing-server
         #Gnome-shell does not supports compiz, so turn on it only in classic mode and only after desktop started
         if [ -x usr/bin/gnome-shell ] ;then
            echo -e "COMPOSITING_WM_START=no\nCOMPOSITING_WM=compiz-fusion" >etc/sysconfig/compositing-wm
            sed -i /COMPOSITING_WM_START/d etc/sysconfig/MagOS
            echo COMPOSITING_WM_START=yes >> etc/sysconfig/MagOS
         else
            echo -e "COMPOSITING_WM_START=yes\nCOMPOSITING_WM=compiz-fusion" >etc/sysconfig/compositing-wm
         fi
         sed -i 's/^ *Xconfig::glx::write({});$/#    Xconfig::glx::write({});/' usr/lib/libDrakX/harddrake/autoconf.pm
}

switch3doff()
{
         echo "COMPOSITING_SERVER_START=no" >etc/sysconfig/compositing-server
         echo -e "COMPOSITING_WM_START=no\nCOMPOSITING_WM=compiz-fusion" >etc/sysconfig/compositing-wm
         sed -i /COMPOSITING_WM_START/d etc/sysconfig/MagOS
         sed -i 's/^#    Xconfig::glx::write({});$/    Xconfig::glx::write({});/' usr/lib/libDrakX/harddrake/autoconf.pm
}


for a in $(cmdline_value desktop | tr , " " ) ;do
   case $a in
       3d)
         switch3don
       ;;
       no3d)
         switch3doff
       ;;
       none)
         sed -i 's/id:.:initdefault:/id:3:initdefault:/' etc/inittab
         ln -sf /lib/systemd/system/multi-user.target etc/systemd/system/default.target
       ;;
       kde)
         echo -e "DISPLAYMANAGER=KDM\nDESKTOP=KDE4" >etc/sysconfig/desktop
         ln -sf /lib/systemd/system/kdm.service etc/systemd/system/display-manager.service
       ;;
       gnome)
         echo -e "DISPLAYMANAGER=GDM\nDESKTOP=GNOME" >etc/sysconfig/desktop
         ln -sf /lib/systemd/system/gdm.service etc/systemd/system/display-manager.service
       ;;
       gnome-shell|gnome3)
         echo -e "DISPLAYMANAGER=GDM\nDESKTOP=GNOMESHELL" >etc/sysconfig/desktop
         ln -sf /lib/systemd/system/gdm.service etc/systemd/system/display-manager.service
       ;;
       lxde)
         echo -e "DISPLAYMANAGER=slim\nDESKTOP=LXDE" >etc/sysconfig/desktop
         ln -sf /lib/systemd/system/slim.service etc/systemd/system/display-manager.service
       ;;
       kdm)
         sed -i 's/DISPLAYMANAGER=.*/DISPLAYMANAGER=KDM/' etc/sysconfig/desktop
         ln -sf /lib/systemd/system/kdm.service etc/systemd/system/display-manager.service
       ;;
       gdm)
         sed -i 's/DISPLAYMANAGER=.*/DISPLAYMANAGER=GDM/' etc/sysconfig/desktop
         ln -sf /lib/systemd/system/gdm.service etc/systemd/system/display-manager.service
       ;;
       slim)
         sed -i 's/DISPLAYMANAGER=.*/DISPLAYMANAGER=slim/' etc/sysconfig/desktop
         ln -sf /lib/systemd/system/slim.service etc/systemd/system/display-manager.service
       ;;
       lan)
         sed -i s/ONBOOT=no/ONBOOT=yes/ etc/sysconfig/network-scripts/ifcfg-eth0 2>/dev/null
       ;;
   esac
done

[ "$(cmdline_parameter 3ddesktop)" ] && switch3don
[ "$(cmdline_parameter no3ddesktop)" ] && switch3doff

#GDM3 default session fix
. etc/sysconfig/desktop
cat >etc/X11/dm/Sessions/00DEFAULT.desktop <<EOF
[Desktop Entry]
Encoding=UTF-8
Name=DEFAULT
Comment=Default MagOS Session
Exec=/usr/share/X11/xdm/Xsession $DESKTOP
Icon=
Type=Application
EOF

