#!/bin/bash
ENABLED=yes
DOMUSGR=audio,video,usb,vboxusers,bumblebee,cdrom,cdwriter,lp,floppy
[ "$ENABLED" != "yes" ] && exit 0
. /usr/lib/magos/os-config
. /etc/MagOS/config
if [ "$DOMAINUSERSHWACCESS" ] ;then
  for a in $(echo "$DOMAINUSERSHWACCESS" | tr ",;" " ") ;do
    for b in $(echo "$DOMUSGR" | tr ",;" " ") ;do
       usermod -a -G $b $a
    done
  done
fi
