#!/bin/bash
if [ "$(id -un)" != "root" ] ;then
   gksu -g "/bin/bash $0 $@"
   exit 0
fi

export PATH=/usr/lib/magos/scripts:$PATH

. liblinuxlive || exit 2

cat /proc/config.gz | gunzip | grep -q SQUASHFS_XZ && addparam="" || addparam="-nolzma"
cat /proc/config.gz | gunzip | grep -q SQUASHFS_XZ && MODULEFORMAT=xzm || MODULEFORMAT=lzm

case $1 in
   --nocompress | --oldpc )
      shift
      create_module "$1" "$1.oldpc.$MODULEFORMAT"  -noI -noD -noF $addparam  ;;
   * )
      create_module "$1" "$1.$MODULEFORMAT"  ;;
esac
if [ $? -eq 0 ] ; then
   mdialog --msgbox "Модуль готов"
else
   mdialog --error "Ошибка при создании модуля"
fi
