#!/bin/bash
# Install/Uninstall Linux Live scripts to /usr/bin and /usr/lib
# so the user is able to use all these commands while running his/her 
# Live Linux. This installer is automatically executed by build script.
#
# Why to install Linux Live scripts to your distribution? Well, you don't have to.
# You only have to, if you wish to use linux-live functions while you
# actually run the LiveCD created by these scripts.
#
# Author: Tomas M. <http://www.linux-live.org>
#

N=$(basename $0)

if [ "$N" = "build" ]; then
   N=install
else
   . ./.config || exit 1
   if [ "$1" ]; then CROOT="$1"; fi
fi

if [ "$N" != "uninstall" ]; then
   sed -r 's/^LIVECDNAME=.*/LIVECDNAME="'$LIVECDNAME'"/' ./tools/liblinuxlive > $CROOT/usr/lib/magos/scripts/liblinuxlive
else
   rm -v $CROOT/usr/lib/magos/scripts/liblinuxlive
fi

echo "Linux Live scripts were $N""ed successfuly in $1/"
