#!/bin/bash
#
# magosctl      Helper script for MagOS Linux Live.
#
# Authors:	Anton Goroshkin <http://magos-linux.ru>
#
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

gtk-update-icon-cache -fit /usr/share/icons/hicolor >/dev/null 2>&1
