#!/bin/bash
# Initial script for MagOS-Linux Live operating system
# This script are launching before starting init from linux-live script.
# Current dir allways must be set to root (/)
# All system path must be relative, except initrd dirs

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

. etc/sysconfig/MagOS
. usr/lib/magos/functions

[ $(cmdline_parameter depmod) ] && DEPMOD="yes"
[ "$DEPMOD" = "yes" ] && chroot . sbin/depmod -a

