#!/bin/bash
# Initial script for MagOS-Linux Live operating system
# This script are launching before starting init from linux-live script.
# Current dir allways must be set to root (/)
# All system path must be relative, except initrd dirs

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

. usr/lib/magos/functions
. etc/sysconfig/MagOS

touch /etc/fstab
mkdir -p boot proc sys dev tmp media mnt
chmod 1777 tmp
rmdir mnt/* 2>/dev/null

ps | grep ntfsmount | awk '{ print $1 }' >> var/run/sendsigs.omit

#Setting up local time zone
. etc/sysconfig/clock
[ "$UTC" = "false" ] && cp -pf usr/share/zoneinfo/$ZONE etc/localtime

#TODO - need check with dracut
#Profile updating
grep -q -f /VERSION etc/magos-release 2>/dev/null || rm -fr /memory/changes/var/lib/rpm  /memory/changes/var/lib/urpmi 2>/dev/null
cp -f /VERSION etc/magos-release

#TODO - need check
#devfs support
if [ -d run/udev/rules.d ] ;then
  mount -t devtmpfs none dev
fi

