#!/bin/bash
# Initial script for MagOS-Linux Live operating system
# This script are launching before starting init from linux-live script.
# Current dir allways must be set to root (/)
# All system path must be relative, except initrd dirs

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

. etc/sysconfig/MagOS

mkdir -p proc
mount -o rbind /proc proc
for a in $(echo $SERVICESSTART | tr , " ") ;do chroot . chkconfig --add $a ;done
for a in $(echo $SERVICESNOSTART | tr , " ") ;do chroot . chkconfig --del $a ;done
umount proc

