#!/bin/bash
#
# /usr/lib/magos/scripts/conv4mod
#
# Description: Convert modules 
# Author : Anton Goroshkin <http://magos-linux.ru>


if [ "$(id -un)" != "root" ] ;then
   beesu "/bin/bash '$0' $@"
   exit 0
fi

export PATH=/usr/lib/magos/scripts:$PATH

mod_dir=/mnt/live/memory/images

mdialog --msgbox  "Утилита для ковертирования модулей MagOS.\nВыберите директорию для сохранения модулей." || exit 1
dir_name=$(mdialog --getexistingdirectory /mnt/livemedia/) || exit 1
[ -z $dir_name ] && exit 1
format=$(mdialog --menu Формат_модулей xzm XZM lzm LZM nolzm LZM_nocompression) || exit 2
[ -z $format ] && exit 2
mask=$(mdialog --inputbox "Ограничить список модулей по маске" "??-") || exit 3
xterm -e dir2mod $format $mod_dir $dir_name $mask

