#!/bin/bash
# MagOS project
# Authors: Alexandr Betсher
# Authors: Mikhail Zaripov
[ -f /etc/sysconfig/theme ] && . /etc/sysconfig/theme
[ -f /etc/sysconfig/MagOS ] && . /etc/sysconfig/MagOS
[ -z "$BACKGROUND" ] && exit 0
DEFAULTDIR=/usr/share/mdk/backgrounds

grep -q xres= /proc/cmdline && XORG_RES=$(cat /proc/cmdline | awk -F xres= '{print $2}' | awk '{print $1}')
[ -z "$XORG_RES" -o "$XORG_RES" = "auto" ] && XORG_RES=$(monitor-edid | awk '/ModeLine/ { print $2 }' | sed -e 's/"//g' -e '2,$d')
[ -z "$XORG_RES" ] && XORG_RES=$(find -L /sys/class/drm/card0 -maxdepth 2 -name modes 2>/dev/null -exec cat '{}' \; | sort -t x -n -k 2 | tail -1)
echo "$XORG_RES" | grep -q ^[0-9]*x[0-9]*$ || XORG_RES=1024x768

SOURCE="$BACKGROUND"
[ -d "$SOURCE" ] && SOURCE=$(find "$SOURCE" | egrep -i "[.]jpeg$|[.]jpg$" | sort -R | head -1)
[ -f "$SOURCE" ] || SOURCE="$DEFAULTDIR/$BACKGROUND.jpg"
[ -f "$SOURCE" ] || SOURCE="$DEFAULTDIR/bluesth.jpg"

rm -f $DEFAULTDIR/default.jpg
if [ "$(dirname $SOURCE)" = "$DEFAULTDIR" ] ;then
   [ "$BACKTODATE" != "no" -a -f "$DEFAULTDIR/todate-$(date +%Y%m%d).jpg" ] && SOURCE="$DEFAULTDIR/todate-$(date +%Y%m%d).jpg"
   [ -f "${SOURCE/.jpg/-wide.jpg}" ] && [ "$(echo ${XORG_RES%x*}*3/4 | bc )" -gt "${XORG_RES#*x}" ] && SOURCE="${SOURCE/.jpg/-wide.jpg}"
fi
if [ "$(dirname $SOURCE)" = "$DEFAULTDIR" -o "$BACKGROUNDMODE" = "1" ] ;then
   convert -resize $XORG_RES! "$SOURCE" /tmp/background.jpg
elif [ "$BACKGROUNDMODE" = "2" ] ;then
   convert -resize $XORG_RES^ -gravity center -extent $XORG_RES "$SOURCE" /tmp/background.jpg
else
   convert -resize $XORG_RES -background black -gravity center -extent $XORG_RES "$SOURCE" /tmp/background.jpg
fi

if [ "$GRAFFITI" = "yes" ] ;then
   rm -f /tmp/graffiti-label.png 2>/dev/null
#   cp /usr/share/magos/graffiti/magos.png /tmp/graffiti-label.png
   cat /proc/cmdline | grep -q changes && LABEL= || LABEL=clean.png
   cat /proc/cmdline | egrep -q 'copy2ram|toram' && LABEL="$LABEL copy2ram.png"
   cat /proc/cmdline | grep -q save2module && LABEL="$LABEL save2module.png"
   [ -z "$LABEL" ] && LABEL=magos.png
   for a in $LABEL ; do
      if [ -f /tmp/graffiti-label.png ] ;then
         montage /tmp/graffiti-label.png /usr/share/magos/graffiti/$a -geometry +0+0 -background transparent /tmp/graffiti-label.png
      else
         cp /usr/share/magos/graffiti/$a /tmp/graffiti-label.png
      fi
   done
   convert -resize x$(expr $(echo $XORG_RES | awk -Fx '{ print $2 }') / 10) /tmp/graffiti-label.png /tmp/logo.png
   composite -gravity SouthWest  /tmp/logo.png /tmp/background.jpg $DEFAULTDIR/default.jpg
   rm -f /tmp/background.jpg /tmp/logo.png /tmp/label.png
else
   mv /tmp/background.jpg $DEFAULTDIR/default.jpg
fi

[ -f $DEFAULTDIR/default.jpg ] || ln -sf "$SOURCE" $DEFAULTDIR/default.jpg

[ -d "/usr/share/apps/ksplash/Themes/Default/$XORG_RES" ] || mkdir "/usr/share/apps/ksplash/Themes/Default/$XORG_RES"
convert $DEFAULTDIR/default.jpg "/usr/share/apps/ksplash/Themes/Default/$XORG_RES/background.png"
