#!/bin/bash
#
# Helper script for MagOS Linux Live.
#
# Authors:	Mikhail Zaripov <m3for@mail.ru>
#

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

DEBUGMODE=no
. /usr/lib/magos/scripts/liblinuxlive
[ "$DEBUGMODE" = "yes" ] && debug_mode "$0" "$@"

# sysctl variables
[ -f /etc/sysctl.conf ] && sysctl -p /etc/sysctl.conf
[ -f /etc/sysctl.d/magos.conf ] && sysctl -p /etc/sysctl.d/magos.conf

# If Linux installed on n[t]fs we have to omit killing rootfilesystem mounter when system halt
ps -A | egrep 'ntfsmount|rpciod|nfsiod|httpfs|curlftpfs' | awk '{ print $1 }' >> /var/run/sendsigs.omit

# Creating /etc/mtab
rm -f  /etc/mtab
ln -sf /proc/mounts /etc/mtab
