#!/bin/bash
#
# Helper script for MagOS Linux Live.
#
# Authors:	Mikhail Zaripov <m3for@mail.ru>
#

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

DEBUGMODE=no
. /liblinuxlive  2>/dev/null || . /mnt/live/liblinuxlive
debug_mode "$0" "$@"

# RPM5 vs ext3 bug workaround
if ! grep -q "tmpfs /mnt/live/memory tmpfs" /proc/mounts ;then
  # RPM5 vs ext3 bug workaround
  if ! grep -q /var/lib/rpmdb /proc/mounts ;then
    [ -d /var/lib/rpmdb ] || mkdir -p /var/lib/rpmdb
    # Removing cache
    rm -f /var/lib/rpm/__db* 2>/dev/null
    mount -o bind /var/lib/rpm /var/lib/rpmdb
    mount -t tmpfs tmpfs /var/lib/rpm
    rsync -a /var/lib/rpmdb/ /var/lib/rpm
  fi
fi
