#!/bin/bash
#
# magosctl      Helper script for MagOS Linux Live.
#
# Authors:	Mikhail Zaripov <m3for@mail.ru>
#
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0
DEBUGMODE=no
. /usr/lib/magos/scripts/liblinuxlive
. /usr/lib/magos/os-config
[ "$DEBUGMODE" = "yes" ] && debug_mode "$0" "$@"
. $HARDCONF
[ "$XDRIVER" != "nvidia" ] && rmmod nvidia
. /etc/sysconfig/MagOS

[ ! -z "$VGAID" ] && grep -q $VGAID /usr/share/magos/hwdata/deleteconf && rm -f /etc/X11/xorg.conf
[ "$DELETE_XORG_CONF" = "yes" ] && rm -f /etc/X11/xorg.conf

grep -q xres= /proc/cmdline && XORG_RES=$(cat /proc/cmdline | awk -F xres= '{print $2}' | awk '{print $1}')
if [ "$SETXORGRES" = "yes" ] ;then
  if ! [ -z "$XORG_RES" ] ;then 
     XCF=/etc/X11/xorg.conf
     grep -qi modes $XCF 2>/dev/null || XCF=/etc/X11/xorg.conf.d/00-modes.conf
     if grep -qi modes $XCF 2>/dev/null ;then
        sed -i 's|^[[:space:]]*Modes.*|        Modes "'$XORG_RES'"|' $XCF
     else
        cat >$XCF <<EOF
Section "Screen"
   Identifier "Screen"
   SubSection "Display"
        Modes "$XORG_RES"
   EndSubSection
EndSection
EOF
     fi
  fi
fi

if echo $DPMS | egrep -qi 'no|off|false' ;then
     sed -i s/'.*Option .DPMS..*'/'    Option "DPMS" "false"'/ /etc/X11/xorg.conf
fi

if [ "$MKKBDFXORG" = "yes" ] ;then
  if ! grep -qi XkbOptions /etc/X11/xorg.conf ;then
     . /etc/sysconfig/keyboard
     cat > /etc/X11/xorg.conf.d/00-keyboard.conf <<EOF
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "$XkbLayout"
        Option "XkbModel" "$XkbModel"
        Option "XkbVariant" "$KEYBOARD"
        Option "XkbOptions" "$XkbOptions"
EndSection
EOF
  fi
fi

