#!/bin/bash
# MagOS project
# Authors: Mikhail Zaripov

DIRGTK=gtk-2.0
DIRMETACITY=metacity-1
DIROPENBOX=openbox-3

[ -f /etc/sysconfig/theme ] && . /etc/sysconfig/theme
[ -f /etc/sysconfig/MagOS ] && . /etc/sysconfig/MagOS
. /usr/lib/magos/functions

if ! [ -z "$THEME" ] ;then
   case $THEME
       "MagOS"   ) 
           THEMEGTK=${THEMEGTK-MagOS}
           THEMEMETACITY=${THEMEMETACITY-MagOS}
           THEMEOPENBOX=${THEMEOPENBOX-MagOS}
           THEMEEMERALD=${THEMEEMERALD-MagOS}
           THEMEKDE=${THEMEKDE-MagOS}
           THEMEPLASMA=${THEMEPLASMA-Aya}
           ;;
        "MagOS-dark" )
           THEMEGTK=${THEMEGTK-MagOS-dark}
           THEMEMETACITY=${THEMEMETACITY-MagOS-dark}
           THEMEOPENBOX=${THEMEOPENBOX-MagOS-dark}
           THEMEEMERALD=${THEMEEMERALD-MagOS-dark}
           THEMEKDE=${THEMEKDE-MagOS-dark}
           THEMEPLASMA=${THEMEPLASMA-Aya}
           ;;
        "Mandriva" )
           THEMEGTK=${THEMEGTK-"Ia Ora Steel"}
           THEMEMETACITY=${THEMEMETACITY-"Ia Ora Steel"}
           THEMEOPENBOX=${THEMEOPENBOX-}
           THEMEEMERALD=${THEMEEMERALD-Adonis_Mod}
           THEMEKDE=${THEMEKDE-"Ia Ora Smooth"}
           THEMEPLASMA=${THEMEPLASMA-Mandriva}
           ;;
    esac
fi

if [ "$THEMEGTK" != "" -a -d "/usr/share/themes/$THEMEGTK/$DIRGTK" ]  ;then
   ln -sf "../$THEMEGTK/$DIRGTK"  "/usr/share/themes/Default/$DIRGTK"
fi
if [ "$THEMEMETACITY" != "" -a -d "/usr/share/themes/$THEMEMETACITY/$DIRMETACITY" ] ;then
   ln -sf "../$THEMEMETACITY/$DIRMETACITY" "/usr/share/themes/Default/$DIRMETACITY"
fi
if [ "$THEMEOPENBOX" != "" -a -d "/usr/share/themes/$THEMEOPENBOX/$DIROPENBOX" ] ;then
   ln -sf "../$THEMEOPENBOX/$DIROPENBOX" "/usr/share/themes/Default/$DIROPENBOX"
fi
if [ "$THEMEEMERALD" != "" -a -d "/usr/share/emerald/themes/$THEMEEMERALD" ] ;then
   rm -fr /usr/share/emerald/theme
   ln -sf "themes/$THEMEEMERALD" /usr/share/emerald/theme
fi
if [ "$THEMEPLASMA" != "" -a -d "/usr/share/apps/desktoptheme/$THEMEPLASMA" ] ;then
   echo -e "[Theme]\nname=Aya" > /var/lib/mandriva/kde4-profiles/common/share/config/plasmarc
   grep -q "defaultWallpaperTheme" "/usr/share/apps/desktoptheme/$THEMEPLASMA/metadata.desktop" || \
   echo -e  "\n[Wallpaper]\ndefaultWallpaperTheme=/usr/share/mdk/backgrounds/default.jpg" >> "/usr/share/apps/desktoptheme/$THEMEPLASMA/metadata.desktop"
fi
if [ "$THEMEKDE" != "" -a -f "/usr/share/apps/color-schemes/$THEMEKDE.colors" ] ;then
   concatenate_ini /var/lib/mandriva/kde4-profiles/common/share/config/kdeglobals "/usr/share/apps/color-schemes/$THEMEKDE.colors"
fi
