#!/bin/bash
# MagOS project
# Authors: Mikhail Zaripov
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

DEBUGMODE=no
. /usr/lib/magos/scripts/liblinuxlive
debug_mode "$0" "$@"

DIRGTK=gtk-2.0
DIRGTK3=gtk-3.0
DIRMETACITY=metacity-1
DIROPENBOX=openbox-3

[ -f /etc/sysconfig/theme ] && . /etc/sysconfig/theme
[ -f /etc/sysconfig/MagOS ] && . /etc/sysconfig/MagOS
. /usr/lib/magos/functions

if ! [ -z "$THEME" ] ;then
   case "$THEME" in
       "MagOS" | "MagOS-dark" | "MagOS-green" )
           THEMEGTK=${THEMEGTK-$THEME}
           THEMEGTK3=${THEMEGTK3-$THEME}
           THEMEMETACITY=${THEMEMETACITY-$THEME}
           THEMEOPENBOX=${THEMEOPENBOX-$THEME}
           THEMEEMERALD=${THEMEEMERALD-$THEME}
           THEMEKDE=${THEMEKDE-$THEME}
           THEMEKDEWIDGET=${THEMEKDEWIDGET-oxygen}
           THEMEKWIN=${THEMEKWIN-kwin3_oxygen}
           THEMEPLASMA=${THEMEPLASMA-Aya}
           ;;
    esac
fi

if [ "$THEMEGTK" != "" -a -d "/usr/share/themes/$THEMEGTK/$DIRGTK" ]  ;then
   rm -fr "/usr/share/themes/Default/$DIRGTK"
   ln -sf "../$THEMEGTK/$DIRGTK"  "/usr/share/themes/Default/$DIRGTK"
fi
if [ "$THEMEGTK3" != "" -a -d "/usr/share/themes/$THEMEGTK3/$DIRGTK3" ]  ;then
   rm -fr "/usr/share/themes/Default/$DIRGTK3"
   ln -sf "../$THEMEGTK3/$DIRGTK3"  "/usr/share/themes/Default/$DIRGTK3"
fi
if [ "$THEMEMETACITY" != "" -a -d "/usr/share/themes/$THEMEMETACITY/$DIRMETACITY" ] ;then
   rm -fr "/usr/share/themes/Default/$DIRMETACITY"
   ln -sf "../$THEMEMETACITY/$DIRMETACITY" "/usr/share/themes/Default/$DIRMETACITY"
fi
if [ "$THEMEOPENBOX" != "" -a -d "/usr/share/themes/$THEMEOPENBOX/$DIROPENBOX" ] ;then
   rm -fr "/usr/share/themes/Default/$DIROPENBOX"
   ln -sf "../$THEMEOPENBOX/$DIROPENBOX" "/usr/share/themes/Default/$DIROPENBOX"
fi
if [ "$THEMEEMERALD" != "" -a -d "/usr/share/emerald/themes/$THEMEEMERALD" ] ;then
   rm -fr /usr/share/emerald/theme
   ln -sf "themes/$THEMEEMERALD" /usr/share/emerald/theme
fi
if [ "$THEMEPLASMA" != ""  ] ;then
   echo -e "[Theme]\nname=$THEMEPLASMA" > /usr/share/magos/kde4/share/config/plasmarc
   if [ -d "/usr/share/apps/desktoptheme/$THEMEPLASMA" ] ;then
     if ! grep -q "defaultWallpaperTheme" "/usr/share/apps/desktoptheme/$THEMEPLASMA/metadata.desktop" ;then
       echo -e  "\n[Wallpaper]\ndefaultWallpaperTheme=/usr/share/magos/wallpapers/default.jpg" >> "/usr/share/apps/desktoptheme/$THEMEPLASMA/metadata.desktop"
     else
       sed -i 's|defaultWallpaperTheme=.*|defaultWallpaperTheme=/usr/share/magos/wallpapers/default.jpg|' "/usr/share/apps/desktoptheme/$THEMEPLASMA/metadata.desktop"
     fi
   fi
fi
if [ "$THEMEKDE" != "" -a -f "/usr/share/apps/color-schemes/$THEMEKDE.colors" ] ;then
   concatenate_ini /usr/share/magos/kde4/share/config/kdeglobals "/usr/share/apps/color-schemes/$THEMEKDE.colors"
fi
if [ "$THEMEKDEWIDGET" != "" ] ;then
   sed -i s/widgetStyle=.*/widgetStyle=$THEMEKDEWIDGET/ /usr/share/magos/kde4/share/config/kdeglobals
fi

if [ "$THEMEKWIN" != "" ] ;then
   sed -i s/PluginLib=.*/"PluginLib=$THEMEKWIN"/ /usr/share/magos/kde4/share/config/kwinrc
fi

if [ "$THEMEICONKDE" != "" ] ;then
   sed -i s/"Theme=.*"/"Theme=$THEMEICONKDE"/ /usr/share/magos/kde4/share/config/kdeglobals
fi

if [ "$THEMEICONGNOME" != "" ] ;then
   sed -i s/"IconTheme=.*"/"IconTheme=$THEMEICONGNOME"/ /usr/share/themes/Default/index.theme
fi

if [ "$THEMEICONLXDE" != "" ] ;then
   sed -i 's|sNet/IconThemeName=.*|sNet/IconThemeName='"$THEMEICONLXDE"'|' /etc/xdg/lxsession/LXDE/desktop.conf
fi
