#!/bin/sh
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

if [ "$1" != "fork" ] ;then
   $0 fork &
   exit 0
fi

sleep 3

BOOKMARKS=.local/share/user-places.xbel
HIDELOOP=255
HIDERAM=0
FFP=$HOME/$BOOKMARKS

if [ ! -f $FFP ] ;then
   dolphin /home &
   PIDDOL=$!
   while [ ! -f $FFP ] ;do sleep 0.1 ;done
   kill $PIDDOL
fi

if ! grep -q "devices/loop$HIDELOOP" $FFP ;then
  for a in $(seq 0 "$HIDELOOP") ;do
    grep -q devices/loop$a $FFP && continue
    cat >>$FFP <<EOF
 <separator>
  <info>
   <metadata owner="http://www.kde.org">
    <UDI>/org/freedesktop/UDisks2/block_devices/loop$a</UDI>
    <isSystemItem>true</isSystemItem>
    <IsHidden>true</IsHidden>
   </metadata>
   <metadata owner="http://freedesktop.org">
    <bookmark:icon name="drive-harddisk"/>
   </metadata>
  </info>
  <title>Loop device</title>
 </separator>
EOF
  done
  for a in $(seq 0 "$HIDERAM") ;do
    grep -q devices/ram$a $FFP && continue
    cat >>$FFP <<EOF
 <separator>
  <info>
   <metadata owner="http://www.kde.org">
    <UDI>/org/freedesktop/UDisks2/block_devices/ram$a</UDI>
    <isSystemItem>true</isSystemItem>
    <IsHidden>true</IsHidden>
   </metadata>
   <metadata owner="http://freedesktop.org">
    <bookmark:icon name="drive-harddisk"/>
   </metadata>
  </info>
   <title>Ram device</title>
 </separator>
EOF
  done
  sed -i /'<\/xbel>'/d $FFP
  echo '</xbel>' >> $FFP
fi
