#!/bin/sh
ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0
. /usr/lib/magos/os-config
. /etc/MagOS/config
which $(basename $0) >/dev/null 2>&1 || exit 0
[ "$QTERMINALSTART" != "no" ] && $(basename $0) --drop &
