.TH pfs-utils 12  "February, 2020" "version 4.*" "PFS-UTILS"
.SH NAME
pfs-utils \- scripts kit to manage squashfs modules for live linux distributions 
.SH DESCRIPTION
Scripts collection to create, merge, extract and load/unload pfs modules
.TP
\- aufs-n \- the list of layers in the order they are mounted to the root aufs
.TP
\- mkpfs \- create and merge modules
.TP
\- pfsextraxt \- extract packages from module, install packages 
.TP
\- pfsload \- mount modules (dirs, images) to the root aufs  
.TP
\- pfsunload \- unmount modules from root aufs
.TP
\- pfsuninstall \- remove package files from system
.TP
\- pfsrebuild \- rebuild loaded (installed) modules (packsges)  whith current changes
.TP
\- sync2layer \- create layer and move changes from top RW layer to new
.TP
\- pfsinfo \- list packsges in module
.TP
\- pfsfind \- find files in PFS modules
.TP
\- chroot2pfs \- creating the PFS module from changes made in the chroot created from the specified modules
.TP
\- addmemory \- increasing the size of the root aufs due the swap file
.TP
\- syschanges \- tracking changes in the rw layer of root aufs
.TP
\- pfs \- pfs-utils scripts library 
.SH EXIT STATUS
all utils returns a zero exit status if the job finished susfull.
.SH AUTHOR
forum.puppyrus.org team (sfs, zay, DdShuruck, betcher)
.TP
Wiki:   http://wiki.puppyrus.org/puppyrus/pr218/pfs4
.TP
Forum:  http://forum.puppyrus.org/index.php?board=188.0
.SH SEE ALSO
mksquashfs(1)
