#!/bin/bash
# License: GPL last version . Лицензия : GPL последней версии
# Written: Mikhail Zaripov . Написано: Михаил Зарипов
# Last modified: ___  . Исправлено _____

INET=on

if [ -f .config ] ;then 
  . .config
else
  echo "Не вижу файла .config" ;  exit 1
fi

mkdir -p loaded/cached_$VERREL loaded/$FLASHNAME-$VERREL
cd loaded/$FLASHNAME-$VERREL

rm -fr *.txt names urls re  2>/dev/null
# Чтобы не загружать постоянно списки можно закоментарить следующую строку
#[ "$INET" = "on" ] && rm -fr media pubkeys urpmi 2>/dev/null

mkdir -p media pubkeys urpmi/etc/urpmi urpmi/var/lib/urpmi urls names re/preferred

# Создание информации об источниках
echo -e "{\n}\n" >  urpmi/etc/urpmi/urpmi.cfg
echo "Загрузка списков хранилищ пакетов"
cd media
for a in `gawk '{print $2}' ../../../files/media/media_list-$STATUS-$VERREL-$ARCH` ;do
        echo -e "$a"
        MEDIAURL=`grep " $a " ../../../files/media/media_list-$STATUS-$VERREL-$ARCH | awk '{print $1}'`
        MEDIAKEY=`grep " $a " ../../../files/media/media_list-$STATUS-$VERREL-$ARCH | awk '{print $3}'`
        MEDIAUPD=`grep " $a " ../../../files/media/media_list-$STATUS-$VERREL-$ARCH | awk '{print $4}'`
        MEDIAADD=`grep " $a " ../../../files/media/media_list-$STATUS-$VERREL-$ARCH | awk '{print $5}'`

        if ! [ -f "$a" ] ;then
           curl -# --retry-delay 2 --retry 5 -o .listing -l "$MEDIAURL/" || exit 1
           if grep -q -i "a href=" .listing ;then 
               sed -i 's|<'[Aa]' |\n<a |g' .listing
               sed -i s/\'/\"/g .listing
               awk -F'<[Aa] [Hh][Rr][Ee][Ff]=["]?'  '{ print $2 }' .listing | awk -F'[" ]' '{print $1}' | grep .rpm |  sed s/'%2b'/'+'/g | sed s/'%25'/'%'/g | LC_ALL=C sort -V >> "$a"
           else
               grep .rpm .listing | LC_ALL=C sort -V >> "$a"
           fi
           sed -i s/'%2B'/'+'/g "$a"
           if [ -f ../../../files/rpm_names/$FLASHNAME-$VERREL/excluded ] ;then
              mv "$a" "$a"_full
              grep -vf ../../../files/rpm_names/$FLASHNAME-$VERREL/excluded "$a"_full > "$a"
              grep -f  ../../../files/rpm_names/$FLASHNAME-$VERREL/excluded "$a"_full > "$a".excluded
              grep -q . "$a".excluded || rm -f "$a".excluded
           fi
           rm -f .listing "$a"_full 2>/dev/null
           if [ "$MEDIAKEY" != "" -a "$MEDIAKEY" != "0" ] ;then
               curl -# --retry-delay 2 --retry 5 -o ../pubkeys/$a.pubkey "$MEDIAURL/media_info/pubkey" || exit 1
           fi
           if [ "$MEDIAUPD" != "skip" -a "$MEDIAUPD" != "nomediainfo" ] ;then
               mkdir ../urpmi/var/lib/urpmi/$a
               curl -# --retry-delay 2 --retry 5 -o ../urpmi/var/lib/urpmi/$a/MD5SUM "$MEDIAURL/media_info/MD5SUM" || exit 1
               curl -# --retry-delay 2 --retry 5 -o ../urpmi/var/lib/urpmi/$a/synthesis.hdlist.cz "$MEDIAURL/media_info/synthesis.hdlist.cz" || exit 1
           fi
           echo
        fi
        cat "$a" | awk '{ print "'$MEDIAURL/'" $1 }' | LC_ALL=C sort -V > "../urls/$a"
        if [ "$MEDIAUPD" != "skip" ] ;then
            echo "$a $MEDIAURL {" >>../urpmi/etc/urpmi/urpmi.cfg
            [ "$MEDIAKEY" != "0" ] && echo "  key-ids: $MEDIAKEY" >>../urpmi/etc/urpmi/urpmi.cfg
            [ "$MEDIAUPD" != "" -a  "$MEDIAUPD" != "nomediainfo" ] && echo "  $MEDIAUPD" >>../urpmi/etc/urpmi/urpmi.cfg
            [ "$MEDIAADD" != "" ] && echo "  $MEDIAADD" >>../urpmi/etc/urpmi/urpmi.cfg
            echo -e "}\n"  >>../urpmi/etc/urpmi/urpmi.cfg
        fi
done
cd ../
echo

# создаём список уже загруженных пакетов
ls -1 ../cached_$VERREL | grep [.]rpm$ > re/local_rpms.txt

# создание списка пакетов в источниках в соответствии с их приоритетом
touch re/names_default_media.txt re/urls_default_media.txt re/preferred/null re/excluded.txt
for a in $MEDIA_DEFAULT ;do
    cat media/$a | LC_ALL=C sort -rV >re/tmp.txt || exit 1
    cat re/names_default_media.txt re/tmp.txt >re/tmp2.txt || exit 1
    mv re/tmp2.txt re/names_default_media.txt || exit 1
    cat urls/$a | LC_ALL=C sort -rV >re/tmp.txt || exit 1
    cat re/urls_default_media.txt re/tmp.txt >re/tmp2.txt || exit 1
    mv re/tmp2.txt re/urls_default_media.txt || exit 1
done
rm -f re/tmp.txt

# создание списка исключений
if [ -d ../../files/rpm_names/$FLASHNAME-$VERREL/media_preferred ];then
   for a in `ls -1 ../../files/rpm_names/$FLASHNAME-$VERREL/media_preferred/*` ;do
       awk '{ print "^" $1 "$" }' "$a" >  re/preferred/${a##*/} || exit 1
       awk '{ print "^" $1 "$" }' "$a" >> re/excluded.txt || exit 1
       cat media/${a##*/} | LC_ALL=C sort -rV >re/names_${a##*/}.txt || exit 1
       cat urls/${a##*/} | LC_ALL=C sort -rV >re/urls_${a##*/}.txt || exit 1
   done
fi

echo "Создание списков rpm пакетов"
for a in `ls -1 ../../files/rpm_names/$FLASHNAME-$VERREL/??-*` ;do
    SHNM=${a##*/}
    echo $SHNM
    #поиск обычных пакетов
    grep -v -f re/excluded.txt "$a" | while read b ;do
         [ -z "$b" ] && continue
         RPMNM=
         [ -f ../../files/rpm_names/$FLASHNAME-$VERREL/special ] && RPMNM=$(grep -m1 "^$b[0-9]" ../../files/rpm_names/$FLASHNAME-$VERREL/special)
         [ -z "$RPMNM" ] &&  RPMNM=$(grep -m1 "^$b[0-9]" re/names_default_media.txt)
         if [ -z "$RPMNM" ] ;then
            echo "$b" >> re/not_founded.txt
         else
            echo $RPMNM >> names/$SHNM || exit 1
            grep -m1 "/$RPMNM$" re/urls_default_media.txt >> urls/$FLASHNAME-$VERREL.list
            grep -m1 -q ^$RPMNM$ re/local_rpms.txt || grep -m1 "/$RPMNM$" re/urls_default_media.txt >> urls/$FLASHNAME-$VERREL
         fi
    done
    #поиск пакетов с указанных источников
    grep -f re/excluded.txt "$a" | while read b ;do
         EXMD=$( grep -m1 "\\^$b\\$" re/preferred/* | awk -F: '{print $1}' | sed 's|.*/||') 
         [ -z "$EXMD" ] && exit 1
         RPMNM=
         [ -f ../../files/rpm_names/$FLASHNAME-$VERREL/special ] && RPMNM=$(grep -m1 "^$b[0-9]" ../../files/rpm_names/$FLASHNAME-$VERREL/special)
         [ -z "$RPMNM" ] && RPMNM=$(grep -m1 "^$b[0-9]" re/names_"$EXMD".txt)
         if [ -z "$RPMNM" ] ;then
            echo "$b" >> re/not_founded.txt
         else
            echo $RPMNM >> names/$SHNM || exit 1
            grep -m1 "/$RPMNM$" re/urls_default_media.txt >> urls/$FLASHNAME-$VERREL.list
            grep -m1 -q ^$RPMNM$ re/local_rpms.txt || grep -m1 "/$RPMNM$" re/urls_$EXMD.txt >> urls/$FLASHNAME-$VERREL
         fi
    done
done

if grep -q . urls/$FLASHNAME-$VERREL 2>/dev/null ;then
   if [ "$INET" = "on" ] ;then
       echo "Закачка файлов"
       cd ../cached_$VERREL
       wget -c -i ../$FLASHNAME-$VERREL/urls/$FLASHNAME-$VERREL || echo -e \n"Ошибка: Часть пакетов не загружена из-за ошибок, запустите скрипт ещё раз для их докачки"
   else
       echo "Ссылки сохранены в loaded/$FLASHNAME-$VERREL/urls/$FLASHNAME-$VERREL"
   fi
fi

cd "$MYPATH"

echo "Создаем источник для установки"
rm -fr "loaded/$FLASHNAME-$VERREL/rpms"
mkdir "loaded/$FLASHNAME-$VERREL/rpms"
cat loaded/$FLASHNAME-$VERREL/names/??-* | while read a ;do
    ln -sf ../../cached_$VERREL/$a loaded/$FLASHNAME-$VERREL/rpms || exit 1
done

echo "Обновление базы данных о скриптах"
mkdir -p loaded/rpmscripts_$VERREL
touch loaded/rpmscripts_$VERREL/scripts loaded/rpmscripts_$VERREL/noscripts
cat loaded/$FLASHNAME-$VERREL/names/??-* | LC_ALL=C sort >loaded/rpmscripts_$VERREL/rpms_$FLASHNAME-$VERREL
cat loaded/rpmscripts_$VERREL/scripts loaded/rpmscripts_$VERREL/noscripts | LC_ALL=C sort > loaded/rpmscripts_$VERREL/processed
diff loaded/rpmscripts_$VERREL/processed loaded/rpmscripts_$VERREL/rpms_$FLASHNAME-$VERREL | grep '> ' | sed s/^..// \
    | while read a ;do
    if ! rpm -qp --scripts "loaded/$FLASHNAME-$VERREL/rpms/$a" | grep -q . ;then
       echo $a >> loaded/rpmscripts_$VERREL/noscripts
    elif echo $a | grep -qf files/rpm_names/$FLASHNAME-$VERREL/noscripts ;then
       echo $a >> loaded/rpmscripts_$VERREL/noscripts
    else
       echo $a >> loaded/rpmscripts_$VERREL/scripts
    fi
done

[ -d loaded/$FLASHNAME-$VERREL/rpms/media_info ] && rm -fr loaded/$FLASHNAME-$VERREL/rpms/media_info
echo "Создание базы пакетов"
genhdlist2 loaded/$FLASHNAME-$VERREL/rpms || exit 1

echo "Проверка зависимостей"
mkcd --checkdeps loaded/$FLASHNAME-$VERREL/rpms >loaded/$FLASHNAME-$VERREL/checkdeps.txt 2>/dev/null
sed -i /^mkcd_build_hdlist/d loaded/$FLASHNAME-$VERREL/checkdeps.txt
sed -i /^done$/d loaded/$FLASHNAME-$VERREL/checkdeps.txt
if grep -q . loaded/$FLASHNAME-$VERREL/checkdeps.txt ;then
   cat loaded/$FLASHNAME-$VERREL/checkdeps.txt
   echo "Обнаружены ошибки зависимости пакетов. Нужно добавить или убрать пакеты в files/rpm_names/* и перезапустить сборку с начала"
fi

if [ -f loaded/$FLASHNAME-$VERREL/re/not_founded.txt ] ;then 
   echo "Ошибка: Не все пакеты были найдены в источниках."
   cat loaded/$FLASHNAME-$VERREL/re/not_founded.txt
fi

echo "Работа скрипта завершена."
exit 0
