#!/bin/bash
# License: GPL last version . Лицензия : GPL последней версии
# Written: Mikhail Zaripov . Написано: Михаил Зарипов
# Last modified: ___  . Исправлено _____

if [ -f .config ] ;then
  . .config
else
  echo "Не вижу файла .config" ;  exit 1
fi

cd "$MYPATH"

ERRPATH=rpms_err_$$
cd loaded/$FLASHNAME-$VERREL
echo "Проверка пакетов на целостность"
for b in srpms rpms ;do 
  cd $b
  for a in  *.rpm  ; do
    echo -ne $a\\r
    if !  rpm2cpio $a  >/dev/null 2>/dev/null ;then
          [ -d ../$ERRPATH ] || mkdir ../$ERRPATH
          mv `readlink $a` ../$ERRPATH
          rm -f $a
          echo -e \\r $a ERROR
    fi
    echo -ne $a\\r | tr [:print:] " "
  done
  cd ..
done
if [ -d $ERRPATH ] ; then
   echo "Обнаружены битые пакеты (перемещены в loaded/$FLASHNAME-$VERREL/$ERRPATH).  Повторите загрузку пакетов."
else
   echo "Работа скрипта завершена, вроде всё нормально"
fi 
cd ../../
