#!/bin/bash
# License: GPL last version . Лицензия : GPL последней версии
# Written: Mikhail Zaripov . Написано: Михаил Зарипов
# Last modified: ___  . Исправлено _____

DESTP=

if [ -f .config ] ;then
  . .config
else
  echo "Не вижу файла .config" ;  exit 1
fi

[ "$PAE" = "no" ] && DESTP=_nopae

cd "$MYPATH"

if [ -d  "work/$FLASHNAME-$VERREL/kernel$DESTP" ] ;then
   echo "Есть уже собранное ядро. Для новой сборки удалите work/$FLASHNAME-$VERREL/kernel$DESTP"
   exit 0
fi

echo "Обновление источников urpmi"
urpmi.update -a 

rm -fr work/rpmbuild 2>/dev/null
mkdir -p work/rpmbuild/SOURCES work/rpmbuild/SPECS loaded
. files/patches/kernel/$FLASHNAME-$VERREL/version
[ "$VERKERNEL" = "" ] && exit 1
[ "$RPMBPATH" = "" ] && RPMBPATH="$HOME/rpmbuild"
[ -d "$RPMBPATH" -a ! -h "$RPMBPATH" ] && mv "$RPMBPATH" "$RPMBPATH".bak
[ -d "$RPMBPATH" ] || ln -sf "$MYPATH/work/rpmbuild" $HOME/rpmbuild

cd loaded
echo "Закачиваем исходники ядра"
[ ! -f linux-$VERKERNEL.tar.xz ] &&  wget http://www.kernel.org/pub/linux/kernel/v3.x/linux-$VERKERNEL.tar.xz
[ ! -f linux-$VERKERNEL.tar.sign ] &&  wget http://www.kernel.org/pub/linux/kernel/v3.x/linux-$VERKERNEL.tar.sign
[ ! -z "$VERKPATCH" -a ! -f patch-$VERKPATCH.xz  ] && wget http://www.kernel.org/pub/linux/kernel/v3.x/patch-$VERKPATCH.xz
[ ! -z "$VERKPATCH" -a ! -f patch-$VERKPATCH.sign  ] && wget http://www.kernel.org/pub/linux/kernel/v3.x/patch-$VERKPATCH.sign
cd ..

[ -f loaded/linux-$VERKERNEL.tar.xz ] || exit 1
cp -pf loaded/linux-$VERKERNEL.tar.* $RPMBPATH/SOURCES || exit 1
[ -z "$VERKPATCH" ] || cp -pf loaded/patch-$VERKPATCH.* $RPMBPATH/SOURCES
cp -pf files/patches/kernel/$FLASHNAME-$VERREL/* $RPMBPATH/SOURCES || exit 1
mv -f  $RPMBPATH/SOURCES/*.spec $RPMBPATH/SPECS || exit 1

if [ ! -z "$DESTP" ] ;then
   cp -pf files/patches/kernel$DESTP/$FLASHNAME-$VERREL/* $RPMBPATH/SOURCES || exit 1
   cat files/patches/kernel$DESTP/$FLASHNAME-$VERREL/kernel_spec_pae.patch | patch -d $RPMBPATH/SPECS -p1 || exit 1
fi

echo "Сборка ядра"
rm -f $RPMBPATH/RPMS/i586/kernel-*.rpm $RPMBPATH/SRPMS/kernel-*.src.rpm 2>/dev/null
rpmbuild -bs $RPMBPATH/SPECS/kernel*.spec || exit 1
rpmbuild -bb $RPMBPATH/SPECS/kernel*.spec --with=build_for_magos || exit 1

echo "Переносим готовые пакеты в work/$FLASHNAME-$VERREL/kernel$DESTP"
mkdir -p work/$FLASHNAME-$VERREL/kernel$DESTP/src
mv $RPMBPATH/RPMS/i586/kernel-*.rpm work/$FLASHNAME-$VERREL/kernel$DESTP || exit 1
mv $RPMBPATH/RPMS/noarch/kernel-*.rpm work/$FLASHNAME-$VERREL/kernel$DESTP 2>/dev/null
mv $RPMBPATH/SRPMS/kernel-*.src.rpm work/$FLASHNAME-$VERREL/kernel$DESTP/src || exit 1

echo "Удаление временных файлов"
rm -fr work/rpmbuild $HOME/rpmbuild
[ -d "$RPMBPATH.bak" ] && mv "$RPMBPATH.bak" "$RPMBPATH"

echo "Работа скрипта завершена, готовые пакеты лежат в work/$FLASHNAME-$VERREL/kernel$DESTP"
