#!/bin/bash
# License: GPL last version . Лицензия : GPL последней версии
# Written: Mikhail Zaripov . Написано: Михаил Зарипов
# Last modified: ___  . Исправлено _____

if [ "`id -u`" != "0" ] ;then
   echo Для доступа ко всем папкам rootfs нужны права root.
   exit 1
fi

if [ -f .config ] ;then
  . .config
else
  echo "Не вижу файла .config" ;  exit 1
fi

echo "Создание образа дистрибутива"
cd "$MYPATH"/work/$FLASHNAME-$VERREL
umount mirror/rootfs 2>/dev/null
rm -fr mirror 2>/dev/null
mkdir -p mirror/changes mirror/rootfs mirror/magos || exit 1
mount -t aufs -o br:mirror/changes=rw:rootfs=ro aufs mirror/rootfs || exit 1

echo "Удаление файлов для уменьшения размера"
cp -p ../../files/patches/rootfs/$FLASHNAME/usr/lib/magos/rootfs-patches/MagOS-clean_distr.sh mirror/rootfs
chroot mirror/rootfs /MagOS-clean_distr.sh || exit 1
rm -f mirror/rootfs/MagOS-clean_distr.sh

echo "Добавление файлов в дистрибутив"
mknod -m 666 mirror/rootfs/dev/null c 1 3
[ -d ../../loaded/$FLASHNAME-$VERREL/urpmi ] &&  cp -pfR ../../loaded/$FLASHNAME-$VERREL/urpmi/* mirror/rootfs
for a in $FLASHNAME $FLASHNAME-$VERREL ;do
    [ -d ../../files/patches/rootfs/$a ] && cp -pfR ../../files/patches/rootfs/$a/* mirror/magos
done
mkdir -p -m 755 mirror/rootfs/var/lib/rpm/modules
cp -p ../../loaded/$FLASHNAME-$VERREL/names/??-* mirror/rootfs/var/lib/rpm/modules || exit 1

echo "Изменение файлов дистрибутива"
umount mirror/rootfs || exit 1
mount -t aufs -o br:mirror/changes=rw:mirror/magos=ro:rootfs=ro aufs mirror/rootfs || exit 1
mkdir -p mirror/rootfs/proc mirror/rootfs/sys mirror/rootfs/tmp mirror/rootfs/mnt/live
mount -o bind /dev  mirror/rootfs/dev
mount -o bind /proc mirror/rootfs/proc
mount -o bind /sys  mirror/rootfs/sys
echo $VERREL $(date +%Y%m%d)  > mirror/rootfs/mnt/live/VERSION
chroot mirror/rootfs /usr/lib/magos/rootfs-patches/$FLASHNAME-patch_distr.sh
[ -f mirror/rootfs/usr/lib/magos/rootfs-patches/${FLASHNAME}_${VERREL}-patch_distr.sh ] && chroot mirror/rootfs /usr/lib/magos/rootfs-patches/${FLASHNAME}_${VERREL}-patch_distr.sh
umount mirror/rootfs/dev mirror/rootfs/proc mirror/rootfs/sys mirror/rootfs
rm -fr mirror/changes/proc mirror/changes/sys mirror/changes/mnt mirror/changes/tmp
ln -sf /proc/mounts mirror/changes/etc/mtab

echo "Работа скрипта завершена"

exit 0

