#!/bin/bash
# License: GPL last version . Лицензия : GPL последней версии
# Written: Mikhail Zaripov . Написано: Михаил Зарипов
# Last modified: ___  . Исправлено _____

if [ -f .config ] ;then
  . .config
else
  echo "Не вижу файла .config" ;  exit 1
fi

cd "$MYPATH"

echo "Добавляем ядро к пакетам дистрибутива."
if [ -d work/$FLASHNAME-$VERREL/kernel ] ;then
   cd work/$FLASHNAME-$VERREL/kernel
   for a in kernel-desktop-*flash*.$ARCH.rpm kernel-2.*flash*.$ARCH.rpm ;do
       echo $a
       ln -sf ../../../work/$FLASHNAME-$VERREL/kernel/$a ../../../loaded/$FLASHNAME-$VERREL/rpms || exit 1
   done
#   cp -p dkms/* ../../loaded/rpms || exit 1
   echo "Пакеты добавлены в источник"
else
   echo "Сначала нужно собрать ядро, чтобы готовые пакеты были в work/$FLASHNAME-$VERREL/kernel"
fi
