#!/bin/bash
# License: GPL last version . Лицензия : GPL последней версии
# Written: Mikhail Zaripov . Написано: Михаил Зарипов
# Last modified: ___  . Исправлено _____
if [ -f .config ] ;then
  . .config
else
  echo "Не вижу файла .config" ;  exit 1
fi
cd "$MYPATH"

if [ "`id -u`" != "0" ] ;then
   echo "Для доступа ко всем файлам work/ нужны права root"
   exit 1
fi

echo "Подготовка"
DISTRVERSION=$(date +%Y%m%d)
DESTDIR=flash/${FLASHNAME}_${VERREL}_${DISTRVERSION}
[ -d "$DESTDIR" ] && rm -fr "$DESTDIR"
mkdir -p "$DESTDIR"/$FLASHNAME/{base,modules,optional,rootcopy} \
  "$DESTDIR"/$FLASHNAME-Data/{changes,homes,modules,optional,rootcopy,cache,steam,backgrounds/wallpapers/Default,backgrounds/screensaver/Default} \
  "$DESTDIR"/$FLASHNAME-Data/machines/{static,dynamic} "$DESTDIR"/$FLASHNAME/machines/{static,dynamic} \
  flash/additions/${FLASHNAME}_${VERREL}_${DISTRVERSION}-international || exit 1
chmod 777 "$DESTDIR"/$FLASHNAME-Data/steam
echo $VERREL $DISTRVERSION > "$MYPATH/$DESTDIR"/$FLASHNAME/VERSION || exit 1
cp -pR files/patches/flash/* "$DESTDIR" || exit 1
[ -d files/patches/flash.$VERREL ] && cp -pfR files/patches/flash.$VERREL/* "$DESTDIR"
cp -L work/$FLASHNAME-$VERREL/rootfs/boot/vmlinuz "$MYPATH/$DESTDIR"/$FLASHNAME || exit 1
[ -f work/$FLASHNAME-$VERREL/mirror/changes/boot/initrd.gz ] && cp -L work/$FLASHNAME-$VERREL/mirror/changes/boot/initrd.gz "$MYPATH/$DESTDIR"/$FLASHNAME

echo "Создание модулей"
cd "$MYPATH/work/$FLASHNAME-$VERREL/split/modules" || exit 1
for a in * ;do
    echo $a
    mksquashfs $a "$MYPATH/$DESTDIR/$FLASHNAME/base/$a.xzm" $MKSQOPT >/dev/null 2>/dev/null || exit 1
done
chmod 444 "$MYPATH/$DESTDIR/$FLASHNAME/base/"*.xzm
mv "$MYPATH/$DESTDIR/$FLASHNAME/base/"??-int-*.xzm "$MYPATH"/flash/additions/${FLASHNAME}_${VERREL}_${DISTRVERSION}-international

echo "Вычисление контрольных сумм"
cd "$MYPATH/$DESTDIR/$FLASHNAME"
md5sum vmlinuz >MD5SUM
[ -f initrd.gz ] && md5sum initrd.gz >>MD5SUM
[ -f uird.magos.cpio.xz ] && md5sum uird.magos.cpio.xz >>MD5SUM
md5sum base/*.xzm >>MD5SUM

echo "Добавление графического материала"
cd "$MYPATH/../graphics" || exit 1
./make_default_themes.sh
cp -p wallpapers/Default/*  $MYPATH"/$DESTDIR/$FLASHNAME-Data/backgrounds/wallpapers/Default"
cp -p screensaver/Default/* $MYPATH"/$DESTDIR/$FLASHNAME-Data/backgrounds/screensaver/Default"

echo "Создание файлов для сохранения данных и архивов папок"
cd "$MYPATH"/$DESTDIR
[ "$DATASIZE1" != "" ] && dd if=/dev/zero of=$FLASHNAME-Data/home.img bs=1M count=$DATASIZE1 && mkfs.ext3 -F -j $FLASHNAME-Data/home.img >/dev/null 2>&1
tar -jcf $FLASHNAME/$FLASHNAME-Data.tar.bz2 $FLASHNAME-Data
tar -jcf $FLASHNAME/boot.tar.bz2 boot EFI

echo "Работа скрипта завершена, в папке flash лежит готовая к установке система :-)"
