#!/bin/bash
# License: GPL last version . Лицензия : GPL последней версии
# Written: Mikhail Zaripov . Написано: Михаил Зарипов
# Last modified: ___  . Исправлено _____

if [ "`id -u`" != "0" ] ;then
   echo Для доступа ко всем папкам rootfs нужны права root.
   exit 1
fi

if [ -f .config ] ;then
  . .config
else
  echo "Не вижу файла .config" ;  exit 1
fi


echo "Изменение файлов дистрибутива"
cd "$MYPATH"/work/$FLASHNAME-$VERREL
rm -fr rootfs/etc/skel/tmp
cp -pfR ../../loaded/$FLASHNAME-$VERREL/urpmi/* rootfs
for a in rootfs rootfs-$FLASHNAME rootfs-$FLASHNAME-$VERREL ;do
    [ -d ../../files/patches/rootfs/$a ] && cp -pfR ../../files/patches/rootfs/$a/* rootfs
done
cd rootfs
mkdir -p usr/lib/magos/rootfs-patches
cp -p ../../../files/patches/rootfs/$FLASHNAME-*.sh usr/lib/magos/rootfs-patches
cp -p ../../../files/patches/rootfs/${FLASHNAME}_${VERREL}-*.sh usr/lib/magos/rootfs-patches
for a in usr/lib/magos/rootfs-patches/*.sh ;do
   [ -f $a ] || continue
   echo $a
   bash $a || exit 1
done
if [ "$SQFSVER" = "3" ] ;then
  ln -sf /usr/bin/unsquashfs3 usr/lib/magos/scripts/unsquashfs
  ln -sf /usr/bin/mksquashfs3 usr/lib/magos/scripts/mksquashfs
  MODULEFORMAT=lzm
else
  ln -sf /usr/bin/unsquashfs usr/lib/magos/scripts/unsquashfs
  ln -sf /usr/bin/mksquashfs usr/lib/magos/scripts/mksquashfs
  MODULEFORMAT=xzm
fi
[ "$MKSQOPT" != "" ] && sed -i s/MKSQOPT=.*/MKSQOPT=\""$MKSQOPT"\"/ usr/lib/magos/scripts/liblinuxlive
sed -i s/MODULEFORMAT=.*/MODULEFORMAT=\""$MODULEFORMAT"\"/ usr/lib/magos/scripts/liblinuxlive

echo "Отключение всех служб"
cd etc/xinetd.d
for a in * ;do
   if grep -q service $a ;then
      chroot "$MYPATH/work/$FLASHNAME-$VERREL/rootfs" chkconfig --del $a 2>/dev/null
   fi
done
cd ../rc.d/init.d
for a in * ;do
   if grep -q "chkconfig:" $a || grep -q "### BEGIN INIT INFO"  $a ;then
      chroot "$MYPATH/work/$FLASHNAME-$VERREL/rootfs" chkconfig --del $a 2>/dev/null
   fi
done

echo "Включение нужных служб"
for a in  $INITDNEED  ;do
   [ -f $a ] || continue
   echo $a
   chroot "$MYPATH/work/$FLASHNAME-$VERREL/rootfs" chkconfig --add $a
done

if [ -d ../../localpatches ] ;then
    cp -pfR ../../localpatches/* rootfs
fi

echo "Работа скрипта завершена"
exit 0

