#!/bin/bash
# License: GPL last version . Лицензия : GPL последней версии
# Written: Mikhail Zaripov . Написано: Михаил Зарипов
# Last modified: ___  . Исправлено _____
if [ -f .config ] ;then
  . .config
else
  echo "Не вижу файла .config" ;  exit 1
fi
cd "$MYPATH"

if [ "`id -u`" != "0" ] ;then
   echo "Для доступа ко всем файлам work нужны права root"
   exit 1
fi

if [ "$SQFSVER" = "3" ] ;then
  MKSQUASHFS=mksquashfs3
  UNSQUASHFS=unsquashfs3
  MODULEFORMAT=lzm
else
  MKSQUASHFS=mksquashfs
  UNSQUASHFS=unsquashfs
  MODULEFORMAT=xzm
fi

function umountbranches()
{
 while grep -q "$1" /proc/mounts ;do
   grep "$1" /proc/mounts | awk '{print $2}' | while read a ;do
      echo umount "$a"
      umount "$a" 2>/dev/null
   done
 done
}

echo "Сборка ядра"
PAE=no ./2_makekernel || exit 1

echo "Создание временной ветви rootfs для сборки"
umountbranches "work/$FLASHNAME-$VERREL/nopae"
rm -fr work/$FLASHNAME-$VERREL/nopae 2>/dev/null || exit 1
mkdir -p work/$FLASHNAME-$VERREL/nopae/changes work/$FLASHNAME-$VERREL/nopae/rootfs || exit 1
cd work/$FLASHNAME-$VERREL/nopae || exit 1
mount -t aufs -o br:changes=rw:../rootfs=ro aufs rootfs || exit 1
cd rootfs

echo "Удаление ядра pae"
for a in `rpm --root "$(pwd)" -qa | grep kernel | grep -v firmware ` ;do
    rpm --noscripts --nodeps -ev --root "$(pwd)" $a
done
rm -fr lib/modules/* var/lib/dkms-binary/*

echo "Установка ядра nopae"
ln -sf /bin/true sbin/mkinitrd 
mkdir -p tmp proc sys dev
mount -o bind /dev dev || exit 1
mount -o bind /proc proc || exit 1
mount -o bind /sys sys || exit 1
rpm --root "$(pwd)" --nodeps -ihv ../../kernel_nopae/kernel-desktop-2.6.*.$ARCH.rpm ../../kernel_nopae/kernel-desktop-devel-2.6.*.$ARCH.rpm || exit 1
KERNSVER=`ls -1d usr/src/linux-* | sed 's|/$||' | sed 's|.*/||'`
KERNBVER=`ls -1d lib/modules/* | sed 's|/$||' | sed 's|.*/||'`
ln -sf /usr/src/$KERNSVER lib/modules/$KERNBVER/build || exit 1
ln -sf /usr/src/$KERNSVER lib/modules/$KERNBVER/source || exit 1
cd boot || exit 1
rm -f vmlinuz 2>/dev/null
ln -sf $(ls -1 vmlinuz-*nopae* | tail -1) vmlinuz || exit 1
cd ..

cd "$MYPATH"
RTFSINSTALL="work/$FLASHNAME-$VERREL/nopae/rootfs" \
RTFSMAKE="$RTFSINSTALL" \
KRNLPATH="work/$FLASHNAME-$VERREL/kernel_nopae/dkms" \
./5_makedkms || exit 1

echo "Cоздание каталога nopae_addon"
DISTRVERSION=$(find flash  -maxdepth 3 -type f | grep $FLASHNAME.sgn | tail -1 | awk -F/ '{print $2}' | awk -F_ '{print $3}' )
[ -z "$DISTRVERSION" ] && exit 1

rm -fr flash/additions/${FLASHNAME}_${VERREL}_${DISTRVERSION}-nopae 2>/dev/null
mkdir -p flash/additions/${FLASHNAME}_${VERREL}_${DISTRVERSION}-nopae/$FLASHNAME/base || exit 1
cp -p $(ls -1 work/$FLASHNAME-$VERREL/nopae/rootfs/boot/vmlinuz-*nopae*) flash/additions/${FLASHNAME}_${VERREL}_${DISTRVERSION}-nopae/$FLASHNAME/vmlinuz || exit 1


echo "Cоздание initrd"
mkdir -p "work/$FLASHNAME-$VERREL/nopae/rootfs/mnt/live"
echo "$VERREL $DISTRVERSION" > "work/$FLASHNAME-$VERREL/nopae/rootfs/mnt/live/VERSION"
chroot "work/$FLASHNAME-$VERREL/nopae/rootfs" /usr/lib/magos/scripts/mkinitrd /boot/initrd.gz || exit 1
mv work/$FLASHNAME-$VERREL/nopae/rootfs/boot/initrd.gz flash/additions/${FLASHNAME}_${VERREL}_${DISTRVERSION}-nopae/$FLASHNAME/initrd.gz || exit 1

echo "Сжатие файлов в модуль"
mkdir -p work/$FLASHNAME-$VERREL/nopae/rootfs/kernel/{boot,lib,var/lib,usr/src}
mv work/$FLASHNAME-$VERREL/nopae/rootfs/boot/System.map-*nopae* work/$FLASHNAME-$VERREL/nopae/rootfs/kernel/boot
mv work/$FLASHNAME-$VERREL/nopae/rootfs/boot/config-*nopae* work/$FLASHNAME-$VERREL/nopae/rootfs/kernel/boot
mv work/$FLASHNAME-$VERREL/nopae/rootfs/boot/symvers-*nopae* work/$FLASHNAME-$VERREL/nopae/rootfs/kernel/boot
mv work/$FLASHNAME-$VERREL/nopae/rootfs/lib/modules work/$FLASHNAME-$VERREL/nopae/rootfs/kernel/lib
mv work/$FLASHNAME-$VERREL/nopae/rootfs/var/lib/dkms-binary work/$FLASHNAME-$VERREL/nopae/rootfs/kernel/var/lib
mv work/$FLASHNAME-$VERREL/nopae/rootfs/usr/src/$KERNSVER work/$FLASHNAME-$VERREL/nopae/rootfs/kernel/usr/src
$MKSQUASHFS work/$FLASHNAME-$VERREL/nopae/rootfs/kernel flash/additions/${FLASHNAME}_${VERREL}_${DISTRVERSION}-nopae/$FLASHNAME/base/00-kernel.$MODULEFORMAT $MKSQOPT >/dev/null 2>&1
umountbranches "work/$FLASHNAME-$VERREL/nopae" && rm -fr "work/$FLASHNAME-$VERREL/nopae"
echo "Работа скрипта завершена"

exit 0


