#!/bin/bash
# License: GPL last version . Лицензия : GPL последней версии
# Written: Mikhail Zaripov . Написано: Михаил Зарипов
# Last modified: ___  . Исправлено _____
if [ -f .config ] ;then
  . .config
else
  echo "Не вижу файла .config" ;  exit 1
fi
cd "$MYPATH"

if [ "`id -u`" != "0" ] ;then
   echo "Для доступа ко всем файлам work нужны права root"
   exit 1
fi

function move_kernel()
{
  mkdir -p lib/modules boot usr/src usr/share/doc var/lib/dkms-binary  2>/dev/null
  mv ../../rootfs/boot/*flash* boot
  mv ../../rootfs/lib/modules/*flash* lib/modules
  mv ../../rootfs/usr/src/*flash* usr/src
  mv ../../rootfs/usr/share/doc/kernel-*flash* usr/share/doc
  mv ../../rootfs/var/lib/dkms-binary/* var/lib/dkms-binary
}

echo "Сборка ядра"
PAE=no ./3_makekernel
echo "Перенос текущего ядра"
rm -fr work/$FLASHNAME-$VERREL/kernel/bin 2>/dev/null
mkdir -p work/$FLASHNAME-$VERREL/kernel/bin
cd work/$FLASHNAME-$VERREL/kernel/bin || exit 1
move_kernel

echo "Установка ядра nopae"
cd "$MYPATH/work/$FLASHNAME-$VERREL/rootfs"
rpm2cpio ../kernel_nopae/kernel-desktop-devel-2.6.*.$ARCH.rpm | cpio -i --make-directories
rpm2cpio ../kernel_nopae/kernel-desktop-2.6.*.$ARCH.rpm | cpio -i --make-directories
KERNVER=`ls -1d usr/src/linux-* | sed s/^.*linux-// | sed s/mnb.*$/mnb/`
ln -sf /usr/src/linux-$KERNVER lib/modules/$KERNVER/build
ln -sf /usr/src/linux-$KERNVER lib/modules/$KERNVER/source
cd boot
ln -sf vmlinuz-* vmlinuz
cd ..
echo "Установка dkms модулей"
LC_ALL=C rpm $OPTS --noscripts --nodeps --root "$MYPATH/work/$FLASHNAME-$VERREL/rootfs" -ihv "$MYPATH"/loaded/$FLASHNAME-$VERREL/rpms/dkms-[a-ln-z]*.rpm
echo "Создание модулей ядра средствами dkms"
# вытаскиваем скрипты при установке модулей dkms, делаем из них скрипт
rpm -qp --triggers --scripts ../../../loaded/$FLASHNAME-$VERREL/rpms/dkms-[a-ln-z]*.rpm \
    | grep "^[/usr/sbin/]*dkms " | grep -v remove \
    | sed s/" install "/" mkrpm "/  | tr -d \& > dkms_scripts || exit 1
# надо указать ядро флешки
sed -i s/"dkms "/"dkms -k `ls -1 lib/modules/ | tail -1 | tr -d /` "/ dkms_scripts || exit 1
# Сборка rpm пакетов
rm -f dev/null 
echo -ne >dev/null
mkdir tmp var/tmp
chroot "$MYPATH/work/$FLASHNAME-$VERREL/rootfs" bash /dkms_scripts || exit 1

echo "Вытаскиваем rpm пакеты"
[ -d ../kernel_nopae/dkms ] && rm -fr ../kernel_nopae/dkms
mkdir ../kernel_nopae/dkms
cd var/lib/dkms
for a in ` find | grep .rpm$` ;do
   cp $a ../../../../kernel_nopae/dkms
done
cd ../../../
rm -f dkms_scripts Module.symvers

echo "Удаляем dkms пакеты"
for a in `rpm --root "$MYPATH/work/$FLASHNAME-$VERREL/rootfs" -qa | grep dkms-[a-z] | grep -v dkms-minimal ` ;do
     rpm -ev --nodeps --root "$MYPATH/work/$FLASHNAME-$VERREL/rootfs" $a
done

echo "Устанавливаем пакеты с модулями"
cd ../kernel_nopae/dkms
rpm --nodeps --root "$MYPATH/work/$FLASHNAME-$VERREL/rootfs" -ihv *.rpm

cd "$MYPATH/work/$FLASHNAME-$VERREL/rootfs"
mv var/lib/dkms/dkms_dbversion ./
rm -fr var/lib/dkms/* tmp dev/null
mv dkms_dbversion var/lib/dkms
mknod dev/null c 1 3

echo "Перенос ядра nopae"
rm -fr ../kernel_nopae/bin 2>/dev/null
mkdir -p ../kernel_nopae/bin
cd ../kernel_nopae/bin || exit 1
move_kernel
for a in `find | grep [.]ko[.]gz$` ;do
   gunzip $a
done
NEWKERNN=$(ls -d1 lib/modules/* | tail -1 | awk -F/ 'n=NF-1 {print $n}')
depmod -a -b ./ $NEWKERNN

echo "Cоздание каталога nopae_addon"
cd "$MYPATH"
DISTRVERSION=$(date +%Y%m%d)
rm -fr flash/additions/${FLASHNAME}_${VERREL}_${DISTRVERSION}-nopae 2>/dev/null
mkdir -p flash/additions/${FLASHNAME}_${VERREL}_${DISTRVERSION}-nopae/$FLASHNAME/base
cp -p work/$FLASHNAME-$VERREL/kernel_nopae/bin/boot/vmlinuz-* flash/additions/${FLASHNAME}_${VERREL}_${DISTRVERSION}-nopae/$FLASHNAME/vmlinuz
cp -p flash/${FLASHNAME}_${VERREL}_${DISTRVERSION}/$FLASHNAME/initrd.gz flash/additions/${FLASHNAME}_${VERREL}_${DISTRVERSION}-nopae/$FLASHNAME/initrd.gz
echo "Сжатие файлов в модуль"
mksquashfs work/$FLASHNAME-$VERREL/kernel_nopae/bin flash/additions/${FLASHNAME}_${VERREL}_${DISTRVERSION}-nopae/$FLASHNAME/base/00-kernel.lzm -b 256K -lzmadic 256K
echo "Изменение initrd"
cd work/$FLASHNAME-$VERREL/kernel_nopae/bin/
find | grep [.]ko | sed s-./-- >>"$MYPATH"/flash/additions/${FLASHNAME}_${VERREL}_${DISTRVERSION}-nopae/$FLASHNAME/all_modules.list
cd "$MYPATH"/flash/additions/${FLASHNAME}_${VERREL}_${DISTRVERSION}-nopae/$FLASHNAME/
mkdir loop
gunzip initrd.gz
mount -o loop initrd loop
mv loop/drivers.lzm ./
mkdir drivers src
mount -t squashfs -o loop drivers.lzm src
cp -pR src/* drivers
umount src
rm -fr drivers.lzm src
find | grep .ko$ > modules.list
echo "Замена модулей"
for a in `cat modules.list` ;do
    MODNAME=`echo $a | awk -F/ '{print $NF}'`
    echo -ne "\r$MODNAME                 \r"
    SRCMOD=`grep /$MODNAME all_modules.list | head -1`
    rm -f $a
    cp -p "$MYPATH"/work/$FLASHNAME-$VERREL/kernel_nopae/bin/$SRCMOD $a
done
echo "Запуск depmod       "
OLDKERNN=`grep /kernel/ modules.list | head -1 | sed 's|^.*/lib/modules/||' | sed 's|/kernel/.*$||'`
NEWKERNN=`grep /kernel/ all_modules.list | head -1 | sed 's|^.*lib/modules/||' | sed 's|/kernel/.*$||'`
mv loop/lib/modules/$OLDKERNN loop/lib/modules/$NEWKERNN || exit 1
mount -o bind drivers loop/lib/modules/*/kernel/drivers
depmod -a -b loop/ $NEWKERNN
umount loop/lib/modules/*/kernel/drivers
mksquashfs drivers drivers.lzm -b 256K -lzmadic 256K || exit 1
mv drivers.lzm loop || exit 1
umount loop
gzip initrd
rm -fr drivers *.list loop

cd "$MYPATH"
cp -pfR work/$FLASHNAME-$VERREL/kernel/bin/* work/$FLASHNAME-$VERREL/rootfs
rm -fr work/$FLASHNAME-$VERREL/kernel/bin  work/$FLASHNAME-$VERREL/kernel_nopae/bin

echo "Работа скрипта завершена"

exit 0


