#!/bin/sh
[ -f /var/lock/subsys/pdnsd ] || exit 0
cat /etc/ppp/resolv.conf /var/run/resolvconf/interface/$1 2>/dev/null | grep ^nameserver > /var/cache/pdnsd/pdnsd.servers.up || \
grep ^DNS1= /etc/sysconfig/network-scripts/ifcfg-$1 2>/dev/null | sed s/^DNS1=/"nameserver "/  > /var/cache/pdnsd/pdnsd.servers.up
if grep -q nameserver /var/cache/pdnsd/pdnsd.servers.up ;then
   mv -f /var/cache/pdnsd/pdnsd.servers.up /var/cache/pdnsd/pdnsd.servers
   /etc/rc.d/init.d/pdnsd reload >/dev/null 2>&1
else
   rm -f /var/cache/pdnsd/pdnsd.servers.up
fi
true
