#!/bin/bash
#
# Helper script for MagOS Linux Live.
#
# Authors:	Mikhail Zaripov <m3for@mail.ru>
#

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0
DEBUGMODE=no
. /usr/lib/magos/scripts/liblinuxlive
. /usr/lib/magos/os-config
[ "$DEBUGMODE" = "yes" ] && debug_mode "$0" "$@"

[ "$SETCLKATSTART" != "yes" ] && exit 0
. /etc/sysconfig/clock
HWCLOCKOPIONS="--utc"
[ "$UTC" = "false" ] && HWCLOCKOPIONS="--localtime"
hwclock -s $HWCLOCKOPIONS
