#!/bin/bash
#
# Helper script for MagOS Linux Live.
#
# Authors:	Mikhail Zaripov <m3for@mail.ru>
#

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0
DEBUGMODE=no
. /usr/lib/magos/functions
. /usr/lib/magos/os-config
debug_mode "$0" "$@"

[ "$MODPROBEPRELOAD" = "no" ] && exit 0

cat /etc/modprobe.preload | sed s/'#.*'// |  sed /^$/d | while read a ;do
   modprobe $a
done