#!/bin/bash
#
# Helper script for MagOS Linux Live.
#
# Authors:	Mikhail Zaripov <m3for@mail.ru>
#

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0
DEBUGMODE=no

. /usr/lib/magos/scripts/liblinuxlive
. /usr/lib/magos/os-config

[ "$DEBUGMODE" = "yes" ] && debug_mode "$0" "$@"

[ "$MODPROBEPRELOAD" != "yes" ] && exit 0

cat /etc/modprobe.preload | sed s/'#.*'// |  sed /^$/d | while read a ;do
   modprobe $a
done