#!/bin/bash
#
# Helper script for MagOS Linux Live.
#
# Authors:	Mikhail Zaripov <m3for@mail.ru>
#

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0
DEBUGMODE=no
. /usr/lib/magos/scripts/liblinuxlive
. /usr/lib/magos/os-config
[ "$DEBUGMODE" = "yes" ] && debug_mode "$0" "$@"

# RPM5 vs ext3 bug workaround
if [ "$RPMDB2TMPFS" = "yes" ] ;then
  if ! grep -q "/memory tmpfs" /proc/mounts ;then
    # RPM5 vs ext3 bug workaround
    if ! grep -q /var/lib/rpmdb /proc/mounts ;then
      [ -d /var/lib/rpmdb ] || mkdir -p /var/lib/rpmdb
      # Removing cache
      rm -f /var/lib/rpm/__db* 2>/dev/null
      mount -t tmpfs tmpfs /var/lib/rpmdb
      rsync -a /var/lib/rpm/ /var/lib/rpmdb
      mount -o bind /var/lib/rpmdb /var/lib/rpm
    fi
  fi
fi
