#!/bin/bash
#
# Helper script for MagOS Linux Live.
#
# Authors:	Mikhail Zaripov <m3for@mail.ru>
#
# Description:  RPM bug workaround. Place rpm db into tmpfs when saving changes in folder or file on FS

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0
DEBUGMODE=no
. /usr/lib/magos/functions
. /usr/lib/magos/os-config
debug_mode "$0" "$@"

# exit if already mounted
grep -q " /var/lib/rpm " /proc/mounts && exit 0

# in case of initrd without profile
grep -q " /mnt/live/memory tmpfs " /proc/mounts && RPMDB2TMPFS=no

# in case of UIRD without profile
if grep -qE "tmpfs /memory |/dev/zram. /memory " /proc/mounts ;then
   grep -q " /memory/changes "  /proc/mounts || RPMDB2TMPFS=no
fi

if [ "$RPMDB2TMPFS" != "no" ] ;then
   # make copy of rpmdb
   mkdir -p /var/lib/rpmdb
   mount -t tmpfs tmpfs /var/lib/rpmdb
   cp -pr /var/lib/rpm/* /var/lib/rpmdb
   # move copy under real rpmdb
   mount -t tmpfs tmpfs /var/lib/rpm
   mv /var/lib/rpmdb/* /var/lib/rpm
   umount /var/lib/rpmdb && rmdir /var/lib/rpmdb
   # block FS from systemd umount-em-all actions
   touch /var/lib/rpm/.umount_lock
   losetup $(losetup -f) /var/lib/rpm/.umount_lock 2>/dev/null
fi
