#!/bin/bash
# Initial script for MagOS-Linux Live operating system
# This script are launching before starting init from linux-live script.
# Current dir allways must be set to root (/)
# All system path must be relative, except initrd dirs

export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

DEBUGMODE=no
. usr/lib/magos/functions
debug_mode "$0" "$@"

. etc/MagOS/config

ps | grep ntfsmount | awk '{ print $1 }' >> var/run/sendsigs.omit

#Setting up local time zone
[ -f etc/sysconfig/clock ] && . etc/sysconfig/clock
[ -f "usr/share/zoneinfo/$ZONE" ] && ln -sf "/usr/share/zoneinfo/$ZONE" etc/localtime

#devfs support
if [ -d run/udev/rules.d ] ;then
  mount -t devtmpfs none dev
fi

#Profile updating
VERSION=$(head -1 /VERSION)
[ -z "$VERSION" ] && VERSION=$(head -1 /memory/layer-base/0/VERSION)
if [ ! -z "$VERSION" -a -f etc/magos-release ] ;then
  grep -q "$VERSION" etc/magos-release 2>/dev/null || rm -fr /memory/changes/var/lib/rpm  /memory/changes/var/lib/urpmi 2>/dev/null
fi
[ ! -z "$VERSION" ] && echo "$VERSION"  > etc/magos-release

if [ ! -f etc/machine-id ] ;then
  echo "$MACHINEID" | grep -qi ^random$ && MACHINEID=$(dd if=/dev/urandom count=1 bs=512 2>/dev/null | cat - /sys/class/net/*/address |  md5sum | awk '{ print $1}')
  [ -z "$MACHINEID" ] && MACHINEID=$(lspci -nmm  | grep ^00  | md5sum | awk '{ print $1}')
  echo "$MACHINEID" > etc/machine-id
fi
