#!/bin/bash
# Initial script for MagOS-Linux Live operating system
# This script are launching before starting init from linux-live script.
# Current dir allways must be set to root (/)
# All system path must be relative, except initrd dirs

export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

DEBUGMODE=no
. /liblinuxlive  2>/dev/null || . /mnt/live/liblinuxlive
debug_mode "$0" "$@"

. etc/sysconfig/MagOS

[ -z "$(cmdline_value autologin)" ] || AUTOLOGINUSER=$(cmdline_value autologin)
[ -z "$AUTOLOGINUSER" ] && AUTOLOGINUSER=$(echo "$NEEDEDUSERS" | awk -F: '{print $1}')
[ -z "$AUTOLOGINUSER" ] && AUTOLOGINUSER=$(grep :500:500: etc/passwd | awk -F: '{print $1}')
[ "$AUTOLOGINUSER" = "none" ] && AUTOLOGINUSER=
sed -i s/^AutomaticLogin=.*/AutomaticLogin=$AUTOLOGINUSER/ etc/X11/gdm/custom.conf 2>/dev/null
sed -i s/^AutoLoginUser=.*/AutoLoginUser=$AUTOLOGINUSER/ usr/share/magos/kde4/share/config/kdm/kdmrc 2>/dev/null
PFP=etc/X11/slim/slim.conf
[ -f "$PFP" ] || PFP=etc/slim.conf
sed -i s/^default_user[[:space:]].*/"default_user        $AUTOLOGINUSER"/ $PFP 2>/dev/null
