#!/bin/sh

. /usr/lib/magos/functions
. /etc/sysconfig/MagOS

DE=$(detectDE)
cd $HOME

[ -z "$AUTOEXEC" ] && AUTOEXEC="kde:yakuake;gnome:guake;lxde:guake;xbindkeys"

echo "$AUTOEXEC" | tr ',;' \\n | while read a ;do
     NEEDDE=$(echo $a | grep : | awk -F: '{print $1}' | tr A-Z a-z)
     PROGRAM=${a/*:/}
     [ "$NEEDDE" -a "$NEEDDE" != "$DE" ] && continue
     [ -z "$PROGRAM" ] || "$PROGRAM" &
done

. /etc/sysconfig/compositing-wm

if [ "$COMPOSITING_WM_START" = "yes" -a "$COMPOSITING_WM" = "compiz-fusion" ] ;then
   fusion-icon -n &
fi

. /etc/sound/profiles/current/profile.conf

if [ "$SOUNDPROFILE" = "pulse" ] ;then
   if [ "$DE" = "kde" ] ;then
      start-pulseaudio-kde &
   else
      start-pulseaudio-x11 &
   fi
fi
