#!/bin/bash
#
# /usr/lib/magos/scripts/createloop
#
# Description: Create loop
# Author : Anton Goroshkin <http://magos-linux.ru>


# $1=enc
# $2=filename
# $3=size

dd if=/dev/zero of="$2" bs="$3" count=1 >/dev/null

dl=$(losetup -f)
/usr/lib/magos/losetup -e "$1" $dl "$2"

echo "y" | mkfs.ext3 $dl >/dev/null

losetup -d $dl
