#!/bin/bash
if [ "$(id -un)" != "root" ] ;then
   gksu -g "/bin/bash $0 $@"
   exit 0
fi

export PATH=/usr/lib/magos/scripts:$PATH

. liblinuxlive || exit 2
case $1 in
   --nocompress | --oldpc )
      shift
      create_module "$1" "$1.oldpc.lzm"  -noI -noD -noF -nolzma  ;;
   * )
      create_module "$1" "$1.lzm"  ;;
esac
if [ $? -eq 0 ] ; then
   mdialog --msgbox "Модуль готов"
else
   mdialog --error "Ошибка при создании модуля"
fi
