#!/bin/sh
PKDE=/usr/bin/kwrite
PGNOME=/usr/bin/gedit
PLXDE=/usr/bin/leafpad
PDEF=/usr/bin/leafpad
[ -x $PLXDE ] || PLXDE=$PDEF
[ -x $PKDE ] || PKDE=$PDEF
[ -x $PGNOME ] || PGNOME=$PDEF

. /usr/lib/magos/functions

DE=$(detectDE)

case "$DE" in
    kde)
    $PKDE "$1"
    ;;

    gnome)
    $PGNOME "$1"
    ;;

    gnome-shell)
    $PGNOME "$1"
    ;;

    lxde)
    $PLXDE "$1"
    ;;

esac

