#!/bin/bash
#
# /usr/lib/magos/scripts/epm2xzm
#
# Description: create LZM/XZM from packages (& dependences)
# Author : Anton Goroshkin <http://magos-linux.ru>
#
# $1=file or name program

cat /proc/config.gz | gunzip | grep -q SQUASHFS_XZ && MODULEFORMAT=xzm || MODULEFORMAT=lzm

[ "$1" = "" ] && exit -1

XZM_NAME=$1
shift

export PATH=/usr/lib/magos/scripts:$PATH

. liblinuxlive

if [ -f /mnt/live/VERSION ]; then
    memory_path=/mnt/live/memory
    bnd=images
else
    memory_path=/memory
    bnd=bundles
fi

mod_br=$memory_path/tmp/wiz_fly_mods
root_br=$memory_path/tmp/wiz_fly_rootfs
mod_path=$memory_path/$bnd

mount_br=$mod_br

rm -rf $mount_br $root_br
mkdir -p $mount_br $root_br

#for a in `ls -d $mod_path/??-*`; do
for a in `ls -d $mod_path/*`; do
    if [ $(cmdline_parameter unionfs) ];then
      mount_br="$mount_br:$a=ro"
    else
      mount_br="$mount_br:$a=rr"
    fi
done

if [ $(cmdline_parameter unionfs) ];then
    mount -t unionfs -o dirs=$mount_br wiz_fly $root_br
else
    mount -t aufs -o br:$mount_br wiz_fly $root_br
fi

mkdir -p $root_br/{dev,proc,sys,etc/apt,etc/urpmi}

for tm in {dev,proc,sys,etc/apt,etc/urpmi}; do
    [ /$tm ] && mount -o bind /$tm $root_br/$tm
done

mkdir -p $root_br/tmp

cp /etc/resolv.conf $root_br/etc/resolv.conf
#chroot $root_br
chroot $root_br /usr/bin/epm $@

for tm in {etc/urpmi,etc/apt,sys,proc,dev}; do
    while (grep -q $root_br/$tm /proc/mounts ) ; do
	umount $root_br/$tm
    done
done


while (grep -q wiz_fly /proc/mounts ) ; do
    umount wiz_fly
done


#dir2lzm $mod_br/var/lib/rpm $1_rpmbase.$MODULEFORMAT

rm -rf $mod_br/var/lib/rpm >/dev/null
rm -rf $mod_br/var/cache/apt >/dev/null
rm -rf $mod_br/var/cache/urpmi >/dev/null
rm -rf $mod_br/var/lib/apt/lists >/dev/null
rm -rf $mod_br/tmp >/dev/null
rm -rf $root_br/{dev,proc,sys} >/dev/null

dir2xzm $mod_br "$(basename $XZM_NAME).$MODULEFORMAT"

rm -rf $mod_br >/dev/null
rm -rf $root_br >/dev/null
