#!/bin/sh

detectDE()
{
    if [ x"$KDE_FULL_SESSION" = x"true" ]; then DE=kde;
    elif [ x"$GNOME_DESKTOP_SESSION_ID" != x"" ]; then DE=gnome;
    else DE=lxde;
    fi
}

detectDE

case "$DE" in
    kde)
    dolphin "$1"
    ;;

    gnome)
    nautilus "$1"
    ;;

    lxde)
    pcmanfm "$1"
    ;;

esac
