#!/bin/bash

. /usr/lib/magos/functions

DE=$(detectDE)

run ()
{
  if [ "$DE" = "kde" ] ; then
    krunner
  elif [  "$DE" = "gnome" ] ; then
    gnome-panel-control --run-dialog
  else
    lxpanelctl run
  fi
} 


list ()
{
  cat $HOME/.xbindkeysrc | sed -e 's/^".*"//' -e 's/Mod4/WIN/' -e s'/^#.*#//' -e 's/^#.*/&:/' -e '/^ *$/ d' > /tmp/listkeys
  if [ "$DE" = "kde" ] ; then
    kdialog --textbox /tmp/listkeys 600 600
  elif [ "$DE" = "gnome" ] ; then
    zenity --text-info --filename=/tmp/listkeys
  else
    leafpad /tmp/listkeys
  fi
  rm -f /tmp/listkeys
} 

info ()
{
  . liblinuxlive
  UPTIME=$(uptime | awk '{print "time - "$1", up - "$3}') 
  RAM=$(free -m | grep Mem | awk '{ print "total - "$2",  free - "$4}')
  SWAP=$(free -m | grep Swap | awk '{ print "total - "$2",  free - "$4}')
  CPU="$(cat /proc/cpuinfo | sed -e '/model name/!d' -e 's/^.*://')"
  CPUARCH=$(uname -p)
  KERNEL=$(uname -r)
  VIDEO=$(lspci | sed -e '/VGA/!d' -e 's/^.*://')
  GLXINFO=$(glxinfo | sed '2,3!d')
  AUDIO=$(lspci | sed -e '/Audio/!d' -e 's/^.*://')
  CMDLINE=$(cat /proc/cmdline)
  VERSION=$(cat /etc/magos-release)
  PROF_SIZE=$(df -h / |grep aufs | awk '{print " ["$5"] total - "$2", free - "$4}')
  echo "$LIVECDNAME $VERSION" > ~/info.txt
  echo "UPTIME: $UPTIME" >> ~/info.txt
  echo "KERNEL: $KERNEL" >> ~/info.txt
  echo "RAM: $RAM" >> ~/info.txt
  echo "SWAP: $SWAP" >> ~/info.txt
  [ "$(cat /proc/cmdline | grep changes= )" ] && echo "PROFILE: $PROF_SIZE" >> ~/info.txt
  echo -e "CPU: ($CPUARCH) \n$CPU" >> ~/info.txt
  echo "VIDEO: $VIDEO" >> ~/info.txt
  echo "$GLXINFO" >> ~/info.txt
  echo "AUDIO: $AUDIO" >> ~/info.txt
  echo "CMDLINE: $CMDLINE" >> ~/info.txt
  echo "MODULES:" >> ~/info.txt
  grep squashfs /proc/mounts | awk '{print $2}' | sort >> ~/info.txt
  if [ "$DE" = "kde" ] ; then
    kdialog --textbox $HOME/info.txt 600 250
  elif [ "$DE" = "gnome" ] ; then
    zenity --text-info --filename=$HOME/info.txt
  else
    leafpad $HOME/info.txt
  fi
  rm -f $HOME/info.txt
}

touchpad ()
{
  if [ $(synclient -l | grep TouchpadOff | awk '{ print $3 }') -eq 0 ] ; then
    synclient TouchpadOff=1
    if [ "$DE" = "kde" ] ; then
      kdialog --passivepopup "touсhpad отключен, WIN+t чтобы включить"
    else
      notify-send "touсhpad отключен, WIN+t чтобы включить"
    fi
  else
    synclient TouchpadOff=0
  fi
}

rfswitch ()
{
  rfkill list | grep yes
  if [ $? -eq 0 ]; then
    rfkill unblock all
  else
    rfkill block all
    if [ "$DE" = "kde" ] ; then
      kdialog --passivepopup "радиоинтерфейсы отключены, WIN+w чтобы включить"
    else
      notify-send "радиоинтерфейсы отключены, WIN+w чтобы включить"
    fi
  fi 
} 

record()
{
  killall xbindkeys
  recordmydesktop --stop-shortcut Mod4+Print
  xbindkeys
  if [ "$DE" = "kde" ] ; then
    kdialog --passivepopup "запись завершена"
  elif [ "$DE" = "gnome" ] ; then
    zenity --notification --text="запись завершена"
  else
    notify-send "запись завершена"
  fi
}

network ()
{
  echo "netstat --inet" > ~/network.txt
  netstat --inet  >> ~/network.txt
  echo -e "\nlsof -i" >> ~/network.txt
  /usr/sbin/lsof -i >> ~/network.txt
  if [ "$DE" = "kde" ] ; then
    kdialog --textbox $HOME/network.txt 600 250
  elif [ "$DE" = "gnome" ] ; then
    zenity --text-info --filename=$HOME/network.txt
  else
    leafpad $HOME/network.txt
  fi
  rm -f $HOME/info.txt
}

$1
exit
