#!/bin/bash
#
# /usr/lib/magos/scripts/mod_mnger
#
# Description: Modules Manager 
# Author : Anton Goroshkin <http://magos-linux.ru>

export PATH=/usr/lib/magos/scripts:$PATH

mdialog --msgbox "Утилита управления модулями находится в разработке. Вы можете использовать менеджер файлов для управления файлами."
filemanager_root /mnt/livemedia/MagOS/modules
filemanager_root /mnt/livemedia/MagOS/optional
