#!/bin/bash
path=/mnt/livemedia/MagOS/modules
cat /mnt/live/etc/modules | grep -q MagOS-Data && path=/mnt/livemedia/MagOS-Data/modules
zcat /proc/config.gz | grep -q SQUASHFS_XZ && MODULEFORMAT=xzm || MODULEFORMAT=lzm

ENABLE()
{
   sed -i '/^SAVETOMODULE.*/d' /etc/sysconfig/MagOS
   echo "SAVETOMODULE=yes" >> /etc/sysconfig/MagOS
   SAVETOMODULENAME="$2"
   [ "${2}_" == "_" ] &&  SAVETOMODULENAME="$path/zz-save-$(date +%F_%H-%M).$MODULEFORMAT"
   echo "SAVETOMODULENAME=$SAVETOMODULENAME" >> /etc/sysconfig/MagOS
}

DISABLE()
{
   sed -i '/^SAVETOMODULE.*/d' /etc/sysconfig/MagOS
}

STATUS()
{
   . /etc/sysconfig/MagOS
   status=disabled
   [ "$SAVETOMODULE" = "yes" ] &&  status=enabled
   [ "$SAVETOMODULENAME" = "" ] && SAVETOMODULENAME=/mnt/livemedia/MagOS/optional/zz-save.$MODULEFORMAT
   echo "$status $SAVETOMODULENAME"
}

HELP()
{
   cat <<EOF
Script to control SAVETOMODULE mode
Usage:
--enable </path/file.$MODULEFORMAT>
--disable
--status
--help
EOF
}

cmd=$1

[ "$cmd" = "" ] &&  cmd="--status" 

case $cmd in
   -h | --help )
      HELP ;;
   --status )
      STATUS ;;
   --enable )
      ENABLE $@ ;;
   --disable )
      DISABLE ;;
esac

exit 0
