#!/bin/bash

function update_app
{
 [ -f "/usr/share/applications/$1.desktop" ] && sed -i "s/^.*Categories=.*$/Categories=$2/" /usr/share/applications/$1.desktop
}

function update_app_tag
{
 [ -f "/usr/share/applications/$1.desktop" ] || return
 KEY=$(echo $2| sed s/'\['/./g | sed s/'\]'/./g)
 grep -iq "^$KEY=$3" "/usr/share/applications/$1.desktop" && return
 if grep -iq "^$KEY=" "/usr/share/applications/$1.desktop" ;then
   sed -i s/"^$KEY=.*"/"$2=$3"/ "/usr/share/applications/$1.desktop"
 else
   sed -i s/'\[Desktop Entry\]'/"[Desktop Entry]\\n$2=$3"/ "/usr/share/applications/$1.desktop"
 fi
}

ln -sf MagOS-applications.menu /etc/xdg/menus/applications.menu
ln -sf MagOS-applications.menu /etc/xdg/menus/kde-applications.menu
ln -sf MagOS-applications.menu /etc/xdg/menus/lxqt-applications.menu

update_app cheese "GNOME;AudioVideo;Recorder;"
update_app devede "AudioVideo;DiscBurning;"
update_app gnomecc "GNOME;GTK;Settings;X-MandrivaLinux-System-Configuration-GNOME;"
update_app gnome-ppp "Network;GNOME;Dialup;"
update_app gnome-screenshot "GTK;GNOME;Utility;Graphics;Scanning;"
update_app gnome-system-monitor "GNOME;GTK;System;Monitor;"
update_app gxneur "GTK;GNOME;Settings;HardwareSettings;"
update_app lxrandr "Settings;X-LXDE-Settings;"
update_app lxtask "GTK;System;Monitor;X-LXDE-Settings;"
update_app mandriva-grip "GTK;AudioVideo;Audio;AudioRipper;"
update_app mandriva-mountloop "Security;System;"
update_app mandriva-mtink "System;Printing;"
update_app mandriva-tightvnc "Network;RemoteAccess;"
update_app mandriva-z42tool "System;Printing;"
update_app net_applet "GTK;Network;Monitor;X-MandrivaLinux-CrossDesktop;"
update_app obconf "Settings;DesktopSettings;GTK;X-LXDE-Settings;"
update_app remmina "GTK;GNOME;X-GNOME-NetworkSettings;Network;RemoteAccess;"
update_app org.remmina.Remmina "GTK;GNOME;X-GNOME-NetworkSettings;Network;RemoteAccess;"
update_app djvulibre-djview3 "Qt;Office;Viewer;"
update_app djvulibre-djview4 "Qt;Office;Viewer;"
update_app startcenter "Office;Editor;"
update_app draw "Office;Editor;X-MandrivaLinux-CrossDesktop;"
update_app base "Office;Editor;X-MandrivaLinux-CrossDesktop;"
update_app web "Office;Editor;X-MandrivaLinux-CrossDesktop;"
update_app dia "Office;Editor;X-MandrivaLinux-CrossDesktop;"
update_app libreoffice-base "Office;Editor;;X-MandrivaLinux-CrossDesktop;"
update_app libreoffice-calc "Office;Editor;X-MandrivaLinux-CrossDesktop;"
update_app libreoffice-draw "Office;Editor;X-MandrivaLinux-CrossDesktop;"
update_app libreoffice-impress "Office;Editor;X-MandrivaLinux-CrossDesktop;"
update_app libreoffice-math "Office;Editor;X-MandrivaLinux-CrossDesktop;"
update_app libreoffice-startcenter "Office;Editor;X-MandrivaLinux-CrossDesktop;"
update_app libreoffice-writer "Office;Editor;X-MandrivaLinux-CrossDesktop;"
update_app java-1.6.0-sun-controlpanel "Settings;X-MandrivaLinux-CrossDesktop;"
update_app java-1.6.0-sun-javaws "Settings;X-MandrivaLinux-CrossDesktop;"
update_app java-1.6.0-sun-javaws_viewer "Settings;X-MandrivaLinux-CrossDesktop;"
update_app java-1.6.0-sun-policytool "Settings;X-MandrivaLinux-CrossDesktop;"
update_app gparted "GTK;System;Filesystem;Settings;HardwareSettings;X-MandrivaLinux-System-Configuration;"
update_app rawtherapee "GTK;Graphics;2DGraphics;RasterGraphics;X-MandrivaLinux-CrossDesktop;"
update_app nautilus-browser "GNOME;GTK;System;Utility;Core;FileManager;"
update_app PlayOnLinux "Emulator;"
update_app easytag "Audio;AudioVideoEditing;GTK;X-MandrivaLinux-CrossDesktop;"
update_app parcellite "Settings;X-LXDE-Settings;"
update_app gucharmap "GNOME;GTK;Utility;TextTools;"
update_app gnome-disks "GTK;System;Filesystems;Settings;HardwareSettings;"
update_app gsmartcontrol "GTK;System;Filesystems;Settings;HardwareSettings;"
update_app nautilus "GNOME;GTK;Utility;Core;FileManager;"
update_app gnome-search-tool "GNOME;GTK;Utility;Core;FileManager;"
update_app gnome-tweak-tool "GNOME;GTK;DesktopSettings;X-GNOME-PersonalSettings;"
update_app yelp "GNOME;GTK;Core;Documentation;"
update_app rpmdrake "GNOME;GTK;PackageManager;"
update_app lxde-ctrl-center "Settings;X-LXDE-Settings;"
update_app gigolo "GTK;Filesystems;Network;"
update_app system-config-nfs "Filesystems;Network;"
update_app system-config-samba "GTK;Filesystems;Network;"
update_app mdvinput "GTK;Settings;HardwareSettings;"
update_app add2sudoers "Settings;System;X-MandrivaLinux-CrossDesktop;"
update_app rmfromsudoers "Settings;System;X-MandrivaLinux-CrossDesktop;"
update_app meld "GTK;TextTools;"
update_app mandriva-wireshark-root "Network;Capture;"
update_app mandriva-wireshark "Network;Capture;"
update_app wireshark "Network;Capture;"
update_app etherape "GTK;Network;Capture;"
update_app gnome-nettool "GTK;Network;Monitor;"
update_app lxshortcut "GTK;X-LXQT-Settings;"
update_app drakxservices "Settings;System;X-MandrivaLinux-CrossDesktop;"
update_app XFdrake "GTK;Settings;HardwareSettings;"
update_app vidalia "Qt;Utility;Security;"
update_app devedeng "AudioVideo;DiscBurning;"
update_app android-file-transfer "Qt;Utility;FileManager;FileTools;"
update_app kdeneur "Qt;Utility;TextTools;"
update_app steam "Game;"
update_app lximage-qt-screenshot "Qt;Graphics;Scanning;"
update_app z42tool "System;Printing;"
update_app ponoff "GTK;Network;Monitor;Control;"
update_app vpnpptp "GTK;Network;Monitor;Control;"
update_app modem-manager-gui "TelephonyTools;HardwareSettings;"
update_app obconf-qt "Qt;DesktopSettings;X-LXQT-Settings;"
update_app pcmanfm-qt-desktop-pref "Qt;DesktopSettings;X-LXQT-Settings;"
update_app compton-conf "Qt;DesktopSettings;X-LXQT-Settings;"
update_app lftp "Network;FileTransfer;"
update_app io.github.qtox.qTox "Network;Chat;Telephony;"
update_app drakxdisks "Categories=System;Filesystem;Settings;HardwareSettings;"
update_app xcam "GTK;Graphics;Scanning;"
update_app devede_ng.py "Video;AudioVideoEditing;AudioVideo;"
update_app lximage-qt "Graphics;Viewer;2DGraphics;"
update_app mandriva-usermount.desktop "System;Filesystem;Settings;HardwareSettings;Utility;"

update_app kde-qt5-fsarchiver "Qt;System;Filesystem;Settings;HardwareSettings;X-MandrivaLinux-System-Configuration;"
update_app org.kde.kruler "Qt;KDE;Graphics;Scanning;"
update_app org.kde.kfloppy "Qt;KDE;X-KDE-settings-peripherals;"
update_app kde4/akonaditray "Qt;KDE;X-KDE-Utilities-PIM;"
update_app kde4/dolphin "Qt;KDE;System;Utility;Core;FileManager;"
update_app kde4/filelight "Qt;KDE;Utility;X-MandrivaLinux-System-FileTools;"
update_app kde4/kcalc "Qt;KDE;Calculator;"
update_app kde4/KCharSelect "Qt;KDE;Utility;TextTools;"
update_app kde4/kcolorchooser "Qt;KDE;Graphics;Scanning;"
update_app kde4/kdf "Qt;KDE;System;X-KDE-settings-peripherals;"
update_app kde4/kleopatra "Qt;KDE;Utility;Security;"
update_app kde4/krandrtray "Qt;KDE;System;HardwareSettings;"
update_app kde4/krename "Qt;KDE;Utility;FileManager;"
update_app kde4/krusader_root-mode "Qt;KDE;FileManager;"
update_app kde4/ksnapshot "Qt;KDE;Graphics;Scanning;"
update_app kde4/ksysguard "Qt;KDE;System;Monitor;"
update_app kde4/ktimer "Qt;KDE;X-KDE-Utilities-PIM;"
update_app kde4/kwikdisk "Qt;KDE;X-KDE-settings-peripherals;"
update_app kde4/sweeper "Qt;KDE;Utility;Security;"
update_app kde4/okular "Qt;KDE;Office;Viewer;"
update_app kde4/knotes "Qt;KDE;Utility;TextTools;"
update_app kde4/Kjots "Qt;KDE;Utility;TextTools;"
update_app kde4/irkick "Qt;KDE;X-KDE-settings-peripherals;"
update_app kde4/KFloppy "Qt;KDE;X-KDE-settings-peripherals;"
update_app kde4/bluedevil-monolithic "Qt;KDE;X-Bluetooth;X-KDE-settings-peripherals;"
update_app kde4/kruler "Qt;KDE;Graphics;Scanning;"
update_app kde4/kgpg "Qt;KDE;Utility;Security;"
update_app kde4/nepomukcleaner "Qt;KDE;X-KDE-Utilities-Desktop;"
update_app kde5/org.kde.kcolorchooser "Qt;KDE;Graphics;Scanning;"
update_app kde5/org.kde.kruler "Qt;KDE;Graphics;Scanning;"
update_app kde5/org.kde.kamoso "Qt;KDE;AudioVideo;Recorder;"
update_app kde5/org.kde.filelight "Qt;KDE;Utility;X-MandrivaLinux-System-FileTools;"
update_app kde5/org.kde.kcharselect "Qt;KDE;Utility;TextTools;"
update_app kde5/org.kde.kfloppy "Qt;KDE;X-KDE-settings-peripherals;"
update_app kde5/org.kde.kfind "Qt;KDE;Utility;FileTools;"
update_app kde5/org.kde.kgpg "Qt;KDE;Utility;Security;"
update_app kde5/systemsettings "Qt;KDE;X-Plasma-Settings;"
update_app kde5/org.kde.spectacle "Qt;KDE;Graphics;Scanning;"
update_app kde5/org.kde.kdeconnect.app "Qt;KDE;X-KDE-settings-peripherals;"
update_app kde5/org.kde.krename "Qt;KDE;Utility;FileManager;"
update_app kde5/org.kde.sweeper "Qt;KDE;Utility;Security;"
update_app kde5/org.kde.kdeconnect_open "Qt;KDE;X-KDE-settings-peripherals;"
update_app kde5/org.kde.kdeconnect.nonplasma "Qt;KDE;X-KDE-settings-peripherals;"
update_app kde5/kshutdown "Qt;KDE;X-Plasma-Settings;"
update_app kde5/org.kde.plasma.emojier "Qt;KDE;X-Plasma-Settings;"

update_app_tag mate-font-viewer OnlyShowIn MATE
update_app_tag fusion-icon Exec "fusion-icon -n"

update_app_tag gparted Exec "gksu -lg gparted"
update_app_tag gparted "Name[ru]" "GParted-управление разделами"
update_app_tag gparted "Comment[ru]" "GParted-управление разделами"

HIDEPROGS="$(ls -1 2>/dev/null /usr/share/applications/java*policytool.desktop | sed s=.*/== | sed s/[.]desktop//)"
HIDEPROGS="$HIDEPROGS fusion-icon emerald-theme-manager kde5/kshutdown"
for a in $HIDEPROGS ;do
   update_app_tag $a Hidden true
done

[ -f /usr/share/applications/pavucontrol.desktop -a -f /usr/share/applications/pavucontrol-qt.desktop ] && mv -f /usr/share/applications/pavucontrol-qt.desktop /usr/share/applications/pavucontrol.desktop

exit 0
