#!/bin/bash
# Initial script for MagOS-Linux Live operating system
# This script are launching before starting init from linux-live script.
# Current dir allways must be set to root (/)
# All system path must be relative, except initrd dirs

export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0


DEBUGMODE=no
. /liblinuxlive  2>/dev/null || . /mnt/live/liblinuxlive
debug_mode "$0" "$@"
 
if [ -d /mnt/livedata -a ! -w /mnt/livemedia -a -f usr/share/applications/install-helper.desktop ] ;then
   mkdir -p etc/skel/Desktop
   cp usr/share/applications/install-helper.desktop etc/skel/Desktop/ && echodebug "install-helper.desktop added  to skel "
fi

if [ -f etc/sysconfig/steam ] ;then
  . etc/sysconfig/steam
  rm -f etc/skel/.steam etc/skel/.local/share/Steam 2>/dev/null
  [ -z "$STEAMCONF" ] || ln -sf "$STEAMCONF" etc/skel/.steam
  [ -z "$STEAMAPP" ] && STEAMAPP=/mnt/livedata/MagOS-Data/steam
  ln -sf "$STEAMAPP" etc/skel/.local/share/Steam
fi
