#!/bin/bash
# Initial script for MagOS-Linux Live operating system
# This script are launching before starting init from linux-live script.
# Current dir allways must be set to root (/)
# All system path must be relative, except initrd dirs

export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

DEBUGMODE=no
. /liblinuxlive  2>/dev/null || . /mnt/live/liblinuxlive
. usr/lib/magos/os-config
debug_mode "$0" "$@"

. etc/sysconfig/MagOS
[ -f /tmp/.credential ] && . /tmp/.credential && rm -f /tmp/.credential
[ -z "$NEEDEDUSERS" ] && NEEDEDUSERS="$DEFAULTUSER:500:$DEFAULTPASSWD"
[ -z "$(cmdline_value users)" ] || NEEDEDUSERS=$(cmdline_value users)
[ "$NOSECUREROOTPASSWD" = "$DEFAULTROOTPASSWD" ] && ADDADM=yes

#$1 - username
#$2 - passwd
function set_passwd()
{
  sed -i /^$1:/d etc/shadow
  echo "$1:$2:16704:0:99999:7:::" >> etc/shadow
  sed -i s/$1:[!]*:/$1:x:/ etc/passwd
  if [ -d etc/tcb/$1 ] ;then 
     sed -i /^$1:/d etc/tcb/$1/shadow
     echo "$1:$2:16704:0:99999:7:::" >> etc/tcb/$1/shadow
  fi
}


for a in $(echo $NEEDEDUSERS | tr ",;" " " ) ;do
  NEEDEDUSER=$(echo $a | awk -F: '{ print $1 }')
  NEEDEDUID=$(echo $a | awk -F: '{ print $2 }')
  NEEDEDPASS=$(echo $a | awk -F: '{ print $3 }')
  [ "$NEEDEDPASS" = "x" ] && NEEDEDPASS="$DEFAULTPASSWD"
  ADDGROUPS=$USERGROUPS
  [ "$NEEDEDUID" = "$ADMUID" -a "$ADDADM" = "yes"  ] && ADDGROUPS=$USERGROUPS,$ADMGROUPS
  # create user
  if ! grep -q ^$NEEDEDUSER: etc/passwd ;then
    chroot . usr/sbin/adduser -M -G users -u $NEEDEDUID $NEEDEDUSER >/dev/null  2>&1 || chroot . usr/sbin/useradd -M -G users -u $NEEDEDUID $NEEDEDUSER >/dev/null  2>&1
  fi
  # add to groups
  chroot . usr/sbin/usermod -a -G $ADDGROUPS $NEEDEDUSER >/dev/null  2>&1
  # set passwordd
  [ "$NEEDEDPASS" = "" ] || set_passwd "$NEEDEDUSER" "$NEEDEDPASS"
  # create home
  if ! [ -d home/$NEEDEDUSER ] ;then
    cp -a etc/skel home/$NEEDEDUSER
    chroot . bin/chown -R $NEEDEDUSER.$NEEDEDUSER /home/$NEEDEDUSER
    chmod 700 home/$NEEDEDUSER
  elif [ "$UPDATEHOME" = "yes" ] ;then
    rsync  -rlpt --ignore-existing etc/skel/ home/$NEEDEDUSER
    chroot . bin/chown -R $NEEDEDUSER.$NEEDEDUSER /home/$NEEDEDUSER
  fi
done
set_passwd root "$DEFAULTROOTPASSWD"
