#!/bin/bash
# Initial script for MagOS-Linux Live operating system
# This script are launching before starting init from linux-live script.
# Current dir allways must be set to root (/)
# All system path must be relative, except initrd dirs

export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

ENABLED=yes
[ "$ENABLED" != "yes" ] && exit 0

DEBUGMODE=no
. /liblinuxlive  2>/dev/null || . /mnt/live/liblinuxlive
debug_mode "$0" "$@"

DEFAULTPASSWD='$2a$08$7zaCsmtvyXcGKVC3jRkUkeLnscv6s0mkXJ4GnJfrMzgmcMZzvF2a2'
DEFAULTROOTPASSWD='$2a$08$6Sd1ei3xkrWq21ypHSlgZOOlViPgyi4u.g7P0hZgpHx43cWwjO/Ji'
DEFAULTUSER=user
USERGROUPS=audio,video,usb,vboxusers
NOSECUREROOTPASSWD=$DEFAULTROOTPASSWD
ADMGROUPS=wheel
ADMUID=500
ADDADM=no

. etc/sysconfig/MagOS
[ -f /tmp/.credential ] && . /tmp/.credential && rm -f /tmp/.credential
[ -z "$NEEDEDUSERS" ] && NEEDEDUSERS="$DEFAULTUSER:500:$DEFAULTPASSWD"
[ -z "$(cmdline_value users)" ] || NEEDEDUSERS=$(cmdline_value users)
[ "$NOSECUREROOTPASSWD" = "$DEFAULTROOTPASSWD" ] && ADDADM=yes

for a in $(echo $NEEDEDUSERS | tr ",;" " " ) ;do
   NEEDEDUSER=$(echo $a | awk -F: '{ print $1 }')
   NEEDEDUID=$(echo $a | awk -F: '{ print $2 }')
   NEEDEDPASS=$(echo $a | awk -F: '{ print $3 }')
   [ "$NEEDEDPASS" = "x" ] && NEEDEDPASS="$DEFAULTPASSWD"
   ADDGROUPS=$USERGROUPS
   [ "$NEEDEDUID" = "$ADMUID" -a "$ADDADM" = "yes"  ] && ADDGROUPS=$USERGROUPS,$ADMGROUPS
   if ! grep -q ^$NEEDEDUSER: etc/passwd ;then
        chroot . usr/sbin/adduser -M -G users -u $NEEDEDUID $NEEDEDUSER >/dev/null  2>&1
        chroot . usr/sbin/usermod -a -G $ADDGROUPS $NEEDEDUSER >/dev/null  2>&1
        chroot . usr/bin/passwd -uf $NEEDEDUSER >/dev/null  2>&1
        [ "$NEEDEDPASS" = "" ] || sed -i s=^$NEEDEDUSER::=$NEEDEDUSER:"$NEEDEDPASS":= etc/shadow
   else
        [ "$NEEDEDPASS" != "$DEFAULTPASSWD" -a "$NEEDEDPASS" != "" ] && chroot . usr/bin/passwd -d $NEEDEDUSER >/dev/null  2>&1
        sed -i s=^$NEEDEDUSER::=$NEEDEDUSER:"$NEEDEDPASS":= etc/shadow
   fi
   if ! [ -d home/$NEEDEDUSER ] ;then
        cp -a etc/skel home/$NEEDEDUSER
        chroot . bin/chown -R $NEEDEDUSER.$NEEDEDUSER /home/$NEEDEDUSER
        chmod 700 home/$NEEDEDUSER
   elif [ "$UPDATEHOME" = "yes" ] ;then
	rsync  -rlpt --ignore-existing etc/skel/ home/$NEEDEDUSER
        chroot . bin/chown -R $NEEDEDUSER.$NEEDEDUSER /home/$NEEDEDUSER
   fi
done
sed -i s=^root::=root:"$DEFAULTROOTPASSWD":= etc/shadow
