#!/bin/bash

# Это файл с параметрами для скриптов

MYPATH="`pwd`"

# Название флешки. Можете менять только  чур без пробелов и русских букв
FLASHNAME=MagOS

# Размер в Мб для данных и изменений системы для каждого профиля
DATASIZE1=512
DATASIZE2=256

#STATUS=devel
STATUS=official
VERREL=Mageia2
# на 64 бит врядли стоит собирать, теряется универсальность
# но под конкретную машину может и есть смысл. Тогда будьте готовы к возможным проблемам 
# со скриптами linux-live, там бинарники собраны под 32бита
ARCH=i586

# Службы которые будут загружаться при загрузке. Порядок перечисления важен.
INITDNEED=" rsyslog acpid udev-post messagebus haldaemon alsa sound resolvconf  \
 iptables network network-up pdnsd dm resolvconf wine gpm xinetd"

# ключи для команды mksquashfs при создании модулей
MKSQOPT="-b 512K"
SQFSVER=4

#Директории
MOD_ROOTFS_DIR=work/$FLASHNAME-$VERREL
MOD_NAMES_DIR=mod_names
ROOTFS=$MOD_ROOTFS_DIR/rootfs
MOD_PREV=work/urpmi_root
MOD_RPMS=work/rpms

#Параметры urpmi
URPMI_PARAM=" --noclean --no-suggests "

#Файловая система unionfs или aufs
FS_ROOTFS=aufs
#FS_ROOTFS=unionfs

# Список репозиториев
DIST_MIRROR_0=http://mirror.yandex.ru/mageia/distrib/2/i586/
DIST_MIRROR_1=http://packages.mageialinux.ru/mageia2/i586/
DIST_MIRROR_2=http://packages.mageialinux.ru/mageiaos/i586
