#!/bin/sh
#
# UIRD Init script
# Author: Anton Goroshkin <http://magos-linux.ru>
#

. /livekitlib
#. /lib/magos-lib.sh

#transfer_initramfs

UNION=$NEWROOT

MEMORY=/memory
CHANGES=$MEMORY/changes
CACHE=$MEMORY/cache
DATAMNT=$MEMORY/data
BUNDLES=$MEMORY/bundles
COPY2RAM=$MEMORY/copy2ram
COPY2CACHE=$MEMORY/copy2cache
MOUNTDIR=$DATAMNT
LAYER_BASE=$DATAMNT/layer-base

LIVEKITNAME="MagOS"

echo "0" >/proc/sys/kernel/printk

header "Starting UIRD init <http://magos-linux.ru/>"

mkdir -p $MEMORY
mount -t tmpfs -o size="100%" tmpfs $MEMORY

debug_start
                                                                                                                                                      debug_shell
init_aufs

# find data dir with filesystem bundles
#DATA="$(find_data 60 "$DATAMNT")"

#init BASE layer
init_layer $LAYER_BASE uird.from
                                                                                                                                                      debug_shell
# setup persistent changes, if possible
#persistent_changes "$DATA" "$CHANGES"

# init CACHE layer
init_layer $CACHE uird.cache
																	              debug_shell
                                                                                                                                                      debug_shell
# copy to RAM if needed
DATA_RAM="$(copy_to_ram "$DATA" "$COPY2RAM")"
                                                                                                                                                      debug_shell
# init aufs union
init_union "$CHANGES" "$UNION"
                                                                                                                                                      debug_shell
# add data from BASE layer to union
for d_dirs in "$LAYER_BASE" ;do
    # copy to CACHE if needed
    DATA_CACHE="$(copy_to_cache $d_dirs "$CACHE")"
done

# add data to union
for d_dirs in "$LAYER_BASE" "$DATA_CACHE";do
    union_append_bundles $d_dirs "$BUNDLES" "$UNION"
done
                                                                                                                                                      debug_shell

# rootcopy
#copy_rootcopy_content "$DATA" "$UNION"

# create empty fstab
#fstab_create "$UNION"
                                                                                                                                                      debug_shell
#header "Live Kit done, starting $LIVEKITNAME"
#change_root "$UNION"

#header "!!ERROR occured, you shouldn't be here.!!"
#/bin/sh

echolog "recreating /etc/fstab and /mnt directories"
touch $UNION/etc/fstab
#rmdir $UNION/mnt/* 2>/dev/null
fstab_update $UNION

mkdir -p $UNION/mnt/live
cp liblinuxlive $UNION/mnt/live/liblinuxlive

cd $UNION
[ -x "etc/rc.d/rc.preinit" ] && /bin/bash etc/rc.d/rc.preinit


#need for usable_root of dracut
mkdir -p $UNION/proc $UNION/sys $UNION/dev $UNION/$MEMORY

#need TODO
mount --move $MEMORY $UNION/$MEMORY

header "UIRD init done, starting $LIVEKITNAME"

