#!/bin/bash
#
# Helper script for MagOS Linux Live.
#
# Authors:	Mikhail Zaripov <m3for@mail.ru>
#

# RPM5 vs ext3 bug workaround
RPMDBITEMS="alternatives Packages filetriggers modules log DB_CONFIG"
[ -f /etc/sysconfig/MagOS ] && . /etc/sysconfig/MagOS

grep -q "tmpfs /mnt/live/memory tmpfs" /proc/mounts && exit 0

# RPM5 vs ext3 bug workaround
if ! grep -q /var/lib/rpmdb /proc/mounts ;then
   [ -d /var/lib/rpmdb ] || mkdir -p /var/lib/rpmdb
   # Removing all except Packages
   [ -f /var/lib/rpm/__db.001 ] && /usr/lib/rpm/bin/dbconvert
   mount -o bind /var/lib/rpm /var/lib/rpmdb
   mount -t tmpfs tmpfs /var/lib/rpm
   for a in $RPMDBITEMS ;do
       ln -s /var/lib/rpmdb/$a /var/lib/rpm
   done
fi
